{-# OPTIONS_GHC -w #-}
{-# OPTIONS -w #-}
-- Haskell module generated by grm *** DO NOT EDIT ***


module Language.LLVM.Par where
import Grm.Prims
import Grm.Lex
import Language.LLVM.Abs

-- parser produced by Happy Version 1.18.6

data HappyAbsSyn t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38
	= HappyTerminal ((Token Point))
	| HappyErrorToken Int
	| HappyAbsSyn4 t4
	| HappyAbsSyn5 t5
	| HappyAbsSyn6 t6
	| HappyAbsSyn7 t7
	| HappyAbsSyn8 t8
	| HappyAbsSyn9 t9
	| HappyAbsSyn10 t10
	| HappyAbsSyn11 t11
	| HappyAbsSyn12 t12
	| HappyAbsSyn13 t13
	| HappyAbsSyn14 t14
	| HappyAbsSyn15 t15
	| HappyAbsSyn16 t16
	| HappyAbsSyn17 t17
	| HappyAbsSyn18 t18
	| HappyAbsSyn19 t19
	| HappyAbsSyn20 t20
	| HappyAbsSyn21 t21
	| HappyAbsSyn22 t22
	| HappyAbsSyn23 t23
	| HappyAbsSyn24 t24
	| HappyAbsSyn25 t25
	| HappyAbsSyn26 t26
	| HappyAbsSyn27 t27
	| HappyAbsSyn28 t28
	| HappyAbsSyn29 t29
	| HappyAbsSyn30 t30
	| HappyAbsSyn31 t31
	| HappyAbsSyn32 t32
	| HappyAbsSyn33 t33
	| HappyAbsSyn34 t34
	| HappyAbsSyn35 t35
	| HappyAbsSyn36 t36
	| HappyAbsSyn37 t37
	| HappyAbsSyn38 t38

action_0 (63) = happyShift action_5
action_0 (64) = happyShift action_6
action_0 (128) = happyShift action_7
action_0 (4) = happyGoto action_8
action_0 (5) = happyGoto action_2
action_0 (37) = happyGoto action_3
action_0 (38) = happyGoto action_4
action_0 _ = happyReduce_119

action_1 (63) = happyShift action_5
action_1 (64) = happyShift action_6
action_1 (128) = happyShift action_7
action_1 (5) = happyGoto action_2
action_1 (37) = happyGoto action_3
action_1 (38) = happyGoto action_4
action_1 _ = happyFail

action_2 _ = happyReduce_120

action_3 _ = happyReduce_1

action_4 (63) = happyShift action_5
action_4 (64) = happyShift action_6
action_4 (128) = happyShift action_7
action_4 (5) = happyGoto action_22
action_4 _ = happyReduce_118

action_5 (47) = happyShift action_12
action_5 (53) = happyShift action_13
action_5 (65) = happyShift action_14
action_5 (71) = happyShift action_15
action_5 (81) = happyShift action_16
action_5 (82) = happyShift action_17
action_5 (117) = happyShift action_18
action_5 (123) = happyShift action_19
action_5 (128) = happyShift action_20
action_5 (20) = happyGoto action_21
action_5 _ = happyFail

action_6 (47) = happyShift action_12
action_6 (53) = happyShift action_13
action_6 (65) = happyShift action_14
action_6 (71) = happyShift action_15
action_6 (81) = happyShift action_16
action_6 (82) = happyShift action_17
action_6 (117) = happyShift action_18
action_6 (123) = happyShift action_19
action_6 (128) = happyShift action_20
action_6 (20) = happyGoto action_11
action_6 _ = happyFail

action_7 (51) = happyShift action_9
action_7 (52) = happyShift action_10
action_7 _ = happyFail

action_8 (132) = happyAccept
action_8 _ = happyFail

action_9 (109) = happyShift action_33
action_9 _ = happyFail

action_10 (131) = happyShift action_32
action_10 _ = happyFail

action_11 (40) = happyShift action_23
action_11 (42) = happyShift action_24
action_11 (128) = happyShift action_31
action_11 _ = happyFail

action_12 _ = happyReduce_86

action_13 (131) = happyShift action_30
action_13 _ = happyFail

action_14 _ = happyReduce_83

action_15 _ = happyReduce_82

action_16 (131) = happyShift action_29
action_16 _ = happyFail

action_17 _ = happyReduce_90

action_18 _ = happyReduce_84

action_19 (47) = happyShift action_12
action_19 (53) = happyShift action_13
action_19 (65) = happyShift action_14
action_19 (71) = happyShift action_15
action_19 (81) = happyShift action_16
action_19 (82) = happyShift action_17
action_19 (117) = happyShift action_18
action_19 (123) = happyShift action_19
action_19 (128) = happyShift action_20
action_19 (20) = happyGoto action_26
action_19 (25) = happyGoto action_27
action_19 (26) = happyGoto action_28
action_19 _ = happyReduce_98

action_20 _ = happyReduce_87

action_21 (40) = happyShift action_23
action_21 (42) = happyShift action_24
action_21 (128) = happyShift action_25
action_21 _ = happyFail

action_22 _ = happyReduce_121

action_23 (47) = happyShift action_12
action_23 (53) = happyShift action_13
action_23 (65) = happyShift action_14
action_23 (71) = happyShift action_15
action_23 (81) = happyShift action_16
action_23 (82) = happyShift action_17
action_23 (117) = happyShift action_18
action_23 (123) = happyShift action_19
action_23 (128) = happyShift action_20
action_23 (20) = happyGoto action_26
action_23 (25) = happyGoto action_41
action_23 (26) = happyGoto action_28
action_23 _ = happyReduce_98

action_24 _ = happyReduce_80

action_25 (40) = happyShift action_40
action_25 _ = happyFail

action_26 (40) = happyShift action_23
action_26 (42) = happyShift action_24
action_26 _ = happyReduce_99

action_27 (125) = happyShift action_39
action_27 _ = happyFail

action_28 (43) = happyShift action_38
action_28 _ = happyReduce_97

action_29 _ = happyReduce_81

action_30 (118) = happyShift action_37
action_30 _ = happyFail

action_31 (40) = happyShift action_36
action_31 _ = happyFail

action_32 (119) = happyShift action_35
action_32 _ = happyFail

action_33 (47) = happyShift action_12
action_33 (53) = happyShift action_13
action_33 (65) = happyShift action_14
action_33 (71) = happyShift action_15
action_33 (81) = happyShift action_16
action_33 (82) = happyShift action_17
action_33 (117) = happyShift action_18
action_33 (123) = happyShift action_19
action_33 (128) = happyShift action_20
action_33 (20) = happyGoto action_34
action_33 _ = happyFail

action_34 (40) = happyShift action_23
action_34 (42) = happyShift action_24
action_34 _ = happyReduce_4

action_35 (39) = happyShift action_50
action_35 _ = happyFail

action_36 (47) = happyShift action_12
action_36 (53) = happyShift action_13
action_36 (65) = happyShift action_14
action_36 (71) = happyShift action_15
action_36 (81) = happyShift action_16
action_36 (82) = happyShift action_17
action_36 (117) = happyShift action_18
action_36 (123) = happyShift action_19
action_36 (128) = happyShift action_20
action_36 (16) = happyGoto action_46
action_36 (20) = happyGoto action_47
action_36 (31) = happyGoto action_48
action_36 (32) = happyGoto action_49
action_36 _ = happyFail

action_37 (47) = happyShift action_12
action_37 (53) = happyShift action_13
action_37 (65) = happyShift action_14
action_37 (71) = happyShift action_15
action_37 (81) = happyShift action_16
action_37 (82) = happyShift action_17
action_37 (117) = happyShift action_18
action_37 (123) = happyShift action_19
action_37 (128) = happyShift action_20
action_37 (20) = happyGoto action_45
action_37 _ = happyFail

action_38 (47) = happyShift action_12
action_38 (53) = happyShift action_13
action_38 (65) = happyShift action_14
action_38 (71) = happyShift action_15
action_38 (81) = happyShift action_16
action_38 (82) = happyShift action_17
action_38 (117) = happyShift action_18
action_38 (123) = happyShift action_19
action_38 (128) = happyShift action_20
action_38 (20) = happyGoto action_44
action_38 _ = happyFail

action_39 _ = happyReduce_88

action_40 (47) = happyShift action_12
action_40 (53) = happyShift action_13
action_40 (65) = happyShift action_14
action_40 (71) = happyShift action_15
action_40 (81) = happyShift action_16
action_40 (82) = happyShift action_17
action_40 (117) = happyShift action_18
action_40 (123) = happyShift action_19
action_40 (128) = happyShift action_20
action_40 (20) = happyGoto action_26
action_40 (25) = happyGoto action_43
action_40 (26) = happyGoto action_28
action_40 _ = happyReduce_98

action_41 (41) = happyShift action_42
action_41 _ = happyFail

action_42 _ = happyReduce_85

action_43 (41) = happyShift action_56
action_43 _ = happyFail

action_44 (40) = happyShift action_23
action_44 (42) = happyShift action_24
action_44 _ = happyReduce_100

action_45 (40) = happyShift action_23
action_45 (42) = happyShift action_24
action_45 (55) = happyShift action_55
action_45 _ = happyFail

action_46 _ = happyReduce_108

action_47 (40) = happyShift action_23
action_47 (42) = happyShift action_24
action_47 (128) = happyShift action_54
action_47 _ = happyFail

action_48 (41) = happyShift action_53
action_48 _ = happyFail

action_49 (43) = happyShift action_52
action_49 _ = happyReduce_107

action_50 (128) = happyShift action_51
action_50 _ = happyFail

action_51 (54) = happyShift action_59
action_51 _ = happyFail

action_52 (47) = happyShift action_12
action_52 (53) = happyShift action_13
action_52 (65) = happyShift action_14
action_52 (71) = happyShift action_15
action_52 (81) = happyShift action_16
action_52 (82) = happyShift action_17
action_52 (117) = happyShift action_18
action_52 (123) = happyShift action_19
action_52 (128) = happyShift action_20
action_52 (16) = happyGoto action_58
action_52 (20) = happyGoto action_47
action_52 _ = happyFail

action_53 (123) = happyShift action_57
action_53 _ = happyFail

action_54 _ = happyReduce_76

action_55 _ = happyReduce_89

action_56 _ = happyReduce_3

action_57 (50) = happyShift action_63
action_57 (60) = happyShift action_64
action_57 (61) = happyShift action_65
action_57 (62) = happyShift action_66
action_57 (93) = happyShift action_67
action_57 (103) = happyShift action_68
action_57 (105) = happyShift action_69
action_57 (128) = happyShift action_70
action_57 (6) = happyGoto action_60
action_57 (35) = happyGoto action_61
action_57 (36) = happyGoto action_62
action_57 _ = happyReduce_115

action_58 _ = happyReduce_109

action_59 _ = happyReduce_5

action_60 _ = happyReduce_116

action_61 (125) = happyShift action_89
action_61 _ = happyFail

action_62 (50) = happyShift action_63
action_62 (60) = happyShift action_64
action_62 (61) = happyShift action_65
action_62 (62) = happyShift action_66
action_62 (93) = happyShift action_67
action_62 (103) = happyShift action_68
action_62 (105) = happyShift action_69
action_62 (128) = happyShift action_70
action_62 (6) = happyGoto action_88
action_62 _ = happyReduce_114

action_63 _ = happyReduce_15

action_64 (68) = happyShift action_83
action_64 (80) = happyShift action_84
action_64 (107) = happyShift action_85
action_64 (128) = happyShift action_86
action_64 (131) = happyShift action_87
action_64 (11) = happyGoto action_81
action_64 (15) = happyGoto action_82
action_64 _ = happyReduce_75

action_65 (128) = happyShift action_80
action_65 _ = happyFail

action_66 (47) = happyShift action_12
action_66 (53) = happyShift action_13
action_66 (65) = happyShift action_14
action_66 (71) = happyShift action_15
action_66 (81) = happyShift action_16
action_66 (82) = happyShift action_17
action_66 (117) = happyShift action_18
action_66 (123) = happyShift action_19
action_66 (128) = happyShift action_20
action_66 (16) = happyGoto action_79
action_66 (20) = happyGoto action_47
action_66 _ = happyFail

action_67 (47) = happyShift action_12
action_67 (53) = happyShift action_13
action_67 (65) = happyShift action_14
action_67 (71) = happyShift action_15
action_67 (81) = happyShift action_16
action_67 (82) = happyShift action_17
action_67 (117) = happyShift action_18
action_67 (123) = happyShift action_19
action_67 (128) = happyShift action_20
action_67 (10) = happyGoto action_78
action_67 (16) = happyGoto action_74
action_67 (17) = happyGoto action_75
action_67 (20) = happyGoto action_76
action_67 _ = happyFail

action_68 (47) = happyShift action_12
action_68 (53) = happyShift action_13
action_68 (65) = happyShift action_14
action_68 (71) = happyShift action_15
action_68 (81) = happyShift action_16
action_68 (82) = happyShift action_17
action_68 (117) = happyShift action_18
action_68 (123) = happyShift action_19
action_68 (128) = happyShift action_20
action_68 (10) = happyGoto action_77
action_68 (16) = happyGoto action_74
action_68 (17) = happyGoto action_75
action_68 (20) = happyGoto action_76
action_68 _ = happyFail

action_69 (47) = happyShift action_12
action_69 (53) = happyShift action_13
action_69 (65) = happyShift action_14
action_69 (71) = happyShift action_15
action_69 (81) = happyShift action_16
action_69 (82) = happyShift action_17
action_69 (117) = happyShift action_18
action_69 (123) = happyShift action_19
action_69 (128) = happyShift action_20
action_69 (10) = happyGoto action_73
action_69 (16) = happyGoto action_74
action_69 (17) = happyGoto action_75
action_69 (20) = happyGoto action_76
action_69 _ = happyFail

action_70 (48) = happyShift action_71
action_70 (51) = happyShift action_72
action_70 _ = happyFail

action_71 _ = happyReduce_11

action_72 (47) = happyShift action_12
action_72 (53) = happyShift action_13
action_72 (56) = happyShift action_100
action_72 (57) = happyShift action_101
action_72 (58) = happyShift action_102
action_72 (59) = happyShift action_103
action_72 (62) = happyShift action_104
action_72 (65) = happyShift action_14
action_72 (67) = happyShift action_105
action_72 (69) = happyShift action_106
action_72 (70) = happyShift action_107
action_72 (71) = happyShift action_15
action_72 (72) = happyShift action_108
action_72 (73) = happyShift action_109
action_72 (74) = happyShift action_110
action_72 (75) = happyShift action_111
action_72 (76) = happyShift action_112
action_72 (77) = happyShift action_113
action_72 (78) = happyShift action_114
action_72 (79) = happyShift action_115
action_72 (81) = happyShift action_16
action_72 (82) = happyShift action_17
action_72 (83) = happyShift action_116
action_72 (84) = happyShift action_117
action_72 (85) = happyShift action_118
action_72 (86) = happyShift action_119
action_72 (92) = happyShift action_120
action_72 (94) = happyShift action_121
action_72 (95) = happyShift action_122
action_72 (98) = happyShift action_123
action_72 (99) = happyShift action_124
action_72 (102) = happyShift action_125
action_72 (104) = happyShift action_126
action_72 (108) = happyShift action_127
action_72 (110) = happyShift action_128
action_72 (113) = happyShift action_129
action_72 (116) = happyShift action_130
action_72 (117) = happyShift action_18
action_72 (121) = happyShift action_131
action_72 (122) = happyShift action_132
action_72 (123) = happyShift action_19
action_72 (128) = happyShift action_20
action_72 (7) = happyGoto action_96
action_72 (8) = happyGoto action_97
action_72 (9) = happyGoto action_98
action_72 (10) = happyGoto action_99
action_72 (16) = happyGoto action_74
action_72 (17) = happyGoto action_75
action_72 (20) = happyGoto action_76
action_72 _ = happyFail

action_73 (46) = happyShift action_95
action_73 _ = happyFail

action_74 _ = happyReduce_53

action_75 _ = happyReduce_52

action_76 (40) = happyShift action_23
action_76 (42) = happyShift action_24
action_76 (68) = happyShift action_83
action_76 (80) = happyShift action_84
action_76 (107) = happyShift action_85
action_76 (128) = happyShift action_54
action_76 (131) = happyShift action_87
action_76 (15) = happyGoto action_94
action_76 _ = happyReduce_75

action_77 (43) = happyShift action_93
action_77 _ = happyFail

action_78 _ = happyReduce_10

action_79 (40) = happyShift action_92
action_79 _ = happyFail

action_80 _ = happyReduce_13

action_81 (46) = happyShift action_91
action_81 _ = happyFail

action_82 _ = happyReduce_54

action_83 _ = happyReduce_72

action_84 (131) = happyShift action_90
action_84 _ = happyFail

action_85 _ = happyReduce_73

action_86 _ = happyReduce_55

action_87 _ = happyReduce_71

action_88 _ = happyReduce_117

action_89 _ = happyReduce_2

action_90 (120) = happyShift action_161
action_90 _ = happyFail

action_91 (128) = happyShift action_160
action_91 _ = happyFail

action_92 (47) = happyShift action_12
action_92 (53) = happyShift action_13
action_92 (65) = happyShift action_14
action_92 (71) = happyShift action_15
action_92 (81) = happyShift action_16
action_92 (82) = happyShift action_17
action_92 (117) = happyShift action_18
action_92 (123) = happyShift action_19
action_92 (128) = happyShift action_20
action_92 (10) = happyGoto action_157
action_92 (16) = happyGoto action_74
action_92 (17) = happyGoto action_75
action_92 (20) = happyGoto action_76
action_92 (29) = happyGoto action_158
action_92 (30) = happyGoto action_159
action_92 _ = happyFail

action_93 (47) = happyShift action_12
action_93 (53) = happyShift action_13
action_93 (65) = happyShift action_14
action_93 (71) = happyShift action_15
action_93 (81) = happyShift action_16
action_93 (82) = happyShift action_17
action_93 (117) = happyShift action_18
action_93 (123) = happyShift action_19
action_93 (128) = happyShift action_20
action_93 (16) = happyGoto action_156
action_93 (20) = happyGoto action_47
action_93 _ = happyReduce_14

action_94 _ = happyReduce_77

action_95 (128) = happyShift action_155
action_95 _ = happyFail

action_96 _ = happyReduce_6

action_97 (47) = happyShift action_12
action_97 (53) = happyShift action_13
action_97 (65) = happyShift action_14
action_97 (71) = happyShift action_15
action_97 (81) = happyShift action_16
action_97 (82) = happyShift action_17
action_97 (117) = happyShift action_18
action_97 (123) = happyShift action_19
action_97 (128) = happyShift action_20
action_97 (16) = happyGoto action_154
action_97 (20) = happyGoto action_47
action_97 _ = happyFail

action_98 (47) = happyShift action_12
action_98 (53) = happyShift action_13
action_98 (65) = happyShift action_14
action_98 (71) = happyShift action_15
action_98 (81) = happyShift action_16
action_98 (82) = happyShift action_17
action_98 (117) = happyShift action_18
action_98 (123) = happyShift action_19
action_98 (128) = happyShift action_20
action_98 (20) = happyGoto action_153
action_98 _ = happyFail

action_99 _ = happyReduce_20

action_100 _ = happyReduce_35

action_101 (47) = happyShift action_12
action_101 (53) = happyShift action_13
action_101 (65) = happyShift action_14
action_101 (71) = happyShift action_15
action_101 (81) = happyShift action_16
action_101 (82) = happyShift action_17
action_101 (117) = happyShift action_18
action_101 (123) = happyShift action_19
action_101 (128) = happyShift action_20
action_101 (20) = happyGoto action_152
action_101 _ = happyFail

action_102 _ = happyReduce_49

action_103 _ = happyReduce_23

action_104 (47) = happyShift action_12
action_104 (53) = happyShift action_13
action_104 (65) = happyShift action_14
action_104 (71) = happyShift action_15
action_104 (81) = happyShift action_16
action_104 (82) = happyShift action_17
action_104 (117) = happyShift action_18
action_104 (123) = happyShift action_19
action_104 (128) = happyShift action_20
action_104 (16) = happyGoto action_151
action_104 (20) = happyGoto action_47
action_104 _ = happyFail

action_105 _ = happyReduce_36

action_106 (88) = happyShift action_147
action_106 (89) = happyShift action_148
action_106 (90) = happyShift action_149
action_106 (91) = happyShift action_150
action_106 (13) = happyGoto action_146
action_106 _ = happyFail

action_107 _ = happyReduce_43

action_108 _ = happyReduce_40

action_109 _ = happyReduce_32

action_110 _ = happyReduce_26

action_111 _ = happyReduce_27

action_112 _ = happyReduce_31

action_113 _ = happyReduce_46

action_114 _ = happyReduce_38

action_115 (47) = happyShift action_12
action_115 (53) = happyShift action_13
action_115 (65) = happyShift action_14
action_115 (71) = happyShift action_15
action_115 (81) = happyShift action_16
action_115 (82) = happyShift action_17
action_115 (117) = happyShift action_18
action_115 (123) = happyShift action_19
action_115 (128) = happyShift action_20
action_115 (16) = happyGoto action_145
action_115 (20) = happyGoto action_47
action_115 _ = happyFail

action_116 (66) = happyShift action_135
action_116 (87) = happyShift action_136
action_116 (96) = happyShift action_137
action_116 (97) = happyShift action_138
action_116 (100) = happyShift action_139
action_116 (101) = happyShift action_140
action_116 (111) = happyShift action_141
action_116 (112) = happyShift action_142
action_116 (114) = happyShift action_143
action_116 (115) = happyShift action_144
action_116 (12) = happyGoto action_134
action_116 _ = happyFail

action_117 (47) = happyShift action_12
action_117 (53) = happyShift action_13
action_117 (65) = happyShift action_14
action_117 (71) = happyShift action_15
action_117 (81) = happyShift action_16
action_117 (82) = happyShift action_17
action_117 (117) = happyShift action_18
action_117 (123) = happyShift action_19
action_117 (128) = happyShift action_20
action_117 (16) = happyGoto action_133
action_117 (20) = happyGoto action_47
action_117 _ = happyFail

action_118 _ = happyReduce_48

action_119 _ = happyReduce_39

action_120 _ = happyReduce_50

action_121 _ = happyReduce_42

action_122 _ = happyReduce_30

action_123 _ = happyReduce_47

action_124 _ = happyReduce_24

action_125 _ = happyReduce_45

action_126 _ = happyReduce_37

action_127 _ = happyReduce_28

action_128 _ = happyReduce_41

action_129 _ = happyReduce_25

action_130 _ = happyReduce_44

action_131 _ = happyReduce_51

action_132 _ = happyReduce_29

action_133 _ = happyReduce_19

action_134 _ = happyReduce_33

action_135 _ = happyReduce_56

action_136 _ = happyReduce_57

action_137 _ = happyReduce_61

action_138 _ = happyReduce_59

action_139 _ = happyReduce_65

action_140 _ = happyReduce_63

action_141 _ = happyReduce_60

action_142 _ = happyReduce_58

action_143 _ = happyReduce_64

action_144 _ = happyReduce_62

action_145 (44) = happyShift action_170
action_145 _ = happyFail

action_146 _ = happyReduce_34

action_147 _ = happyReduce_67

action_148 _ = happyReduce_66

action_149 _ = happyReduce_69

action_150 _ = happyReduce_68

action_151 (40) = happyShift action_169
action_151 _ = happyFail

action_152 (40) = happyShift action_23
action_152 (42) = happyShift action_24
action_152 _ = happyReduce_18

action_153 (40) = happyShift action_23
action_153 (42) = happyShift action_24
action_153 (68) = happyShift action_83
action_153 (80) = happyShift action_84
action_153 (107) = happyShift action_85
action_153 (128) = happyShift action_86
action_153 (131) = happyShift action_87
action_153 (11) = happyGoto action_168
action_153 (15) = happyGoto action_82
action_153 _ = happyReduce_75

action_154 (106) = happyShift action_167
action_154 _ = happyFail

action_155 (53) = happyShift action_166
action_155 _ = happyFail

action_156 _ = happyReduce_7

action_157 _ = happyReduce_105

action_158 (41) = happyShift action_165
action_158 _ = happyFail

action_159 (43) = happyShift action_164
action_159 _ = happyReduce_104

action_160 (46) = happyShift action_163
action_160 _ = happyFail

action_161 (128) = happyShift action_162
action_161 _ = happyFail

action_162 (45) = happyShift action_182
action_162 _ = happyFail

action_163 (128) = happyShift action_181
action_163 _ = happyFail

action_164 (47) = happyShift action_12
action_164 (53) = happyShift action_13
action_164 (65) = happyShift action_14
action_164 (71) = happyShift action_15
action_164 (81) = happyShift action_16
action_164 (82) = happyShift action_17
action_164 (117) = happyShift action_18
action_164 (123) = happyShift action_19
action_164 (128) = happyShift action_20
action_164 (10) = happyGoto action_180
action_164 (16) = happyGoto action_74
action_164 (17) = happyGoto action_75
action_164 (20) = happyGoto action_76
action_164 _ = happyFail

action_165 _ = happyReduce_8

action_166 (47) = happyShift action_12
action_166 (53) = happyShift action_13
action_166 (65) = happyShift action_14
action_166 (71) = happyShift action_15
action_166 (81) = happyShift action_16
action_166 (82) = happyShift action_17
action_166 (117) = happyShift action_18
action_166 (123) = happyShift action_19
action_166 (128) = happyShift action_20
action_166 (14) = happyGoto action_175
action_166 (17) = happyGoto action_176
action_166 (20) = happyGoto action_177
action_166 (33) = happyGoto action_178
action_166 (34) = happyGoto action_179
action_166 _ = happyReduce_111

action_167 (47) = happyShift action_12
action_167 (53) = happyShift action_13
action_167 (65) = happyShift action_14
action_167 (71) = happyShift action_15
action_167 (81) = happyShift action_16
action_167 (82) = happyShift action_17
action_167 (117) = happyShift action_18
action_167 (123) = happyShift action_19
action_167 (128) = happyShift action_20
action_167 (20) = happyGoto action_174
action_167 _ = happyFail

action_168 (43) = happyShift action_173
action_168 _ = happyFail

action_169 (47) = happyShift action_12
action_169 (53) = happyShift action_13
action_169 (65) = happyShift action_14
action_169 (71) = happyShift action_15
action_169 (81) = happyShift action_16
action_169 (82) = happyShift action_17
action_169 (117) = happyShift action_18
action_169 (123) = happyShift action_19
action_169 (128) = happyShift action_20
action_169 (10) = happyGoto action_157
action_169 (16) = happyGoto action_74
action_169 (17) = happyGoto action_75
action_169 (20) = happyGoto action_76
action_169 (29) = happyGoto action_172
action_169 (30) = happyGoto action_159
action_169 _ = happyFail

action_170 (47) = happyShift action_12
action_170 (53) = happyShift action_13
action_170 (65) = happyShift action_14
action_170 (71) = happyShift action_15
action_170 (81) = happyShift action_16
action_170 (82) = happyShift action_17
action_170 (117) = happyShift action_18
action_170 (123) = happyShift action_19
action_170 (128) = happyShift action_20
action_170 (10) = happyGoto action_171
action_170 (16) = happyGoto action_74
action_170 (17) = happyGoto action_75
action_170 (20) = happyGoto action_76
action_170 _ = happyFail

action_171 _ = happyReduce_22

action_172 (41) = happyShift action_187
action_172 _ = happyFail

action_173 (68) = happyShift action_83
action_173 (80) = happyShift action_84
action_173 (107) = happyShift action_85
action_173 (128) = happyShift action_86
action_173 (131) = happyShift action_87
action_173 (11) = happyGoto action_186
action_173 (15) = happyGoto action_82
action_173 _ = happyReduce_75

action_174 (40) = happyShift action_23
action_174 (42) = happyShift action_24
action_174 _ = happyReduce_17

action_175 _ = happyReduce_112

action_176 (46) = happyShift action_185
action_176 _ = happyFail

action_177 (40) = happyShift action_23
action_177 (42) = happyShift action_24
action_177 (68) = happyShift action_83
action_177 (80) = happyShift action_84
action_177 (107) = happyShift action_85
action_177 (131) = happyShift action_87
action_177 (15) = happyGoto action_94
action_177 _ = happyReduce_75

action_178 (55) = happyShift action_184
action_178 _ = happyFail

action_179 (47) = happyShift action_12
action_179 (53) = happyShift action_13
action_179 (65) = happyShift action_14
action_179 (71) = happyShift action_15
action_179 (81) = happyShift action_16
action_179 (82) = happyShift action_17
action_179 (117) = happyShift action_18
action_179 (123) = happyShift action_19
action_179 (128) = happyShift action_20
action_179 (14) = happyGoto action_183
action_179 (17) = happyGoto action_176
action_179 (20) = happyGoto action_177
action_179 _ = happyReduce_110

action_180 _ = happyReduce_106

action_181 _ = happyReduce_12

action_182 _ = happyReduce_74

action_183 _ = happyReduce_113

action_184 _ = happyReduce_9

action_185 (128) = happyShift action_188
action_185 _ = happyFail

action_186 _ = happyReduce_21

action_187 _ = happyReduce_16

action_188 _ = happyReduce_70

happyReduce_1 = happySpecReduce_1  4 happyReduction_1
happyReduction_1 (HappyAbsSyn37  happy_var_1)
	 =  HappyAbsSyn4
		 (Module  happy_var_1
	)
happyReduction_1 _  = notHappyAtAll 

happyReduce_2 = happyReduce 9 5 happyReduction_2
happyReduction_2 (_ `HappyStk`
	(HappyAbsSyn35  happy_var_8) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn31  happy_var_5) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_3) `HappyStk`
	(HappyAbsSyn20  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn5
		 (Define   happy_var_2 (unTLident happy_var_3)  happy_var_5   happy_var_8
	) `HappyStk` happyRest

happyReduce_3 = happyReduce 6 5 happyReduction_3
happyReduction_3 (_ `HappyStk`
	(HappyAbsSyn25  happy_var_5) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_3) `HappyStk`
	(HappyAbsSyn20  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn5
		 (Declare   happy_var_2 (unTLident happy_var_3)  happy_var_5
	) `HappyStk` happyRest

happyReduce_4 = happyReduce 4 5 happyReduction_4
happyReduction_4 ((HappyAbsSyn20  happy_var_4) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn5
		 (TypeD  (unTLident happy_var_1)   happy_var_4
	) `HappyStk` happyRest

happyReduce_5 = happyReduce 7 5 happyReduction_5
happyReduction_5 (_ `HappyStk`
	(HappyTerminal happy_var_6) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn5
		 (StringD  (unTLident happy_var_1)  (unTNumber happy_var_3)     (unTLident happy_var_6)
	) `HappyStk` happyRest

happyReduce_6 = happySpecReduce_3  6 happyReduction_6
happyReduction_6 (HappyAbsSyn7  happy_var_3)
	_
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn6
		 (LetS  (unTLident happy_var_1)  happy_var_3
	)
happyReduction_6 _ _ _  = notHappyAtAll 

happyReduce_7 = happyReduce 4 6 happyReduction_7
happyReduction_7 ((HappyAbsSyn16  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn10  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn6
		 (StoreS   happy_var_2   happy_var_4
	) `HappyStk` happyRest

happyReduce_8 = happyReduce 5 6 happyReduction_8
happyReduction_8 (_ `HappyStk`
	(HappyAbsSyn29  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn16  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn6
		 (CallS   happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_9 = happyReduce 7 6 happyReduction_9
happyReduction_9 (_ `HappyStk`
	(HappyAbsSyn33  happy_var_6) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn10  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn6
		 (SwitchS   happy_var_2    (unTLident happy_var_4)  happy_var_6
	) `HappyStk` happyRest

happyReduce_10 = happySpecReduce_2  6 happyReduction_10
happyReduction_10 (HappyAbsSyn10  happy_var_2)
	_
	 =  HappyAbsSyn6
		 (ReturnS   happy_var_2
	)
happyReduction_10 _ _  = notHappyAtAll 

happyReduce_11 = happySpecReduce_2  6 happyReduction_11
happyReduction_11 _
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn6
		 (LabelS  (unTLident happy_var_1)
	)
happyReduction_11 _ _  = notHappyAtAll 

happyReduce_12 = happyReduce 6 6 happyReduction_12
happyReduction_12 ((HappyTerminal happy_var_6) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn11  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn6
		 (BrS   happy_var_2    (unTLident happy_var_4)    (unTLident happy_var_6)
	) `HappyStk` happyRest

happyReduce_13 = happySpecReduce_2  6 happyReduction_13
happyReduction_13 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn6
		 (Br0S    (unTLident happy_var_2)
	)
happyReduction_13 _ _  = notHappyAtAll 

happyReduce_14 = happySpecReduce_3  6 happyReduction_14
happyReduction_14 _
	(HappyAbsSyn10  happy_var_2)
	_
	 =  HappyAbsSyn6
		 (TagS   happy_var_2
	)
happyReduction_14 _ _ _  = notHappyAtAll 

happyReduce_15 = happySpecReduce_1  6 happyReduction_15
happyReduction_15 _
	 =  HappyAbsSyn6
		 (NoOpS
	)

happyReduce_16 = happyReduce 5 7 happyReduction_16
happyReduction_16 (_ `HappyStk`
	(HappyAbsSyn29  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn16  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (CallE   happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_17 = happyReduce 4 7 happyReduction_17
happyReduction_17 ((HappyAbsSyn20  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn16  happy_var_2) `HappyStk`
	(HappyAbsSyn8  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (CastE  happy_var_1 happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_18 = happySpecReduce_2  7 happyReduction_18
happyReduction_18 (HappyAbsSyn20  happy_var_2)
	_
	 =  HappyAbsSyn7
		 (AllocaE   happy_var_2
	)
happyReduction_18 _ _  = notHappyAtAll 

happyReduce_19 = happySpecReduce_2  7 happyReduction_19
happyReduction_19 (HappyAbsSyn16  happy_var_2)
	_
	 =  HappyAbsSyn7
		 (LoadE   happy_var_2
	)
happyReduction_19 _ _  = notHappyAtAll 

happyReduce_20 = happySpecReduce_1  7 happyReduction_20
happyReduction_20 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn7
		 (AtomE  happy_var_1
	)
happyReduction_20 _  = notHappyAtAll 

happyReduce_21 = happyReduce 5 7 happyReduction_21
happyReduction_21 ((HappyAbsSyn11  happy_var_5) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn11  happy_var_3) `HappyStk`
	(HappyAbsSyn20  happy_var_2) `HappyStk`
	(HappyAbsSyn9  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (BinOpE  happy_var_1 happy_var_2 happy_var_3   happy_var_5
	) `HappyStk` happyRest

happyReduce_22 = happyReduce 4 7 happyReduction_22
happyReduction_22 ((HappyAbsSyn10  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn16  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (IdxE   happy_var_2   happy_var_4
	) `HappyStk` happyRest

happyReduce_23 = happySpecReduce_1  8 happyReduction_23
happyReduction_23 _
	 =  HappyAbsSyn8
		 (Bitcast
	)

happyReduce_24 = happySpecReduce_1  8 happyReduction_24
happyReduction_24 _
	 =  HappyAbsSyn8
		 (Sitofp
	)

happyReduce_25 = happySpecReduce_1  8 happyReduction_25
happyReduction_25 _
	 =  HappyAbsSyn8
		 (Uitofp
	)

happyReduce_26 = happySpecReduce_1  8 happyReduction_26
happyReduction_26 _
	 =  HappyAbsSyn8
		 (Fptosi
	)

happyReduce_27 = happySpecReduce_1  8 happyReduction_27
happyReduction_27 _
	 =  HappyAbsSyn8
		 (Fptoui
	)

happyReduce_28 = happySpecReduce_1  8 happyReduction_28
happyReduction_28 _
	 =  HappyAbsSyn8
		 (Trunc
	)

happyReduce_29 = happySpecReduce_1  8 happyReduction_29
happyReduction_29 _
	 =  HappyAbsSyn8
		 (Zext
	)

happyReduce_30 = happySpecReduce_1  8 happyReduction_30
happyReduction_30 _
	 =  HappyAbsSyn8
		 (Sext
	)

happyReduce_31 = happySpecReduce_1  8 happyReduction_31
happyReduction_31 _
	 =  HappyAbsSyn8
		 (Fptrunc
	)

happyReduce_32 = happySpecReduce_1  8 happyReduction_32
happyReduction_32 _
	 =  HappyAbsSyn8
		 (Fpext
	)

happyReduce_33 = happySpecReduce_2  9 happyReduction_33
happyReduction_33 (HappyAbsSyn12  happy_var_2)
	_
	 =  HappyAbsSyn9
		 (Icmp   happy_var_2
	)
happyReduction_33 _ _  = notHappyAtAll 

happyReduce_34 = happySpecReduce_2  9 happyReduction_34
happyReduction_34 (HappyAbsSyn13  happy_var_2)
	_
	 =  HappyAbsSyn9
		 (Fcmp   happy_var_2
	)
happyReduction_34 _ _  = notHappyAtAll 

happyReduce_35 = happySpecReduce_1  9 happyReduction_35
happyReduction_35 _
	 =  HappyAbsSyn9
		 (Add
	)

happyReduce_36 = happySpecReduce_1  9 happyReduction_36
happyReduction_36 _
	 =  HappyAbsSyn9
		 (Fadd
	)

happyReduce_37 = happySpecReduce_1  9 happyReduction_37
happyReduction_37 _
	 =  HappyAbsSyn9
		 (Sub
	)

happyReduce_38 = happySpecReduce_1  9 happyReduction_38
happyReduction_38 _
	 =  HappyAbsSyn9
		 (Fsub
	)

happyReduce_39 = happySpecReduce_1  9 happyReduction_39
happyReduction_39 _
	 =  HappyAbsSyn9
		 (Mul
	)

happyReduce_40 = happySpecReduce_1  9 happyReduction_40
happyReduction_40 _
	 =  HappyAbsSyn9
		 (Fmul
	)

happyReduce_41 = happySpecReduce_1  9 happyReduction_41
happyReduction_41 _
	 =  HappyAbsSyn9
		 (Udiv
	)

happyReduce_42 = happySpecReduce_1  9 happyReduction_42
happyReduction_42 _
	 =  HappyAbsSyn9
		 (Sdiv
	)

happyReduce_43 = happySpecReduce_1  9 happyReduction_43
happyReduction_43 _
	 =  HappyAbsSyn9
		 (Fdiv
	)

happyReduce_44 = happySpecReduce_1  9 happyReduction_44
happyReduction_44 _
	 =  HappyAbsSyn9
		 (Urem
	)

happyReduce_45 = happySpecReduce_1  9 happyReduction_45
happyReduction_45 _
	 =  HappyAbsSyn9
		 (Srem
	)

happyReduce_46 = happySpecReduce_1  9 happyReduction_46
happyReduction_46 _
	 =  HappyAbsSyn9
		 (Frem
	)

happyReduce_47 = happySpecReduce_1  9 happyReduction_47
happyReduction_47 _
	 =  HappyAbsSyn9
		 (Shl
	)

happyReduce_48 = happySpecReduce_1  9 happyReduction_48
happyReduction_48 _
	 =  HappyAbsSyn9
		 (Lshr
	)

happyReduce_49 = happySpecReduce_1  9 happyReduction_49
happyReduction_49 _
	 =  HappyAbsSyn9
		 (And
	)

happyReduce_50 = happySpecReduce_1  9 happyReduction_50
happyReduction_50 _
	 =  HappyAbsSyn9
		 (Or
	)

happyReduce_51 = happySpecReduce_1  9 happyReduction_51
happyReduction_51 _
	 =  HappyAbsSyn9
		 (Xor
	)

happyReduce_52 = happySpecReduce_1  10 happyReduction_52
happyReduction_52 (HappyAbsSyn17  happy_var_1)
	 =  HappyAbsSyn10
		 (LitA  happy_var_1
	)
happyReduction_52 _  = notHappyAtAll 

happyReduce_53 = happySpecReduce_1  10 happyReduction_53
happyReduction_53 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn10
		 (VarA  happy_var_1
	)
happyReduction_53 _  = notHappyAtAll 

happyReduce_54 = happySpecReduce_1  11 happyReduction_54
happyReduction_54 (HappyAbsSyn15  happy_var_1)
	 =  HappyAbsSyn11
		 (LitUA  happy_var_1
	)
happyReduction_54 _  = notHappyAtAll 

happyReduce_55 = happySpecReduce_1  11 happyReduction_55
happyReduction_55 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn11
		 (VarUA  (unTLident happy_var_1)
	)
happyReduction_55 _  = notHappyAtAll 

happyReduce_56 = happySpecReduce_1  12 happyReduction_56
happyReduction_56 _
	 =  HappyAbsSyn12
		 (Equ
	)

happyReduce_57 = happySpecReduce_1  12 happyReduction_57
happyReduction_57 _
	 =  HappyAbsSyn12
		 (Neq
	)

happyReduce_58 = happySpecReduce_1  12 happyReduction_58
happyReduction_58 _
	 =  HappyAbsSyn12
		 (Ugt
	)

happyReduce_59 = happySpecReduce_1  12 happyReduction_59
happyReduction_59 _
	 =  HappyAbsSyn12
		 (Sgt
	)

happyReduce_60 = happySpecReduce_1  12 happyReduction_60
happyReduction_60 _
	 =  HappyAbsSyn12
		 (Uge
	)

happyReduce_61 = happySpecReduce_1  12 happyReduction_61
happyReduction_61 _
	 =  HappyAbsSyn12
		 (Sge
	)

happyReduce_62 = happySpecReduce_1  12 happyReduction_62
happyReduction_62 _
	 =  HappyAbsSyn12
		 (Ult
	)

happyReduce_63 = happySpecReduce_1  12 happyReduction_63
happyReduction_63 _
	 =  HappyAbsSyn12
		 (Slt
	)

happyReduce_64 = happySpecReduce_1  12 happyReduction_64
happyReduction_64 _
	 =  HappyAbsSyn12
		 (Ule
	)

happyReduce_65 = happySpecReduce_1  12 happyReduction_65
happyReduction_65 _
	 =  HappyAbsSyn12
		 (Sle
	)

happyReduce_66 = happySpecReduce_1  13 happyReduction_66
happyReduction_66 _
	 =  HappyAbsSyn13
		 (Ogt
	)

happyReduce_67 = happySpecReduce_1  13 happyReduction_67
happyReduction_67 _
	 =  HappyAbsSyn13
		 (Oge
	)

happyReduce_68 = happySpecReduce_1  13 happyReduction_68
happyReduction_68 _
	 =  HappyAbsSyn13
		 (Olt
	)

happyReduce_69 = happySpecReduce_1  13 happyReduction_69
happyReduction_69 _
	 =  HappyAbsSyn13
		 (Ole
	)

happyReduce_70 = happySpecReduce_3  14 happyReduction_70
happyReduction_70 (HappyTerminal happy_var_3)
	_
	(HappyAbsSyn17  happy_var_1)
	 =  HappyAbsSyn14
		 (SwitchAlt  happy_var_1    (unTLident happy_var_3)
	)
happyReduction_70 _ _ _  = notHappyAtAll 

happyReduce_71 = happySpecReduce_1  15 happyReduction_71
happyReduction_71 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (NmbrL  (unTNumber happy_var_1)
	)
happyReduction_71 _  = notHappyAtAll 

happyReduce_72 = happySpecReduce_1  15 happyReduction_72
happyReduction_72 _
	 =  HappyAbsSyn15
		 (FalseL
	)

happyReduce_73 = happySpecReduce_1  15 happyReduction_73
happyReduction_73 _
	 =  HappyAbsSyn15
		 (TrueL
	)

happyReduce_74 = happyReduce 5 15 happyReduction_74
happyReduction_74 (_ `HappyStk`
	(HappyTerminal happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn15
		 (StringL   (unTNumber happy_var_2)  (unTLident happy_var_4)
	) `HappyStk` happyRest

happyReduce_75 = happySpecReduce_0  15 happyReduction_75
happyReduction_75  =  HappyAbsSyn15
		 (VoidL
	)

happyReduce_76 = happySpecReduce_2  16 happyReduction_76
happyReduction_76 (HappyTerminal happy_var_2)
	(HappyAbsSyn20  happy_var_1)
	 =  HappyAbsSyn16
		 (TVar  happy_var_1 (unTLident happy_var_2)
	)
happyReduction_76 _ _  = notHappyAtAll 

happyReduce_77 = happySpecReduce_2  17 happyReduction_77
happyReduction_77 (HappyAbsSyn15  happy_var_2)
	(HappyAbsSyn20  happy_var_1)
	 =  HappyAbsSyn17
		 (TLit  happy_var_1 happy_var_2
	)
happyReduction_77 _ _  = notHappyAtAll 

happyReduce_78 = happySpecReduce_3  18 happyReduction_78
happyReduction_78 (HappyAbsSyn20  happy_var_3)
	_
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn18
		 (FieldT  (unTUident happy_var_1)  happy_var_3
	)
happyReduction_78 _ _ _  = notHappyAtAll 

happyReduce_79 = happySpecReduce_2  19 happyReduction_79
happyReduction_79 (HappyAbsSyn20  happy_var_2)
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn19
		 (ConC  (unTUident happy_var_1) happy_var_2
	)
happyReduction_79 _ _  = notHappyAtAll 

happyReduce_80 = happySpecReduce_2  20 happyReduction_80
happyReduction_80 _
	(HappyAbsSyn20  happy_var_1)
	 =  HappyAbsSyn20
		 (PtrT  happy_var_1
	)
happyReduction_80 _ _  = notHappyAtAll 

happyReduce_81 = happySpecReduce_2  20 happyReduction_81
happyReduction_81 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn20
		 (IntT    (unTNumber happy_var_2)
	)
happyReduction_81 _ _  = notHappyAtAll 

happyReduce_82 = happySpecReduce_1  20 happyReduction_82
happyReduction_82 _
	 =  HappyAbsSyn20
		 (FloatT
	)

happyReduce_83 = happySpecReduce_1  20 happyReduction_83
happyReduction_83 _
	 =  HappyAbsSyn20
		 (DoubleT
	)

happyReduce_84 = happySpecReduce_1  20 happyReduction_84
happyReduction_84 _
	 =  HappyAbsSyn20
		 (VoidT
	)

happyReduce_85 = happyReduce 4 20 happyReduction_85
happyReduction_85 (_ `HappyStk`
	(HappyAbsSyn25  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn20  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn20
		 (FunT  happy_var_1  happy_var_3
	) `HappyStk` happyRest

happyReduce_86 = happySpecReduce_1  20 happyReduction_86
happyReduction_86 _
	 =  HappyAbsSyn20
		 (VarArgsT
	)

happyReduce_87 = happySpecReduce_1  20 happyReduction_87
happyReduction_87 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn20
		 (UserT  (unTLident happy_var_1)
	)
happyReduction_87 _  = notHappyAtAll 

happyReduce_88 = happySpecReduce_3  20 happyReduction_88
happyReduction_88 _
	(HappyAbsSyn25  happy_var_2)
	_
	 =  HappyAbsSyn20
		 (StructT   happy_var_2
	)
happyReduction_88 _ _ _  = notHappyAtAll 

happyReduce_89 = happyReduce 5 20 happyReduction_89
happyReduction_89 (_ `HappyStk`
	(HappyAbsSyn20  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn20
		 (ArrayT   (unTNumber happy_var_2)  happy_var_4
	) `HappyStk` happyRest

happyReduce_90 = happySpecReduce_1  20 happyReduction_90
happyReduction_90 _
	 =  HappyAbsSyn20
		 (CharT
	)

happyReduce_91 = happySpecReduce_1  21 happyReduction_91
happyReduction_91 (HappyAbsSyn22  happy_var_1)
	 =  HappyAbsSyn21
		 (reverse happy_var_1
	)
happyReduction_91 _  = notHappyAtAll 

happyReduce_92 = happySpecReduce_1  22 happyReduction_92
happyReduction_92 (HappyAbsSyn19  happy_var_1)
	 =  HappyAbsSyn22
		 ([happy_var_1]
	)
happyReduction_92 _  = notHappyAtAll 

happyReduce_93 = happySpecReduce_3  22 happyReduction_93
happyReduction_93 (HappyAbsSyn19  happy_var_3)
	_
	(HappyAbsSyn22  happy_var_1)
	 =  HappyAbsSyn22
		 (happy_var_3 : happy_var_1
	)
happyReduction_93 _ _ _  = notHappyAtAll 

happyReduce_94 = happySpecReduce_1  23 happyReduction_94
happyReduction_94 (HappyAbsSyn24  happy_var_1)
	 =  HappyAbsSyn23
		 (reverse happy_var_1
	)
happyReduction_94 _  = notHappyAtAll 

happyReduce_95 = happySpecReduce_1  24 happyReduction_95
happyReduction_95 (HappyAbsSyn18  happy_var_1)
	 =  HappyAbsSyn24
		 ([happy_var_1]
	)
happyReduction_95 _  = notHappyAtAll 

happyReduce_96 = happySpecReduce_3  24 happyReduction_96
happyReduction_96 (HappyAbsSyn18  happy_var_3)
	_
	(HappyAbsSyn24  happy_var_1)
	 =  HappyAbsSyn24
		 (happy_var_3 : happy_var_1
	)
happyReduction_96 _ _ _  = notHappyAtAll 

happyReduce_97 = happySpecReduce_1  25 happyReduction_97
happyReduction_97 (HappyAbsSyn26  happy_var_1)
	 =  HappyAbsSyn25
		 (reverse happy_var_1
	)
happyReduction_97 _  = notHappyAtAll 

happyReduce_98 = happySpecReduce_0  25 happyReduction_98
happyReduction_98  =  HappyAbsSyn25
		 ([]
	)

happyReduce_99 = happySpecReduce_1  26 happyReduction_99
happyReduction_99 (HappyAbsSyn20  happy_var_1)
	 =  HappyAbsSyn26
		 ([happy_var_1]
	)
happyReduction_99 _  = notHappyAtAll 

happyReduce_100 = happySpecReduce_3  26 happyReduction_100
happyReduction_100 (HappyAbsSyn20  happy_var_3)
	_
	(HappyAbsSyn26  happy_var_1)
	 =  HappyAbsSyn26
		 (happy_var_3 : happy_var_1
	)
happyReduction_100 _ _ _  = notHappyAtAll 

happyReduce_101 = happySpecReduce_1  27 happyReduction_101
happyReduction_101 (HappyAbsSyn28  happy_var_1)
	 =  HappyAbsSyn27
		 (reverse happy_var_1
	)
happyReduction_101 _  = notHappyAtAll 

happyReduce_102 = happySpecReduce_1  28 happyReduction_102
happyReduction_102 (HappyAbsSyn7  happy_var_1)
	 =  HappyAbsSyn28
		 ([happy_var_1]
	)
happyReduction_102 _  = notHappyAtAll 

happyReduce_103 = happySpecReduce_3  28 happyReduction_103
happyReduction_103 (HappyAbsSyn7  happy_var_3)
	_
	(HappyAbsSyn28  happy_var_1)
	 =  HappyAbsSyn28
		 (happy_var_3 : happy_var_1
	)
happyReduction_103 _ _ _  = notHappyAtAll 

happyReduce_104 = happySpecReduce_1  29 happyReduction_104
happyReduction_104 (HappyAbsSyn30  happy_var_1)
	 =  HappyAbsSyn29
		 (reverse happy_var_1
	)
happyReduction_104 _  = notHappyAtAll 

happyReduce_105 = happySpecReduce_1  30 happyReduction_105
happyReduction_105 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn30
		 ([happy_var_1]
	)
happyReduction_105 _  = notHappyAtAll 

happyReduce_106 = happySpecReduce_3  30 happyReduction_106
happyReduction_106 (HappyAbsSyn10  happy_var_3)
	_
	(HappyAbsSyn30  happy_var_1)
	 =  HappyAbsSyn30
		 (happy_var_3 : happy_var_1
	)
happyReduction_106 _ _ _  = notHappyAtAll 

happyReduce_107 = happySpecReduce_1  31 happyReduction_107
happyReduction_107 (HappyAbsSyn32  happy_var_1)
	 =  HappyAbsSyn31
		 (reverse happy_var_1
	)
happyReduction_107 _  = notHappyAtAll 

happyReduce_108 = happySpecReduce_1  32 happyReduction_108
happyReduction_108 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn32
		 ([happy_var_1]
	)
happyReduction_108 _  = notHappyAtAll 

happyReduce_109 = happySpecReduce_3  32 happyReduction_109
happyReduction_109 (HappyAbsSyn16  happy_var_3)
	_
	(HappyAbsSyn32  happy_var_1)
	 =  HappyAbsSyn32
		 (happy_var_3 : happy_var_1
	)
happyReduction_109 _ _ _  = notHappyAtAll 

happyReduce_110 = happySpecReduce_1  33 happyReduction_110
happyReduction_110 (HappyAbsSyn34  happy_var_1)
	 =  HappyAbsSyn33
		 (reverse happy_var_1
	)
happyReduction_110 _  = notHappyAtAll 

happyReduce_111 = happySpecReduce_0  33 happyReduction_111
happyReduction_111  =  HappyAbsSyn33
		 ([]
	)

happyReduce_112 = happySpecReduce_1  34 happyReduction_112
happyReduction_112 (HappyAbsSyn14  happy_var_1)
	 =  HappyAbsSyn34
		 ([happy_var_1]
	)
happyReduction_112 _  = notHappyAtAll 

happyReduce_113 = happySpecReduce_2  34 happyReduction_113
happyReduction_113 (HappyAbsSyn14  happy_var_2)
	(HappyAbsSyn34  happy_var_1)
	 =  HappyAbsSyn34
		 (happy_var_2 : happy_var_1
	)
happyReduction_113 _ _  = notHappyAtAll 

happyReduce_114 = happySpecReduce_1  35 happyReduction_114
happyReduction_114 (HappyAbsSyn36  happy_var_1)
	 =  HappyAbsSyn35
		 (reverse happy_var_1
	)
happyReduction_114 _  = notHappyAtAll 

happyReduce_115 = happySpecReduce_0  35 happyReduction_115
happyReduction_115  =  HappyAbsSyn35
		 ([]
	)

happyReduce_116 = happySpecReduce_1  36 happyReduction_116
happyReduction_116 (HappyAbsSyn6  happy_var_1)
	 =  HappyAbsSyn36
		 ([happy_var_1]
	)
happyReduction_116 _  = notHappyAtAll 

happyReduce_117 = happySpecReduce_2  36 happyReduction_117
happyReduction_117 (HappyAbsSyn6  happy_var_2)
	(HappyAbsSyn36  happy_var_1)
	 =  HappyAbsSyn36
		 (happy_var_2 : happy_var_1
	)
happyReduction_117 _ _  = notHappyAtAll 

happyReduce_118 = happySpecReduce_1  37 happyReduction_118
happyReduction_118 (HappyAbsSyn38  happy_var_1)
	 =  HappyAbsSyn37
		 (reverse happy_var_1
	)
happyReduction_118 _  = notHappyAtAll 

happyReduce_119 = happySpecReduce_0  37 happyReduction_119
happyReduction_119  =  HappyAbsSyn37
		 ([]
	)

happyReduce_120 = happySpecReduce_1  38 happyReduction_120
happyReduction_120 (HappyAbsSyn5  happy_var_1)
	 =  HappyAbsSyn38
		 ([happy_var_1]
	)
happyReduction_120 _  = notHappyAtAll 

happyReduce_121 = happySpecReduce_2  38 happyReduction_121
happyReduction_121 (HappyAbsSyn5  happy_var_2)
	(HappyAbsSyn38  happy_var_1)
	 =  HappyAbsSyn38
		 (happy_var_2 : happy_var_1
	)
happyReduction_121 _ _  = notHappyAtAll 

happyNewToken action sts stk [] =
	action 132 132 notHappyAtAll (HappyState action) sts stk []

happyNewToken action sts stk (tk:tks) =
	let cont i = action i i tk (HappyState action) sts stk tks in
	case tk of {
	TSymbol _ "\"" -> cont 39;
	TSymbol _ "(" -> cont 40;
	TSymbol _ ")" -> cont 41;
	TSymbol _ "*" -> cont 42;
	TSymbol _ "," -> cont 43;
	TSymbol _ ", i32 0," -> cont 44;
	TSymbol _ ", i32 0, i32 0)" -> cont 45;
	TSymbol _ ", label %" -> cont 46;
	TSymbol _ "..." -> cont 47;
	TSymbol _ ":" -> cont 48;
	TSymbol _ "::" -> cont 49;
	TSymbol _ ";" -> cont 50;
	TSymbol _ "=" -> cont 51;
	TSymbol _ "= private constant [" -> cont 52;
	TSymbol _ "[" -> cont 53;
	TSymbol _ "\\00\"" -> cont 54;
	TSymbol _ "]" -> cont 55;
	TSymbol _ "add nuw nsw" -> cont 56;
	TSymbol _ "alloca" -> cont 57;
	TSymbol _ "and" -> cont 58;
	TSymbol _ "bitcast" -> cont 59;
	TSymbol _ "br i1" -> cont 60;
	TSymbol _ "br label %" -> cont 61;
	TSymbol _ "call" -> cont 62;
	TSymbol _ "declare" -> cont 63;
	TSymbol _ "define" -> cont 64;
	TSymbol _ "double" -> cont 65;
	TSymbol _ "eq" -> cont 66;
	TSymbol _ "fadd" -> cont 67;
	TSymbol _ "false" -> cont 68;
	TSymbol _ "fcmp" -> cont 69;
	TSymbol _ "fdiv" -> cont 70;
	TSymbol _ "float" -> cont 71;
	TSymbol _ "fmul" -> cont 72;
	TSymbol _ "fpext" -> cont 73;
	TSymbol _ "fptosi" -> cont 74;
	TSymbol _ "fptoui" -> cont 75;
	TSymbol _ "fptrunc" -> cont 76;
	TSymbol _ "frem" -> cont 77;
	TSymbol _ "fsub" -> cont 78;
	TSymbol _ "getelementptr inbounds" -> cont 79;
	TSymbol _ "getelementptr inbounds ([" -> cont 80;
	TSymbol _ "i" -> cont 81;
	TSymbol _ "i8" -> cont 82;
	TSymbol _ "icmp" -> cont 83;
	TSymbol _ "load" -> cont 84;
	TSymbol _ "lshr" -> cont 85;
	TSymbol _ "mul nuw nsw" -> cont 86;
	TSymbol _ "ne" -> cont 87;
	TSymbol _ "oge" -> cont 88;
	TSymbol _ "ogt" -> cont 89;
	TSymbol _ "ole" -> cont 90;
	TSymbol _ "olt" -> cont 91;
	TSymbol _ "or" -> cont 92;
	TSymbol _ "ret" -> cont 93;
	TSymbol _ "sdiv" -> cont 94;
	TSymbol _ "sext" -> cont 95;
	TSymbol _ "sge" -> cont 96;
	TSymbol _ "sgt" -> cont 97;
	TSymbol _ "shl" -> cont 98;
	TSymbol _ "sitofp" -> cont 99;
	TSymbol _ "sle" -> cont 100;
	TSymbol _ "slt" -> cont 101;
	TSymbol _ "srem" -> cont 102;
	TSymbol _ "store" -> cont 103;
	TSymbol _ "sub nuw nsw" -> cont 104;
	TSymbol _ "switch" -> cont 105;
	TSymbol _ "to" -> cont 106;
	TSymbol _ "true" -> cont 107;
	TSymbol _ "trunc" -> cont 108;
	TSymbol _ "type" -> cont 109;
	TSymbol _ "udiv" -> cont 110;
	TSymbol _ "uge" -> cont 111;
	TSymbol _ "ugt" -> cont 112;
	TSymbol _ "uitofp" -> cont 113;
	TSymbol _ "ule" -> cont 114;
	TSymbol _ "ult" -> cont 115;
	TSymbol _ "urem" -> cont 116;
	TSymbol _ "void" -> cont 117;
	TSymbol _ "x" -> cont 118;
	TSymbol _ "x i8 ] c" -> cont 119;
	TSymbol _ "x i8 ]*" -> cont 120;
	TSymbol _ "xor" -> cont 121;
	TSymbol _ "zext" -> cont 122;
	TSymbol _ "{" -> cont 123;
	TSymbol _ "|" -> cont 124;
	TSymbol _ "}" -> cont 125;
	TUident _ _ -> cont 126;
	TUsym _ _ -> cont 127;
	TLident _ _ -> cont 128;
	TString _ _ -> cont 129;
	TChar _ _ -> cont 130;
	TNumber _ _ -> cont 131;
	_ -> happyError' (tk:tks)
	}

happyError_ tk tks = happyError' (tk:tks)

newtype HappyIdentity a = HappyIdentity a
happyIdentity = HappyIdentity
happyRunIdentity (HappyIdentity a) = a

instance Monad HappyIdentity where
    return = HappyIdentity
    (HappyIdentity p) >>= q = q p

happyThen :: () => HappyIdentity a -> (a -> HappyIdentity b) -> HappyIdentity b
happyThen = (>>=)
happyReturn :: () => a -> HappyIdentity a
happyReturn = (return)
happyThen1 m k tks = (>>=) m (\a -> k a tks)
happyReturn1 :: () => a -> b -> HappyIdentity a
happyReturn1 = \a tks -> (return) a
happyError' :: () => [((Token Point))] -> HappyIdentity a
happyError' = HappyIdentity . happyError

grmParse tks = happyRunIdentity happySomeParser where
  happySomeParser = happyThen (happyParse action_0 tks) (\x -> case x of {HappyAbsSyn4 z -> happyReturn z; _other -> notHappyAtAll })

happySeq = happyDontSeq



{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "<built-in>" #-}
{-# LINE 1 "<command-line>" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
-- Id: GenericTemplate.hs,v 1.26 2005/01/14 14:47:22 simonmar Exp 

{-# LINE 30 "templates/GenericTemplate.hs" #-}








{-# LINE 51 "templates/GenericTemplate.hs" #-}

{-# LINE 61 "templates/GenericTemplate.hs" #-}

{-# LINE 70 "templates/GenericTemplate.hs" #-}

infixr 9 `HappyStk`
data HappyStk a = HappyStk a (HappyStk a)

-----------------------------------------------------------------------------
-- starting the parse

happyParse start_state = happyNewToken start_state notHappyAtAll notHappyAtAll

-----------------------------------------------------------------------------
-- Accepting the parse

-- If the current token is (1), it means we've just accepted a partial
-- parse (a %partial parser).  We must ignore the saved token on the top of
-- the stack in this case.
happyAccept (1) tk st sts (_ `HappyStk` ans `HappyStk` _) =
	happyReturn1 ans
happyAccept j tk st sts (HappyStk ans _) = 
	 (happyReturn1 ans)

-----------------------------------------------------------------------------
-- Arrays only: do the next action

{-# LINE 148 "templates/GenericTemplate.hs" #-}

-----------------------------------------------------------------------------
-- HappyState data type (not arrays)



newtype HappyState b c = HappyState
        (Int ->                    -- token number
         Int ->                    -- token number (yes, again)
         b ->                           -- token semantic value
         HappyState b c ->              -- current state
         [HappyState b c] ->            -- state stack
         c)



-----------------------------------------------------------------------------
-- Shifting a token

happyShift new_state (1) tk st sts stk@(x `HappyStk` _) =
     let (i) = (case x of { HappyErrorToken (i) -> i }) in
--     trace "shifting the error token" $
     new_state i i tk (HappyState (new_state)) ((st):(sts)) (stk)

happyShift new_state i tk st sts stk =
     happyNewToken new_state ((st):(sts)) ((HappyTerminal (tk))`HappyStk`stk)

-- happyReduce is specialised for the common cases.

happySpecReduce_0 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_0 nt fn j tk st@((HappyState (action))) sts stk
     = action nt j tk st ((st):(sts)) (fn `HappyStk` stk)

happySpecReduce_1 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_1 nt fn j tk _ sts@(((st@(HappyState (action))):(_))) (v1`HappyStk`stk')
     = let r = fn v1 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_2 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_2 nt fn j tk _ ((_):(sts@(((st@(HappyState (action))):(_))))) (v1`HappyStk`v2`HappyStk`stk')
     = let r = fn v1 v2 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_3 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_3 nt fn j tk _ ((_):(((_):(sts@(((st@(HappyState (action))):(_))))))) (v1`HappyStk`v2`HappyStk`v3`HappyStk`stk')
     = let r = fn v1 v2 v3 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happyReduce k i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyReduce k nt fn j tk st sts stk
     = case happyDrop (k - ((1) :: Int)) sts of
	 sts1@(((st1@(HappyState (action))):(_))) ->
        	let r = fn stk in  -- it doesn't hurt to always seq here...
       		happyDoSeq r (action nt j tk st1 sts1 r)

happyMonadReduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonadReduce k nt fn j tk st sts stk =
        happyThen1 (fn stk tk) (\r -> action nt j tk st1 sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk

happyMonad2Reduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonad2Reduce k nt fn j tk st sts stk =
       happyThen1 (fn stk tk) (\r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk





             new_state = action


happyDrop (0) l = l
happyDrop n ((_):(t)) = happyDrop (n - ((1) :: Int)) t

happyDropStk (0) l = l
happyDropStk n (x `HappyStk` xs) = happyDropStk (n - ((1)::Int)) xs

-----------------------------------------------------------------------------
-- Moving to a new state after a reduction

{-# LINE 246 "templates/GenericTemplate.hs" #-}
happyGoto action j tk st = action j j tk (HappyState action)


-----------------------------------------------------------------------------
-- Error recovery ((1) is the error token)

-- parse error if we are in recovery and we fail again
happyFail  (1) tk old_st _ stk =
--	trace "failing" $ 
    	happyError_ tk

{-  We don't need state discarding for our restricted implementation of
    "error".  In fact, it can cause some bogus parses, so I've disabled it
    for now --SDM

-- discard a state
happyFail  (1) tk old_st (((HappyState (action))):(sts)) 
						(saved_tok `HappyStk` _ `HappyStk` stk) =
--	trace ("discarding state, depth " ++ show (length stk))  $
	action (1) (1) tk (HappyState (action)) sts ((saved_tok`HappyStk`stk))
-}

-- Enter error recovery: generate an error token,
--                       save the old token and carry on.
happyFail  i tk (HappyState (action)) sts stk =
--      trace "entering error recovery" $
	action (1) (1) tk (HappyState (action)) sts ( (HappyErrorToken (i)) `HappyStk` stk)

-- Internal happy errors:

notHappyAtAll :: a
notHappyAtAll = error "Internal Happy error\n"

-----------------------------------------------------------------------------
-- Hack to get the typechecker to accept our action functions







-----------------------------------------------------------------------------
-- Seq-ing.  If the --strict flag is given, then Happy emits 
--	happySeq = happyDoSeq
-- otherwise it emits
-- 	happySeq = happyDontSeq

happyDoSeq, happyDontSeq :: a -> b -> b
happyDoSeq   a b = a `seq` b
happyDontSeq a b = b

-----------------------------------------------------------------------------
-- Don't inline any functions from the template.  GHC has a nasty habit
-- of deciding to inline happyGoto everywhere, which increases the size of
-- the generated parser quite a bit.

{-# LINE 311 "templates/GenericTemplate.hs" #-}
{-# NOINLINE happyShift #-}
{-# NOINLINE happySpecReduce_0 #-}
{-# NOINLINE happySpecReduce_1 #-}
{-# NOINLINE happySpecReduce_2 #-}
{-# NOINLINE happySpecReduce_3 #-}
{-# NOINLINE happyReduce #-}
{-# NOINLINE happyMonadReduce #-}
{-# NOINLINE happyGoto #-}
{-# NOINLINE happyFail #-}

-- end of Happy Template.
