{-# OPTIONS_GHC -w #-}
{-# OPTIONS -w #-}
-- Haskell module generated by grm *** DO NOT EDIT ***


module Language.Pds.Par where
import Grm.Prims
import Grm.Lex
import Language.Pds.Abs

-- parser produced by Happy Version 1.18.6

data HappyAbsSyn t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42 t43 t44 t45 t46
	= HappyTerminal ((Token Point))
	| HappyErrorToken Int
	| HappyAbsSyn4 t4
	| HappyAbsSyn5 t5
	| HappyAbsSyn6 t6
	| HappyAbsSyn7 t7
	| HappyAbsSyn8 t8
	| HappyAbsSyn9 t9
	| HappyAbsSyn10 t10
	| HappyAbsSyn11 t11
	| HappyAbsSyn12 t12
	| HappyAbsSyn13 t13
	| HappyAbsSyn14 t14
	| HappyAbsSyn15 t15
	| HappyAbsSyn16 t16
	| HappyAbsSyn17 t17
	| HappyAbsSyn18 t18
	| HappyAbsSyn19 t19
	| HappyAbsSyn20 t20
	| HappyAbsSyn21 t21
	| HappyAbsSyn22 t22
	| HappyAbsSyn23 t23
	| HappyAbsSyn24 t24
	| HappyAbsSyn25 t25
	| HappyAbsSyn26 t26
	| HappyAbsSyn27 t27
	| HappyAbsSyn28 t28
	| HappyAbsSyn29 t29
	| HappyAbsSyn30 t30
	| HappyAbsSyn31 t31
	| HappyAbsSyn32 t32
	| HappyAbsSyn33 t33
	| HappyAbsSyn34 t34
	| HappyAbsSyn35 t35
	| HappyAbsSyn36 t36
	| HappyAbsSyn37 t37
	| HappyAbsSyn38 t38
	| HappyAbsSyn39 t39
	| HappyAbsSyn40 t40
	| HappyAbsSyn41 t41
	| HappyAbsSyn42 t42
	| HappyAbsSyn43 t43
	| HappyAbsSyn44 t44
	| HappyAbsSyn45 t45
	| HappyAbsSyn46 t46

action_0 (64) = happyShift action_2
action_0 (4) = happyGoto action_3
action_0 _ = happyFail

action_1 (64) = happyShift action_2
action_1 _ = happyFail

action_2 (76) = happyShift action_4
action_2 _ = happyFail

action_3 (82) = happyAccept
action_3 _ = happyFail

action_4 (73) = happyShift action_5
action_4 _ = happyFail

action_5 (59) = happyShift action_9
action_5 (5) = happyGoto action_6
action_5 (23) = happyGoto action_7
action_5 (24) = happyGoto action_8
action_5 _ = happyReduce_42

action_6 (52) = happyShift action_17
action_6 _ = happyFail

action_7 (60) = happyShift action_16
action_7 (6) = happyGoto action_13
action_7 (25) = happyGoto action_14
action_7 (26) = happyGoto action_15
action_7 _ = happyReduce_46

action_8 (59) = happyShift action_9
action_8 (5) = happyGoto action_12
action_8 _ = happyReduce_41

action_9 (76) = happyShift action_10
action_9 (78) = happyShift action_11
action_9 _ = happyFail

action_10 _ = happyReduce_2

action_11 _ = happyReduce_3

action_12 (52) = happyShift action_25
action_12 _ = happyFail

action_13 (52) = happyShift action_24
action_13 _ = happyFail

action_14 (71) = happyShift action_23
action_14 (8) = happyGoto action_20
action_14 (29) = happyGoto action_21
action_14 (30) = happyGoto action_22
action_14 _ = happyReduce_54

action_15 (60) = happyShift action_16
action_15 (6) = happyGoto action_19
action_15 _ = happyReduce_45

action_16 (76) = happyShift action_18
action_16 _ = happyFail

action_17 _ = happyReduce_43

action_18 (57) = happyShift action_35
action_18 (7) = happyGoto action_34
action_18 _ = happyReduce_6

action_19 (52) = happyShift action_33
action_19 _ = happyFail

action_20 (52) = happyShift action_32
action_20 _ = happyFail

action_21 (62) = happyShift action_31
action_21 (10) = happyGoto action_28
action_21 (31) = happyGoto action_29
action_21 (32) = happyGoto action_30
action_21 _ = happyReduce_58

action_22 (71) = happyShift action_23
action_22 (8) = happyGoto action_27
action_22 _ = happyReduce_53

action_23 (76) = happyShift action_26
action_23 _ = happyFail

action_24 _ = happyReduce_47

action_25 _ = happyReduce_44

action_26 (78) = happyShift action_48
action_26 (22) = happyGoto action_45
action_26 (41) = happyGoto action_46
action_26 (42) = happyGoto action_47
action_26 _ = happyReduce_75

action_27 (52) = happyShift action_44
action_27 _ = happyFail

action_28 (52) = happyShift action_43
action_28 _ = happyFail

action_29 (78) = happyShift action_42
action_29 (9) = happyGoto action_39
action_29 (27) = happyGoto action_40
action_29 (28) = happyGoto action_41
action_29 _ = happyReduce_50

action_30 (62) = happyShift action_31
action_30 (10) = happyGoto action_38
action_30 _ = happyReduce_57

action_31 (76) = happyShift action_37
action_31 _ = happyFail

action_32 _ = happyReduce_55

action_33 _ = happyReduce_48

action_34 _ = happyReduce_4

action_35 (76) = happyShift action_36
action_35 _ = happyFail

action_36 _ = happyReduce_5

action_37 (47) = happyShift action_59
action_37 (55) = happyShift action_60
action_37 (73) = happyShift action_61
action_37 (78) = happyShift action_62
action_37 (16) = happyGoto action_58
action_37 _ = happyFail

action_38 (52) = happyShift action_57
action_38 _ = happyFail

action_39 (52) = happyShift action_56
action_39 _ = happyFail

action_40 (75) = happyShift action_55
action_40 _ = happyFail

action_41 (78) = happyShift action_42
action_41 (9) = happyGoto action_54
action_41 _ = happyReduce_49

action_42 (53) = happyShift action_52
action_42 (54) = happyShift action_53
action_42 (11) = happyGoto action_51
action_42 _ = happyFail

action_43 _ = happyReduce_59

action_44 _ = happyReduce_56

action_45 _ = happyReduce_76

action_46 (53) = happyShift action_50
action_46 _ = happyFail

action_47 (78) = happyShift action_48
action_47 (22) = happyGoto action_49
action_47 _ = happyReduce_74

action_48 _ = happyReduce_40

action_49 _ = happyReduce_77

action_50 (58) = happyShift action_81
action_50 (65) = happyShift action_82
action_50 (67) = happyShift action_83
action_50 (69) = happyShift action_84
action_50 (70) = happyShift action_85
action_50 (72) = happyShift action_86
action_50 (12) = happyGoto action_80
action_50 _ = happyFail

action_51 (47) = happyShift action_72
action_51 (56) = happyShift action_73
action_51 (63) = happyShift action_74
action_51 (68) = happyShift action_75
action_51 (78) = happyShift action_76
action_51 (79) = happyShift action_77
action_51 (80) = happyShift action_78
action_51 (81) = happyShift action_79
action_51 (13) = happyGoto action_70
action_51 (15) = happyGoto action_71
action_51 _ = happyFail

action_52 _ = happyReduce_11

action_53 _ = happyReduce_10

action_54 (52) = happyShift action_69
action_54 _ = happyFail

action_55 _ = happyReduce_1

action_56 _ = happyReduce_51

action_57 _ = happyReduce_60

action_58 _ = happyReduce_9

action_59 (47) = happyShift action_59
action_59 (55) = happyShift action_60
action_59 (73) = happyShift action_61
action_59 (76) = happyShift action_68
action_59 (78) = happyShift action_62
action_59 (16) = happyGoto action_67
action_59 _ = happyFail

action_60 _ = happyReduce_32

action_61 (76) = happyShift action_66
action_61 (18) = happyGoto action_63
action_61 (45) = happyGoto action_64
action_61 (46) = happyGoto action_65
action_61 _ = happyFail

action_62 _ = happyReduce_34

action_63 _ = happyReduce_83

action_64 (75) = happyShift action_109
action_64 _ = happyFail

action_65 (49) = happyShift action_108
action_65 _ = happyReduce_82

action_66 (78) = happyShift action_48
action_66 (22) = happyGoto action_45
action_66 (41) = happyGoto action_107
action_66 (42) = happyGoto action_47
action_66 _ = happyReduce_75

action_67 (50) = happyShift action_106
action_67 _ = happyFail

action_68 (47) = happyShift action_59
action_68 (55) = happyShift action_60
action_68 (73) = happyShift action_61
action_68 (78) = happyShift action_62
action_68 (16) = happyGoto action_103
action_68 (43) = happyGoto action_104
action_68 (44) = happyGoto action_105
action_68 _ = happyReduce_79

action_69 _ = happyReduce_52

action_70 _ = happyReduce_8

action_71 _ = happyReduce_24

action_72 (47) = happyShift action_72
action_72 (56) = happyShift action_73
action_72 (63) = happyShift action_74
action_72 (68) = happyShift action_75
action_72 (78) = happyShift action_76
action_72 (79) = happyShift action_77
action_72 (80) = happyShift action_78
action_72 (81) = happyShift action_79
action_72 (13) = happyGoto action_102
action_72 (15) = happyGoto action_71
action_72 _ = happyFail

action_73 (78) = happyShift action_101
action_73 _ = happyFail

action_74 (78) = happyShift action_100
action_74 _ = happyFail

action_75 (47) = happyShift action_72
action_75 (56) = happyShift action_73
action_75 (63) = happyShift action_74
action_75 (68) = happyShift action_75
action_75 (78) = happyShift action_76
action_75 (79) = happyShift action_77
action_75 (80) = happyShift action_78
action_75 (81) = happyShift action_79
action_75 (13) = happyGoto action_99
action_75 (15) = happyGoto action_71
action_75 _ = happyFail

action_76 _ = happyReduce_23

action_77 _ = happyReduce_28

action_78 _ = happyReduce_27

action_79 _ = happyReduce_29

action_80 _ = happyReduce_7

action_81 (76) = happyShift action_98
action_81 (20) = happyGoto action_95
action_81 (35) = happyGoto action_96
action_81 (36) = happyGoto action_97
action_81 _ = happyFail

action_82 (76) = happyShift action_94
action_82 _ = happyFail

action_83 (73) = happyShift action_93
action_83 _ = happyFail

action_84 (47) = happyShift action_59
action_84 (55) = happyShift action_60
action_84 (73) = happyShift action_61
action_84 (78) = happyShift action_62
action_84 (16) = happyGoto action_92
action_84 _ = happyFail

action_85 (76) = happyShift action_91
action_85 (19) = happyGoto action_88
action_85 (37) = happyGoto action_89
action_85 (38) = happyGoto action_90
action_85 _ = happyFail

action_86 (76) = happyShift action_87
action_86 _ = happyFail

action_87 _ = happyReduce_17

action_88 _ = happyReduce_69

action_89 _ = happyReduce_13

action_90 (74) = happyShift action_127
action_90 _ = happyReduce_68

action_91 (47) = happyShift action_59
action_91 (55) = happyShift action_60
action_91 (73) = happyShift action_61
action_91 (78) = happyShift action_62
action_91 (16) = happyGoto action_126
action_91 _ = happyFail

action_92 _ = happyReduce_15

action_93 (76) = happyShift action_125
action_93 (21) = happyGoto action_122
action_93 (39) = happyGoto action_123
action_93 (40) = happyGoto action_124
action_93 _ = happyFail

action_94 (47) = happyShift action_59
action_94 (55) = happyShift action_60
action_94 (73) = happyShift action_61
action_94 (78) = happyShift action_62
action_94 (16) = happyGoto action_121
action_94 _ = happyFail

action_95 _ = happyReduce_66

action_96 _ = happyReduce_14

action_97 (74) = happyShift action_120
action_97 _ = happyReduce_65

action_98 _ = happyReduce_38

action_99 (66) = happyShift action_119
action_99 _ = happyFail

action_100 (53) = happyShift action_52
action_100 (54) = happyShift action_53
action_100 (11) = happyGoto action_118
action_100 _ = happyFail

action_101 (50) = happyShift action_117
action_101 _ = happyFail

action_102 (47) = happyShift action_72
action_102 (51) = happyShift action_116
action_102 (56) = happyShift action_73
action_102 (63) = happyShift action_74
action_102 (68) = happyShift action_75
action_102 (78) = happyShift action_76
action_102 (79) = happyShift action_77
action_102 (80) = happyShift action_78
action_102 (81) = happyShift action_79
action_102 (13) = happyGoto action_115
action_102 (15) = happyGoto action_71
action_102 _ = happyFail

action_103 _ = happyReduce_80

action_104 (48) = happyShift action_114
action_104 _ = happyFail

action_105 (47) = happyShift action_59
action_105 (55) = happyShift action_60
action_105 (73) = happyShift action_61
action_105 (78) = happyShift action_62
action_105 (16) = happyGoto action_113
action_105 _ = happyReduce_78

action_106 (47) = happyShift action_59
action_106 (55) = happyShift action_60
action_106 (73) = happyShift action_61
action_106 (78) = happyShift action_62
action_106 (16) = happyGoto action_112
action_106 _ = happyFail

action_107 _ = happyReduce_36

action_108 (76) = happyShift action_66
action_108 (18) = happyGoto action_111
action_108 _ = happyFail

action_109 (54) = happyShift action_110
action_109 _ = happyFail

action_110 (47) = happyShift action_59
action_110 (55) = happyShift action_60
action_110 (73) = happyShift action_61
action_110 (78) = happyShift action_62
action_110 (16) = happyGoto action_140
action_110 _ = happyFail

action_111 _ = happyReduce_84

action_112 (48) = happyShift action_139
action_112 _ = happyFail

action_113 _ = happyReduce_81

action_114 _ = happyReduce_33

action_115 (48) = happyShift action_138
action_115 _ = happyFail

action_116 (47) = happyShift action_59
action_116 (55) = happyShift action_60
action_116 (73) = happyShift action_61
action_116 (78) = happyShift action_62
action_116 (16) = happyGoto action_137
action_116 _ = happyFail

action_117 (47) = happyShift action_72
action_117 (56) = happyShift action_73
action_117 (63) = happyShift action_74
action_117 (68) = happyShift action_75
action_117 (78) = happyShift action_76
action_117 (79) = happyShift action_77
action_117 (80) = happyShift action_78
action_117 (81) = happyShift action_79
action_117 (13) = happyGoto action_136
action_117 (15) = happyGoto action_71
action_117 _ = happyFail

action_118 (47) = happyShift action_72
action_118 (56) = happyShift action_73
action_118 (63) = happyShift action_74
action_118 (68) = happyShift action_75
action_118 (78) = happyShift action_76
action_118 (79) = happyShift action_77
action_118 (80) = happyShift action_78
action_118 (81) = happyShift action_79
action_118 (13) = happyGoto action_135
action_118 (15) = happyGoto action_71
action_118 _ = happyFail

action_119 (47) = happyShift action_72
action_119 (56) = happyShift action_73
action_119 (63) = happyShift action_74
action_119 (68) = happyShift action_75
action_119 (78) = happyShift action_76
action_119 (79) = happyShift action_77
action_119 (80) = happyShift action_78
action_119 (81) = happyShift action_79
action_119 (13) = happyGoto action_133
action_119 (14) = happyGoto action_134
action_119 (15) = happyGoto action_71
action_119 _ = happyReduce_25

action_120 (76) = happyShift action_98
action_120 (20) = happyGoto action_132
action_120 _ = happyFail

action_121 _ = happyReduce_16

action_122 _ = happyReduce_72

action_123 (75) = happyShift action_131
action_123 _ = happyFail

action_124 (49) = happyShift action_130
action_124 _ = happyReduce_71

action_125 (51) = happyShift action_129
action_125 _ = happyFail

action_126 _ = happyReduce_37

action_127 (76) = happyShift action_91
action_127 (19) = happyGoto action_128
action_127 _ = happyFail

action_128 _ = happyReduce_70

action_129 (47) = happyShift action_59
action_129 (55) = happyShift action_60
action_129 (73) = happyShift action_61
action_129 (78) = happyShift action_62
action_129 (16) = happyGoto action_145
action_129 _ = happyFail

action_130 (76) = happyShift action_125
action_130 (21) = happyGoto action_144
action_130 _ = happyFail

action_131 _ = happyReduce_12

action_132 _ = happyReduce_67

action_133 _ = happyReduce_26

action_134 (73) = happyShift action_143
action_134 _ = happyFail

action_135 (61) = happyShift action_142
action_135 _ = happyFail

action_136 _ = happyReduce_19

action_137 (48) = happyShift action_141
action_137 _ = happyFail

action_138 _ = happyReduce_21

action_139 _ = happyReduce_31

action_140 _ = happyReduce_30

action_141 _ = happyReduce_22

action_142 (47) = happyShift action_72
action_142 (56) = happyShift action_73
action_142 (63) = happyShift action_74
action_142 (68) = happyShift action_75
action_142 (78) = happyShift action_76
action_142 (79) = happyShift action_77
action_142 (80) = happyShift action_78
action_142 (81) = happyShift action_79
action_142 (13) = happyGoto action_150
action_142 (15) = happyGoto action_71
action_142 _ = happyFail

action_143 (47) = happyShift action_72
action_143 (56) = happyShift action_73
action_143 (63) = happyShift action_74
action_143 (68) = happyShift action_75
action_143 (78) = happyShift action_76
action_143 (79) = happyShift action_77
action_143 (80) = happyShift action_78
action_143 (81) = happyShift action_79
action_143 (13) = happyGoto action_146
action_143 (15) = happyGoto action_71
action_143 (17) = happyGoto action_147
action_143 (33) = happyGoto action_148
action_143 (34) = happyGoto action_149
action_143 _ = happyReduce_62

action_144 _ = happyReduce_73

action_145 _ = happyReduce_39

action_146 (50) = happyShift action_154
action_146 _ = happyFail

action_147 (52) = happyShift action_153
action_147 _ = happyFail

action_148 (75) = happyShift action_152
action_148 _ = happyFail

action_149 (47) = happyShift action_72
action_149 (56) = happyShift action_73
action_149 (63) = happyShift action_74
action_149 (68) = happyShift action_75
action_149 (78) = happyShift action_76
action_149 (79) = happyShift action_77
action_149 (80) = happyShift action_78
action_149 (81) = happyShift action_79
action_149 (13) = happyGoto action_146
action_149 (15) = happyGoto action_71
action_149 (17) = happyGoto action_151
action_149 _ = happyReduce_61

action_150 _ = happyReduce_18

action_151 (52) = happyShift action_156
action_151 _ = happyFail

action_152 _ = happyReduce_20

action_153 _ = happyReduce_63

action_154 (47) = happyShift action_72
action_154 (56) = happyShift action_73
action_154 (63) = happyShift action_74
action_154 (68) = happyShift action_75
action_154 (78) = happyShift action_76
action_154 (79) = happyShift action_77
action_154 (80) = happyShift action_78
action_154 (81) = happyShift action_79
action_154 (13) = happyGoto action_155
action_154 (15) = happyGoto action_71
action_154 _ = happyFail

action_155 _ = happyReduce_35

action_156 _ = happyReduce_64

happyReduce_1 = happyReduce 9 4 happyReduction_1
happyReduction_1 (_ `HappyStk`
	(HappyAbsSyn27  happy_var_8) `HappyStk`
	(HappyAbsSyn31  happy_var_7) `HappyStk`
	(HappyAbsSyn29  happy_var_6) `HappyStk`
	(HappyAbsSyn25  happy_var_5) `HappyStk`
	(HappyAbsSyn23  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn4
		 (Module   (unTUident happy_var_2)  happy_var_4 happy_var_5 happy_var_6 happy_var_7 happy_var_8
	) `HappyStk` happyRest

happyReduce_2 = happySpecReduce_2  5 happyReduction_2
happyReduction_2 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn5
		 (TypeEx   (unTUident happy_var_2)
	)
happyReduction_2 _ _  = notHappyAtAll 

happyReduce_3 = happySpecReduce_2  5 happyReduction_3
happyReduction_3 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn5
		 (VarEx   (unTLident happy_var_2)
	)
happyReduction_3 _ _  = notHappyAtAll 

happyReduce_4 = happySpecReduce_3  6 happyReduction_4
happyReduction_4 (HappyAbsSyn7  happy_var_3)
	(HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn6
		 (ImportD   (unTUident happy_var_2) happy_var_3
	)
happyReduction_4 _ _ _  = notHappyAtAll 

happyReduce_5 = happySpecReduce_2  7 happyReduction_5
happyReduction_5 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn7
		 (AsAS   (unTUident happy_var_2)
	)
happyReduction_5 _ _  = notHappyAtAll 

happyReduce_6 = happySpecReduce_0  7 happyReduction_6
happyReduction_6  =  HappyAbsSyn7
		 (EmptyAS
	)

happyReduce_7 = happyReduce 5 8 happyReduction_7
happyReduction_7 ((HappyAbsSyn12  happy_var_5) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn41  happy_var_3) `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn8
		 (TypeD   (unTUident happy_var_2) happy_var_3  happy_var_5
	) `HappyStk` happyRest

happyReduce_8 = happySpecReduce_3  9 happyReduction_8
happyReduction_8 (HappyAbsSyn13  happy_var_3)
	(HappyAbsSyn11  happy_var_2)
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn9
		 (VarD  (unTLident happy_var_1) happy_var_2 happy_var_3
	)
happyReduction_8 _ _ _  = notHappyAtAll 

happyReduce_9 = happySpecReduce_3  10 happyReduction_9
happyReduction_9 (HappyAbsSyn16  happy_var_3)
	(HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn10
		 (InstD   (unTUident happy_var_2) happy_var_3
	)
happyReduction_9 _ _ _  = notHappyAtAll 

happyReduce_10 = happySpecReduce_1  11 happyReduction_10
happyReduction_10 _
	 =  HappyAbsSyn11
		 (Macro
	)

happyReduce_11 = happySpecReduce_1  11 happyReduction_11
happyReduction_11 _
	 =  HappyAbsSyn11
		 (Define
	)

happyReduce_12 = happyReduce 4 12 happyReduction_12
happyReduction_12 (_ `HappyStk`
	(HappyAbsSyn39  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn12
		 (TyRecord    happy_var_3
	) `HappyStk` happyRest

happyReduce_13 = happySpecReduce_2  12 happyReduction_13
happyReduction_13 (HappyAbsSyn37  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyTagged   happy_var_2
	)
happyReduction_13 _ _  = notHappyAtAll 

happyReduce_14 = happySpecReduce_2  12 happyReduction_14
happyReduction_14 (HappyAbsSyn35  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyEnum   happy_var_2
	)
happyReduction_14 _ _  = notHappyAtAll 

happyReduce_15 = happySpecReduce_2  12 happyReduction_15
happyReduction_15 (HappyAbsSyn16  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TySyn   happy_var_2
	)
happyReduction_15 _ _  = notHappyAtAll 

happyReduce_16 = happySpecReduce_3  12 happyReduction_16
happyReduction_16 (HappyAbsSyn16  happy_var_3)
	(HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyNewtype   (unTUident happy_var_2) happy_var_3
	)
happyReduction_16 _ _ _  = notHappyAtAll 

happyReduce_17 = happySpecReduce_2  12 happyReduction_17
happyReduction_17 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyUnit   (unTUident happy_var_2)
	)
happyReduction_17 _ _  = notHappyAtAll 

happyReduce_18 = happyReduce 6 13 happyReduction_18
happyReduction_18 ((HappyAbsSyn13  happy_var_6) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn13  happy_var_4) `HappyStk`
	(HappyAbsSyn11  happy_var_3) `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (LetE   (unTLident happy_var_2) happy_var_3 happy_var_4  happy_var_6
	) `HappyStk` happyRest

happyReduce_19 = happyReduce 4 13 happyReduction_19
happyReduction_19 ((HappyAbsSyn13  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (LamE   (unTLident happy_var_2)  happy_var_4
	) `HappyStk` happyRest

happyReduce_20 = happyReduce 7 13 happyReduction_20
happyReduction_20 (_ `HappyStk`
	(HappyAbsSyn33  happy_var_6) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn14  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn13  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (SwitchE   happy_var_2  happy_var_4  happy_var_6
	) `HappyStk` happyRest

happyReduce_21 = happyReduce 4 13 happyReduction_21
happyReduction_21 (_ `HappyStk`
	(HappyAbsSyn13  happy_var_3) `HappyStk`
	(HappyAbsSyn13  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (AppE   happy_var_2 happy_var_3
	) `HappyStk` happyRest

happyReduce_22 = happyReduce 5 13 happyReduction_22
happyReduction_22 (_ `HappyStk`
	(HappyAbsSyn16  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn13  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (AscribeE   happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_23 = happySpecReduce_1  13 happyReduction_23
happyReduction_23 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn13
		 (VarE  (unTLident happy_var_1)
	)
happyReduction_23 _  = notHappyAtAll 

happyReduce_24 = happySpecReduce_1  13 happyReduction_24
happyReduction_24 (HappyAbsSyn15  happy_var_1)
	 =  HappyAbsSyn13
		 (LitE  happy_var_1
	)
happyReduction_24 _  = notHappyAtAll 

happyReduce_25 = happySpecReduce_0  14 happyReduction_25
happyReduction_25  =  HappyAbsSyn14
		 (DefaultNone
	)

happyReduce_26 = happySpecReduce_1  14 happyReduction_26
happyReduction_26 (HappyAbsSyn13  happy_var_1)
	 =  HappyAbsSyn14
		 (DefaultSome  happy_var_1
	)
happyReduction_26 _  = notHappyAtAll 

happyReduce_27 = happySpecReduce_1  15 happyReduction_27
happyReduction_27 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (CharL  (unTChar happy_var_1)
	)
happyReduction_27 _  = notHappyAtAll 

happyReduce_28 = happySpecReduce_1  15 happyReduction_28
happyReduction_28 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (StringL  (unTString happy_var_1)
	)
happyReduction_28 _  = notHappyAtAll 

happyReduce_29 = happySpecReduce_1  15 happyReduction_29
happyReduction_29 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (NmbrL  (unTNumber happy_var_1)
	)
happyReduction_29 _  = notHappyAtAll 

happyReduce_30 = happyReduce 5 16 happyReduction_30
happyReduction_30 ((HappyAbsSyn16  happy_var_5) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn45  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn16
		 (TyCxt   happy_var_2   happy_var_5
	) `HappyStk` happyRest

happyReduce_31 = happyReduce 5 16 happyReduction_31
happyReduction_31 (_ `HappyStk`
	(HappyAbsSyn16  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn16  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn16
		 (TyFun   happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_32 = happySpecReduce_1  16 happyReduction_32
happyReduction_32 _
	 =  HappyAbsSyn16
		 (TyVoid
	)

happyReduce_33 = happyReduce 4 16 happyReduction_33
happyReduction_33 (_ `HappyStk`
	(HappyAbsSyn43  happy_var_3) `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn16
		 (TyConstr   (unTUident happy_var_2) happy_var_3
	) `HappyStk` happyRest

happyReduce_34 = happySpecReduce_1  16 happyReduction_34
happyReduction_34 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn16
		 (TyVarT  (unTLident happy_var_1)
	)
happyReduction_34 _  = notHappyAtAll 

happyReduce_35 = happySpecReduce_3  17 happyReduction_35
happyReduction_35 (HappyAbsSyn13  happy_var_3)
	_
	(HappyAbsSyn13  happy_var_1)
	 =  HappyAbsSyn17
		 (SwitchAlt  happy_var_1  happy_var_3
	)
happyReduction_35 _ _ _  = notHappyAtAll 

happyReduce_36 = happySpecReduce_2  18 happyReduction_36
happyReduction_36 (HappyAbsSyn41  happy_var_2)
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn18
		 (Cxt  (unTUident happy_var_1) happy_var_2
	)
happyReduction_36 _ _  = notHappyAtAll 

happyReduce_37 = happySpecReduce_2  19 happyReduction_37
happyReduction_37 (HappyAbsSyn16  happy_var_2)
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn19
		 (ConC  (unTUident happy_var_1) happy_var_2
	)
happyReduction_37 _ _  = notHappyAtAll 

happyReduce_38 = happySpecReduce_1  20 happyReduction_38
happyReduction_38 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn20
		 (EnumC  (unTUident happy_var_1)
	)
happyReduction_38 _  = notHappyAtAll 

happyReduce_39 = happySpecReduce_3  21 happyReduction_39
happyReduction_39 (HappyAbsSyn16  happy_var_3)
	_
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn21
		 (FieldT  (unTUident happy_var_1)  happy_var_3
	)
happyReduction_39 _ _ _  = notHappyAtAll 

happyReduce_40 = happySpecReduce_1  22 happyReduction_40
happyReduction_40 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn22
		 (Var  (unTLident happy_var_1)
	)
happyReduction_40 _  = notHappyAtAll 

happyReduce_41 = happySpecReduce_1  23 happyReduction_41
happyReduction_41 (HappyAbsSyn24  happy_var_1)
	 =  HappyAbsSyn23
		 (reverse happy_var_1
	)
happyReduction_41 _  = notHappyAtAll 

happyReduce_42 = happySpecReduce_0  23 happyReduction_42
happyReduction_42  =  HappyAbsSyn23
		 ([]
	)

happyReduce_43 = happySpecReduce_2  24 happyReduction_43
happyReduction_43 _
	(HappyAbsSyn5  happy_var_1)
	 =  HappyAbsSyn24
		 ([happy_var_1]
	)
happyReduction_43 _ _  = notHappyAtAll 

happyReduce_44 = happySpecReduce_3  24 happyReduction_44
happyReduction_44 _
	(HappyAbsSyn5  happy_var_2)
	(HappyAbsSyn24  happy_var_1)
	 =  HappyAbsSyn24
		 (happy_var_2 : happy_var_1
	)
happyReduction_44 _ _ _  = notHappyAtAll 

happyReduce_45 = happySpecReduce_1  25 happyReduction_45
happyReduction_45 (HappyAbsSyn26  happy_var_1)
	 =  HappyAbsSyn25
		 (reverse happy_var_1
	)
happyReduction_45 _  = notHappyAtAll 

happyReduce_46 = happySpecReduce_0  25 happyReduction_46
happyReduction_46  =  HappyAbsSyn25
		 ([]
	)

happyReduce_47 = happySpecReduce_2  26 happyReduction_47
happyReduction_47 _
	(HappyAbsSyn6  happy_var_1)
	 =  HappyAbsSyn26
		 ([happy_var_1]
	)
happyReduction_47 _ _  = notHappyAtAll 

happyReduce_48 = happySpecReduce_3  26 happyReduction_48
happyReduction_48 _
	(HappyAbsSyn6  happy_var_2)
	(HappyAbsSyn26  happy_var_1)
	 =  HappyAbsSyn26
		 (happy_var_2 : happy_var_1
	)
happyReduction_48 _ _ _  = notHappyAtAll 

happyReduce_49 = happySpecReduce_1  27 happyReduction_49
happyReduction_49 (HappyAbsSyn28  happy_var_1)
	 =  HappyAbsSyn27
		 (reverse happy_var_1
	)
happyReduction_49 _  = notHappyAtAll 

happyReduce_50 = happySpecReduce_0  27 happyReduction_50
happyReduction_50  =  HappyAbsSyn27
		 ([]
	)

happyReduce_51 = happySpecReduce_2  28 happyReduction_51
happyReduction_51 _
	(HappyAbsSyn9  happy_var_1)
	 =  HappyAbsSyn28
		 ([happy_var_1]
	)
happyReduction_51 _ _  = notHappyAtAll 

happyReduce_52 = happySpecReduce_3  28 happyReduction_52
happyReduction_52 _
	(HappyAbsSyn9  happy_var_2)
	(HappyAbsSyn28  happy_var_1)
	 =  HappyAbsSyn28
		 (happy_var_2 : happy_var_1
	)
happyReduction_52 _ _ _  = notHappyAtAll 

happyReduce_53 = happySpecReduce_1  29 happyReduction_53
happyReduction_53 (HappyAbsSyn30  happy_var_1)
	 =  HappyAbsSyn29
		 (reverse happy_var_1
	)
happyReduction_53 _  = notHappyAtAll 

happyReduce_54 = happySpecReduce_0  29 happyReduction_54
happyReduction_54  =  HappyAbsSyn29
		 ([]
	)

happyReduce_55 = happySpecReduce_2  30 happyReduction_55
happyReduction_55 _
	(HappyAbsSyn8  happy_var_1)
	 =  HappyAbsSyn30
		 ([happy_var_1]
	)
happyReduction_55 _ _  = notHappyAtAll 

happyReduce_56 = happySpecReduce_3  30 happyReduction_56
happyReduction_56 _
	(HappyAbsSyn8  happy_var_2)
	(HappyAbsSyn30  happy_var_1)
	 =  HappyAbsSyn30
		 (happy_var_2 : happy_var_1
	)
happyReduction_56 _ _ _  = notHappyAtAll 

happyReduce_57 = happySpecReduce_1  31 happyReduction_57
happyReduction_57 (HappyAbsSyn32  happy_var_1)
	 =  HappyAbsSyn31
		 (reverse happy_var_1
	)
happyReduction_57 _  = notHappyAtAll 

happyReduce_58 = happySpecReduce_0  31 happyReduction_58
happyReduction_58  =  HappyAbsSyn31
		 ([]
	)

happyReduce_59 = happySpecReduce_2  32 happyReduction_59
happyReduction_59 _
	(HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn32
		 ([happy_var_1]
	)
happyReduction_59 _ _  = notHappyAtAll 

happyReduce_60 = happySpecReduce_3  32 happyReduction_60
happyReduction_60 _
	(HappyAbsSyn10  happy_var_2)
	(HappyAbsSyn32  happy_var_1)
	 =  HappyAbsSyn32
		 (happy_var_2 : happy_var_1
	)
happyReduction_60 _ _ _  = notHappyAtAll 

happyReduce_61 = happySpecReduce_1  33 happyReduction_61
happyReduction_61 (HappyAbsSyn34  happy_var_1)
	 =  HappyAbsSyn33
		 (reverse happy_var_1
	)
happyReduction_61 _  = notHappyAtAll 

happyReduce_62 = happySpecReduce_0  33 happyReduction_62
happyReduction_62  =  HappyAbsSyn33
		 ([]
	)

happyReduce_63 = happySpecReduce_2  34 happyReduction_63
happyReduction_63 _
	(HappyAbsSyn17  happy_var_1)
	 =  HappyAbsSyn34
		 ([happy_var_1]
	)
happyReduction_63 _ _  = notHappyAtAll 

happyReduce_64 = happySpecReduce_3  34 happyReduction_64
happyReduction_64 _
	(HappyAbsSyn17  happy_var_2)
	(HappyAbsSyn34  happy_var_1)
	 =  HappyAbsSyn34
		 (happy_var_2 : happy_var_1
	)
happyReduction_64 _ _ _  = notHappyAtAll 

happyReduce_65 = happySpecReduce_1  35 happyReduction_65
happyReduction_65 (HappyAbsSyn36  happy_var_1)
	 =  HappyAbsSyn35
		 (reverse happy_var_1
	)
happyReduction_65 _  = notHappyAtAll 

happyReduce_66 = happySpecReduce_1  36 happyReduction_66
happyReduction_66 (HappyAbsSyn20  happy_var_1)
	 =  HappyAbsSyn36
		 ([happy_var_1]
	)
happyReduction_66 _  = notHappyAtAll 

happyReduce_67 = happySpecReduce_3  36 happyReduction_67
happyReduction_67 (HappyAbsSyn20  happy_var_3)
	_
	(HappyAbsSyn36  happy_var_1)
	 =  HappyAbsSyn36
		 (happy_var_3 : happy_var_1
	)
happyReduction_67 _ _ _  = notHappyAtAll 

happyReduce_68 = happySpecReduce_1  37 happyReduction_68
happyReduction_68 (HappyAbsSyn38  happy_var_1)
	 =  HappyAbsSyn37
		 (reverse happy_var_1
	)
happyReduction_68 _  = notHappyAtAll 

happyReduce_69 = happySpecReduce_1  38 happyReduction_69
happyReduction_69 (HappyAbsSyn19  happy_var_1)
	 =  HappyAbsSyn38
		 ([happy_var_1]
	)
happyReduction_69 _  = notHappyAtAll 

happyReduce_70 = happySpecReduce_3  38 happyReduction_70
happyReduction_70 (HappyAbsSyn19  happy_var_3)
	_
	(HappyAbsSyn38  happy_var_1)
	 =  HappyAbsSyn38
		 (happy_var_3 : happy_var_1
	)
happyReduction_70 _ _ _  = notHappyAtAll 

happyReduce_71 = happySpecReduce_1  39 happyReduction_71
happyReduction_71 (HappyAbsSyn40  happy_var_1)
	 =  HappyAbsSyn39
		 (reverse happy_var_1
	)
happyReduction_71 _  = notHappyAtAll 

happyReduce_72 = happySpecReduce_1  40 happyReduction_72
happyReduction_72 (HappyAbsSyn21  happy_var_1)
	 =  HappyAbsSyn40
		 ([happy_var_1]
	)
happyReduction_72 _  = notHappyAtAll 

happyReduce_73 = happySpecReduce_3  40 happyReduction_73
happyReduction_73 (HappyAbsSyn21  happy_var_3)
	_
	(HappyAbsSyn40  happy_var_1)
	 =  HappyAbsSyn40
		 (happy_var_3 : happy_var_1
	)
happyReduction_73 _ _ _  = notHappyAtAll 

happyReduce_74 = happySpecReduce_1  41 happyReduction_74
happyReduction_74 (HappyAbsSyn42  happy_var_1)
	 =  HappyAbsSyn41
		 (reverse happy_var_1
	)
happyReduction_74 _  = notHappyAtAll 

happyReduce_75 = happySpecReduce_0  41 happyReduction_75
happyReduction_75  =  HappyAbsSyn41
		 ([]
	)

happyReduce_76 = happySpecReduce_1  42 happyReduction_76
happyReduction_76 (HappyAbsSyn22  happy_var_1)
	 =  HappyAbsSyn42
		 ([happy_var_1]
	)
happyReduction_76 _  = notHappyAtAll 

happyReduce_77 = happySpecReduce_2  42 happyReduction_77
happyReduction_77 (HappyAbsSyn22  happy_var_2)
	(HappyAbsSyn42  happy_var_1)
	 =  HappyAbsSyn42
		 (happy_var_2 : happy_var_1
	)
happyReduction_77 _ _  = notHappyAtAll 

happyReduce_78 = happySpecReduce_1  43 happyReduction_78
happyReduction_78 (HappyAbsSyn44  happy_var_1)
	 =  HappyAbsSyn43
		 (reverse happy_var_1
	)
happyReduction_78 _  = notHappyAtAll 

happyReduce_79 = happySpecReduce_0  43 happyReduction_79
happyReduction_79  =  HappyAbsSyn43
		 ([]
	)

happyReduce_80 = happySpecReduce_1  44 happyReduction_80
happyReduction_80 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn44
		 ([happy_var_1]
	)
happyReduction_80 _  = notHappyAtAll 

happyReduce_81 = happySpecReduce_2  44 happyReduction_81
happyReduction_81 (HappyAbsSyn16  happy_var_2)
	(HappyAbsSyn44  happy_var_1)
	 =  HappyAbsSyn44
		 (happy_var_2 : happy_var_1
	)
happyReduction_81 _ _  = notHappyAtAll 

happyReduce_82 = happySpecReduce_1  45 happyReduction_82
happyReduction_82 (HappyAbsSyn46  happy_var_1)
	 =  HappyAbsSyn45
		 (reverse happy_var_1
	)
happyReduction_82 _  = notHappyAtAll 

happyReduce_83 = happySpecReduce_1  46 happyReduction_83
happyReduction_83 (HappyAbsSyn18  happy_var_1)
	 =  HappyAbsSyn46
		 ([happy_var_1]
	)
happyReduction_83 _  = notHappyAtAll 

happyReduce_84 = happySpecReduce_3  46 happyReduction_84
happyReduction_84 (HappyAbsSyn18  happy_var_3)
	_
	(HappyAbsSyn46  happy_var_1)
	 =  HappyAbsSyn46
		 (happy_var_3 : happy_var_1
	)
happyReduction_84 _ _ _  = notHappyAtAll 

happyNewToken action sts stk [] =
	action 82 82 notHappyAtAll (HappyState action) sts stk []

happyNewToken action sts stk (tk:tks) =
	let cont i = action i i tk (HappyState action) sts stk tks in
	case tk of {
	TSymbol _ "(" -> cont 47;
	TSymbol _ ")" -> cont 48;
	TSymbol _ "," -> cont 49;
	TSymbol _ "->" -> cont 50;
	TSymbol _ "::" -> cont 51;
	TSymbol _ ";" -> cont 52;
	TSymbol _ "=" -> cont 53;
	TSymbol _ "=>" -> cont 54;
	TSymbol _ "VoidT" -> cont 55;
	TSymbol _ "\\" -> cont 56;
	TSymbol _ "as" -> cont 57;
	TSymbol _ "enum" -> cont 58;
	TSymbol _ "export" -> cont 59;
	TSymbol _ "import" -> cont 60;
	TSymbol _ "in" -> cont 61;
	TSymbol _ "instance" -> cont 62;
	TSymbol _ "let" -> cont 63;
	TSymbol _ "module" -> cont 64;
	TSymbol _ "newtype" -> cont 65;
	TSymbol _ "of" -> cont 66;
	TSymbol _ "record" -> cont 67;
	TSymbol _ "switch" -> cont 68;
	TSymbol _ "synonym" -> cont 69;
	TSymbol _ "tagged" -> cont 70;
	TSymbol _ "type" -> cont 71;
	TSymbol _ "unit" -> cont 72;
	TSymbol _ "{" -> cont 73;
	TSymbol _ "|" -> cont 74;
	TSymbol _ "}" -> cont 75;
	TUident _ _ -> cont 76;
	TUsym _ _ -> cont 77;
	TLident _ _ -> cont 78;
	TString _ _ -> cont 79;
	TChar _ _ -> cont 80;
	TNumber _ _ -> cont 81;
	_ -> happyError' (tk:tks)
	}

happyError_ tk tks = happyError' (tk:tks)

newtype HappyIdentity a = HappyIdentity a
happyIdentity = HappyIdentity
happyRunIdentity (HappyIdentity a) = a

instance Monad HappyIdentity where
    return = HappyIdentity
    (HappyIdentity p) >>= q = q p

happyThen :: () => HappyIdentity a -> (a -> HappyIdentity b) -> HappyIdentity b
happyThen = (>>=)
happyReturn :: () => a -> HappyIdentity a
happyReturn = (return)
happyThen1 m k tks = (>>=) m (\a -> k a tks)
happyReturn1 :: () => a -> b -> HappyIdentity a
happyReturn1 = \a tks -> (return) a
happyError' :: () => [((Token Point))] -> HappyIdentity a
happyError' = HappyIdentity . happyError

grmParse tks = happyRunIdentity happySomeParser where
  happySomeParser = happyThen (happyParse action_0 tks) (\x -> case x of {HappyAbsSyn4 z -> happyReturn z; _other -> notHappyAtAll })

happySeq = happyDontSeq



{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "<built-in>" #-}
{-# LINE 1 "<command-line>" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
-- Id: GenericTemplate.hs,v 1.26 2005/01/14 14:47:22 simonmar Exp 

{-# LINE 30 "templates/GenericTemplate.hs" #-}








{-# LINE 51 "templates/GenericTemplate.hs" #-}

{-# LINE 61 "templates/GenericTemplate.hs" #-}

{-# LINE 70 "templates/GenericTemplate.hs" #-}

infixr 9 `HappyStk`
data HappyStk a = HappyStk a (HappyStk a)

-----------------------------------------------------------------------------
-- starting the parse

happyParse start_state = happyNewToken start_state notHappyAtAll notHappyAtAll

-----------------------------------------------------------------------------
-- Accepting the parse

-- If the current token is (1), it means we've just accepted a partial
-- parse (a %partial parser).  We must ignore the saved token on the top of
-- the stack in this case.
happyAccept (1) tk st sts (_ `HappyStk` ans `HappyStk` _) =
	happyReturn1 ans
happyAccept j tk st sts (HappyStk ans _) = 
	 (happyReturn1 ans)

-----------------------------------------------------------------------------
-- Arrays only: do the next action

{-# LINE 148 "templates/GenericTemplate.hs" #-}

-----------------------------------------------------------------------------
-- HappyState data type (not arrays)



newtype HappyState b c = HappyState
        (Int ->                    -- token number
         Int ->                    -- token number (yes, again)
         b ->                           -- token semantic value
         HappyState b c ->              -- current state
         [HappyState b c] ->            -- state stack
         c)



-----------------------------------------------------------------------------
-- Shifting a token

happyShift new_state (1) tk st sts stk@(x `HappyStk` _) =
     let (i) = (case x of { HappyErrorToken (i) -> i }) in
--     trace "shifting the error token" $
     new_state i i tk (HappyState (new_state)) ((st):(sts)) (stk)

happyShift new_state i tk st sts stk =
     happyNewToken new_state ((st):(sts)) ((HappyTerminal (tk))`HappyStk`stk)

-- happyReduce is specialised for the common cases.

happySpecReduce_0 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_0 nt fn j tk st@((HappyState (action))) sts stk
     = action nt j tk st ((st):(sts)) (fn `HappyStk` stk)

happySpecReduce_1 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_1 nt fn j tk _ sts@(((st@(HappyState (action))):(_))) (v1`HappyStk`stk')
     = let r = fn v1 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_2 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_2 nt fn j tk _ ((_):(sts@(((st@(HappyState (action))):(_))))) (v1`HappyStk`v2`HappyStk`stk')
     = let r = fn v1 v2 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_3 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_3 nt fn j tk _ ((_):(((_):(sts@(((st@(HappyState (action))):(_))))))) (v1`HappyStk`v2`HappyStk`v3`HappyStk`stk')
     = let r = fn v1 v2 v3 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happyReduce k i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyReduce k nt fn j tk st sts stk
     = case happyDrop (k - ((1) :: Int)) sts of
	 sts1@(((st1@(HappyState (action))):(_))) ->
        	let r = fn stk in  -- it doesn't hurt to always seq here...
       		happyDoSeq r (action nt j tk st1 sts1 r)

happyMonadReduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonadReduce k nt fn j tk st sts stk =
        happyThen1 (fn stk tk) (\r -> action nt j tk st1 sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk

happyMonad2Reduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonad2Reduce k nt fn j tk st sts stk =
       happyThen1 (fn stk tk) (\r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk





             new_state = action


happyDrop (0) l = l
happyDrop n ((_):(t)) = happyDrop (n - ((1) :: Int)) t

happyDropStk (0) l = l
happyDropStk n (x `HappyStk` xs) = happyDropStk (n - ((1)::Int)) xs

-----------------------------------------------------------------------------
-- Moving to a new state after a reduction

{-# LINE 246 "templates/GenericTemplate.hs" #-}
happyGoto action j tk st = action j j tk (HappyState action)


-----------------------------------------------------------------------------
-- Error recovery ((1) is the error token)

-- parse error if we are in recovery and we fail again
happyFail  (1) tk old_st _ stk =
--	trace "failing" $ 
    	happyError_ tk

{-  We don't need state discarding for our restricted implementation of
    "error".  In fact, it can cause some bogus parses, so I've disabled it
    for now --SDM

-- discard a state
happyFail  (1) tk old_st (((HappyState (action))):(sts)) 
						(saved_tok `HappyStk` _ `HappyStk` stk) =
--	trace ("discarding state, depth " ++ show (length stk))  $
	action (1) (1) tk (HappyState (action)) sts ((saved_tok`HappyStk`stk))
-}

-- Enter error recovery: generate an error token,
--                       save the old token and carry on.
happyFail  i tk (HappyState (action)) sts stk =
--      trace "entering error recovery" $
	action (1) (1) tk (HappyState (action)) sts ( (HappyErrorToken (i)) `HappyStk` stk)

-- Internal happy errors:

notHappyAtAll :: a
notHappyAtAll = error "Internal Happy error\n"

-----------------------------------------------------------------------------
-- Hack to get the typechecker to accept our action functions







-----------------------------------------------------------------------------
-- Seq-ing.  If the --strict flag is given, then Happy emits 
--	happySeq = happyDoSeq
-- otherwise it emits
-- 	happySeq = happyDontSeq

happyDoSeq, happyDontSeq :: a -> b -> b
happyDoSeq   a b = a `seq` b
happyDontSeq a b = b

-----------------------------------------------------------------------------
-- Don't inline any functions from the template.  GHC has a nasty habit
-- of deciding to inline happyGoto everywhere, which increases the size of
-- the generated parser quite a bit.

{-# LINE 311 "templates/GenericTemplate.hs" #-}
{-# NOINLINE happyShift #-}
{-# NOINLINE happySpecReduce_0 #-}
{-# NOINLINE happySpecReduce_1 #-}
{-# NOINLINE happySpecReduce_2 #-}
{-# NOINLINE happySpecReduce_3 #-}
{-# NOINLINE happyReduce #-}
{-# NOINLINE happyMonadReduce #-}
{-# NOINLINE happyGoto #-}
{-# NOINLINE happyFail #-}

-- end of Happy Template.
