{-# OPTIONS_GHC -w #-}
{-# OPTIONS -w #-}
-- Haskell module generated by grm *** DO NOT EDIT ***


module Language.Pds.Par where
import Grm.Prims
import Grm.Lex
import Language.Pds.Abs

-- parser produced by Happy Version 1.18.6

data HappyAbsSyn t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42 t43 t44 t45 t46 t47 t48
	= HappyTerminal ((Token Point))
	| HappyErrorToken Int
	| HappyAbsSyn4 t4
	| HappyAbsSyn5 t5
	| HappyAbsSyn6 t6
	| HappyAbsSyn7 t7
	| HappyAbsSyn8 t8
	| HappyAbsSyn9 t9
	| HappyAbsSyn10 t10
	| HappyAbsSyn11 t11
	| HappyAbsSyn12 t12
	| HappyAbsSyn13 t13
	| HappyAbsSyn14 t14
	| HappyAbsSyn15 t15
	| HappyAbsSyn16 t16
	| HappyAbsSyn17 t17
	| HappyAbsSyn18 t18
	| HappyAbsSyn19 t19
	| HappyAbsSyn20 t20
	| HappyAbsSyn21 t21
	| HappyAbsSyn22 t22
	| HappyAbsSyn23 t23
	| HappyAbsSyn24 t24
	| HappyAbsSyn25 t25
	| HappyAbsSyn26 t26
	| HappyAbsSyn27 t27
	| HappyAbsSyn28 t28
	| HappyAbsSyn29 t29
	| HappyAbsSyn30 t30
	| HappyAbsSyn31 t31
	| HappyAbsSyn32 t32
	| HappyAbsSyn33 t33
	| HappyAbsSyn34 t34
	| HappyAbsSyn35 t35
	| HappyAbsSyn36 t36
	| HappyAbsSyn37 t37
	| HappyAbsSyn38 t38
	| HappyAbsSyn39 t39
	| HappyAbsSyn40 t40
	| HappyAbsSyn41 t41
	| HappyAbsSyn42 t42
	| HappyAbsSyn43 t43
	| HappyAbsSyn44 t44
	| HappyAbsSyn45 t45
	| HappyAbsSyn46 t46
	| HappyAbsSyn47 t47
	| HappyAbsSyn48 t48

action_0 (66) = happyShift action_2
action_0 (4) = happyGoto action_3
action_0 _ = happyFail

action_1 (66) = happyShift action_2
action_1 _ = happyFail

action_2 (78) = happyShift action_4
action_2 _ = happyFail

action_3 (84) = happyAccept
action_3 _ = happyFail

action_4 (75) = happyShift action_5
action_4 _ = happyFail

action_5 (61) = happyShift action_9
action_5 (5) = happyGoto action_6
action_5 (23) = happyGoto action_7
action_5 (24) = happyGoto action_8
action_5 _ = happyReduce_41

action_6 (54) = happyShift action_17
action_6 _ = happyFail

action_7 (62) = happyShift action_16
action_7 (6) = happyGoto action_13
action_7 (25) = happyGoto action_14
action_7 (26) = happyGoto action_15
action_7 _ = happyReduce_45

action_8 (61) = happyShift action_9
action_8 (5) = happyGoto action_12
action_8 _ = happyReduce_40

action_9 (78) = happyShift action_10
action_9 (80) = happyShift action_11
action_9 _ = happyFail

action_10 _ = happyReduce_2

action_11 _ = happyReduce_3

action_12 (54) = happyShift action_25
action_12 _ = happyFail

action_13 (54) = happyShift action_24
action_13 _ = happyFail

action_14 (59) = happyShift action_23
action_14 (7) = happyGoto action_20
action_14 (31) = happyGoto action_21
action_14 (32) = happyGoto action_22
action_14 _ = happyReduce_57

action_15 (62) = happyShift action_16
action_15 (6) = happyGoto action_19
action_15 _ = happyReduce_44

action_16 (78) = happyShift action_18
action_16 _ = happyFail

action_17 _ = happyReduce_42

action_18 _ = happyReduce_4

action_19 (54) = happyShift action_33
action_19 _ = happyFail

action_20 (54) = happyShift action_32
action_20 _ = happyFail

action_21 (73) = happyShift action_31
action_21 (8) = happyGoto action_28
action_21 (29) = happyGoto action_29
action_21 (30) = happyGoto action_30
action_21 _ = happyReduce_53

action_22 (59) = happyShift action_23
action_22 (7) = happyGoto action_27
action_22 _ = happyReduce_56

action_23 (83) = happyShift action_26
action_23 _ = happyFail

action_24 _ = happyReduce_46

action_25 _ = happyReduce_43

action_26 _ = happyReduce_5

action_27 (54) = happyShift action_41
action_27 _ = happyFail

action_28 (54) = happyShift action_40
action_28 _ = happyFail

action_29 (64) = happyShift action_39
action_29 (10) = happyGoto action_36
action_29 (33) = happyGoto action_37
action_29 (34) = happyGoto action_38
action_29 _ = happyReduce_61

action_30 (73) = happyShift action_31
action_30 (8) = happyGoto action_35
action_30 _ = happyReduce_52

action_31 (78) = happyShift action_34
action_31 _ = happyFail

action_32 _ = happyReduce_58

action_33 _ = happyReduce_47

action_34 (80) = happyShift action_53
action_34 (22) = happyGoto action_50
action_34 (43) = happyGoto action_51
action_34 (44) = happyGoto action_52
action_34 _ = happyReduce_78

action_35 (54) = happyShift action_49
action_35 _ = happyFail

action_36 (54) = happyShift action_48
action_36 _ = happyFail

action_37 (80) = happyShift action_47
action_37 (9) = happyGoto action_44
action_37 (27) = happyGoto action_45
action_37 (28) = happyGoto action_46
action_37 _ = happyReduce_49

action_38 (64) = happyShift action_39
action_38 (10) = happyGoto action_43
action_38 _ = happyReduce_60

action_39 (78) = happyShift action_42
action_39 _ = happyFail

action_40 _ = happyReduce_54

action_41 _ = happyReduce_59

action_42 (49) = happyShift action_64
action_42 (57) = happyShift action_65
action_42 (75) = happyShift action_66
action_42 (80) = happyShift action_67
action_42 (16) = happyGoto action_63
action_42 _ = happyFail

action_43 (54) = happyShift action_62
action_43 _ = happyFail

action_44 (54) = happyShift action_61
action_44 _ = happyFail

action_45 (77) = happyShift action_60
action_45 _ = happyFail

action_46 (80) = happyShift action_47
action_46 (9) = happyGoto action_59
action_46 _ = happyReduce_48

action_47 (55) = happyShift action_57
action_47 (56) = happyShift action_58
action_47 (11) = happyGoto action_56
action_47 _ = happyFail

action_48 _ = happyReduce_62

action_49 _ = happyReduce_55

action_50 _ = happyReduce_79

action_51 (55) = happyShift action_55
action_51 _ = happyFail

action_52 (80) = happyShift action_53
action_52 (22) = happyGoto action_54
action_52 _ = happyReduce_77

action_53 _ = happyReduce_39

action_54 _ = happyReduce_80

action_55 (60) = happyShift action_86
action_55 (67) = happyShift action_87
action_55 (69) = happyShift action_88
action_55 (71) = happyShift action_89
action_55 (72) = happyShift action_90
action_55 (74) = happyShift action_91
action_55 (12) = happyGoto action_85
action_55 _ = happyFail

action_56 (49) = happyShift action_77
action_56 (58) = happyShift action_78
action_56 (65) = happyShift action_79
action_56 (70) = happyShift action_80
action_56 (80) = happyShift action_81
action_56 (81) = happyShift action_82
action_56 (82) = happyShift action_83
action_56 (83) = happyShift action_84
action_56 (13) = happyGoto action_75
action_56 (15) = happyGoto action_76
action_56 _ = happyFail

action_57 _ = happyReduce_10

action_58 _ = happyReduce_9

action_59 (54) = happyShift action_74
action_59 _ = happyFail

action_60 _ = happyReduce_1

action_61 _ = happyReduce_50

action_62 _ = happyReduce_63

action_63 _ = happyReduce_8

action_64 (49) = happyShift action_64
action_64 (57) = happyShift action_65
action_64 (75) = happyShift action_66
action_64 (78) = happyShift action_73
action_64 (80) = happyShift action_67
action_64 (16) = happyGoto action_72
action_64 _ = happyFail

action_65 _ = happyReduce_31

action_66 (78) = happyShift action_71
action_66 (18) = happyGoto action_68
action_66 (47) = happyGoto action_69
action_66 (48) = happyGoto action_70
action_66 _ = happyReduce_86

action_67 _ = happyReduce_33

action_68 _ = happyReduce_87

action_69 (77) = happyShift action_114
action_69 _ = happyFail

action_70 (51) = happyShift action_113
action_70 _ = happyReduce_85

action_71 (80) = happyShift action_53
action_71 (22) = happyGoto action_50
action_71 (43) = happyGoto action_112
action_71 (44) = happyGoto action_52
action_71 _ = happyReduce_78

action_72 (52) = happyShift action_111
action_72 _ = happyFail

action_73 (49) = happyShift action_64
action_73 (57) = happyShift action_65
action_73 (75) = happyShift action_66
action_73 (80) = happyShift action_67
action_73 (16) = happyGoto action_108
action_73 (45) = happyGoto action_109
action_73 (46) = happyGoto action_110
action_73 _ = happyReduce_82

action_74 _ = happyReduce_51

action_75 _ = happyReduce_7

action_76 _ = happyReduce_23

action_77 (49) = happyShift action_77
action_77 (58) = happyShift action_78
action_77 (65) = happyShift action_79
action_77 (70) = happyShift action_80
action_77 (80) = happyShift action_81
action_77 (81) = happyShift action_82
action_77 (82) = happyShift action_83
action_77 (83) = happyShift action_84
action_77 (13) = happyGoto action_107
action_77 (15) = happyGoto action_76
action_77 _ = happyFail

action_78 (80) = happyShift action_106
action_78 _ = happyFail

action_79 (80) = happyShift action_105
action_79 _ = happyFail

action_80 (49) = happyShift action_77
action_80 (58) = happyShift action_78
action_80 (65) = happyShift action_79
action_80 (70) = happyShift action_80
action_80 (80) = happyShift action_81
action_80 (81) = happyShift action_82
action_80 (82) = happyShift action_83
action_80 (83) = happyShift action_84
action_80 (13) = happyGoto action_104
action_80 (15) = happyGoto action_76
action_80 _ = happyFail

action_81 _ = happyReduce_22

action_82 _ = happyReduce_27

action_83 _ = happyReduce_26

action_84 _ = happyReduce_28

action_85 _ = happyReduce_6

action_86 (78) = happyShift action_103
action_86 (20) = happyGoto action_100
action_86 (37) = happyGoto action_101
action_86 (38) = happyGoto action_102
action_86 _ = happyFail

action_87 (78) = happyShift action_99
action_87 _ = happyFail

action_88 (75) = happyShift action_98
action_88 _ = happyFail

action_89 (49) = happyShift action_64
action_89 (57) = happyShift action_65
action_89 (75) = happyShift action_66
action_89 (80) = happyShift action_67
action_89 (16) = happyGoto action_97
action_89 _ = happyFail

action_90 (78) = happyShift action_96
action_90 (19) = happyGoto action_93
action_90 (39) = happyGoto action_94
action_90 (40) = happyGoto action_95
action_90 _ = happyFail

action_91 (78) = happyShift action_92
action_91 _ = happyFail

action_92 _ = happyReduce_16

action_93 _ = happyReduce_72

action_94 _ = happyReduce_12

action_95 (76) = happyShift action_132
action_95 _ = happyReduce_71

action_96 (49) = happyShift action_64
action_96 (57) = happyShift action_65
action_96 (75) = happyShift action_66
action_96 (80) = happyShift action_67
action_96 (16) = happyGoto action_131
action_96 _ = happyFail

action_97 _ = happyReduce_14

action_98 (80) = happyShift action_130
action_98 (21) = happyGoto action_127
action_98 (41) = happyGoto action_128
action_98 (42) = happyGoto action_129
action_98 _ = happyFail

action_99 (49) = happyShift action_64
action_99 (57) = happyShift action_65
action_99 (75) = happyShift action_66
action_99 (80) = happyShift action_67
action_99 (16) = happyGoto action_126
action_99 _ = happyFail

action_100 _ = happyReduce_69

action_101 _ = happyReduce_13

action_102 (76) = happyShift action_125
action_102 _ = happyReduce_68

action_103 _ = happyReduce_37

action_104 (68) = happyShift action_124
action_104 _ = happyFail

action_105 (55) = happyShift action_57
action_105 (56) = happyShift action_58
action_105 (11) = happyGoto action_123
action_105 _ = happyFail

action_106 (52) = happyShift action_122
action_106 _ = happyFail

action_107 (49) = happyShift action_77
action_107 (53) = happyShift action_121
action_107 (58) = happyShift action_78
action_107 (65) = happyShift action_79
action_107 (70) = happyShift action_80
action_107 (80) = happyShift action_81
action_107 (81) = happyShift action_82
action_107 (82) = happyShift action_83
action_107 (83) = happyShift action_84
action_107 (13) = happyGoto action_120
action_107 (15) = happyGoto action_76
action_107 _ = happyFail

action_108 _ = happyReduce_83

action_109 (50) = happyShift action_119
action_109 _ = happyFail

action_110 (49) = happyShift action_64
action_110 (57) = happyShift action_65
action_110 (75) = happyShift action_66
action_110 (80) = happyShift action_67
action_110 (16) = happyGoto action_118
action_110 _ = happyReduce_81

action_111 (49) = happyShift action_64
action_111 (57) = happyShift action_65
action_111 (75) = happyShift action_66
action_111 (80) = happyShift action_67
action_111 (16) = happyGoto action_117
action_111 _ = happyFail

action_112 _ = happyReduce_35

action_113 (78) = happyShift action_71
action_113 (18) = happyGoto action_116
action_113 _ = happyFail

action_114 (56) = happyShift action_115
action_114 _ = happyFail

action_115 (49) = happyShift action_64
action_115 (57) = happyShift action_65
action_115 (75) = happyShift action_66
action_115 (80) = happyShift action_67
action_115 (16) = happyGoto action_145
action_115 _ = happyFail

action_116 _ = happyReduce_88

action_117 (50) = happyShift action_144
action_117 _ = happyFail

action_118 _ = happyReduce_84

action_119 _ = happyReduce_32

action_120 (50) = happyShift action_143
action_120 _ = happyFail

action_121 (49) = happyShift action_64
action_121 (57) = happyShift action_65
action_121 (75) = happyShift action_66
action_121 (80) = happyShift action_67
action_121 (16) = happyGoto action_142
action_121 _ = happyFail

action_122 (49) = happyShift action_77
action_122 (58) = happyShift action_78
action_122 (65) = happyShift action_79
action_122 (70) = happyShift action_80
action_122 (80) = happyShift action_81
action_122 (81) = happyShift action_82
action_122 (82) = happyShift action_83
action_122 (83) = happyShift action_84
action_122 (13) = happyGoto action_141
action_122 (15) = happyGoto action_76
action_122 _ = happyFail

action_123 (49) = happyShift action_77
action_123 (58) = happyShift action_78
action_123 (65) = happyShift action_79
action_123 (70) = happyShift action_80
action_123 (80) = happyShift action_81
action_123 (81) = happyShift action_82
action_123 (82) = happyShift action_83
action_123 (83) = happyShift action_84
action_123 (13) = happyGoto action_140
action_123 (15) = happyGoto action_76
action_123 _ = happyFail

action_124 (49) = happyShift action_77
action_124 (58) = happyShift action_78
action_124 (65) = happyShift action_79
action_124 (70) = happyShift action_80
action_124 (80) = happyShift action_81
action_124 (81) = happyShift action_82
action_124 (82) = happyShift action_83
action_124 (83) = happyShift action_84
action_124 (13) = happyGoto action_138
action_124 (14) = happyGoto action_139
action_124 (15) = happyGoto action_76
action_124 _ = happyReduce_24

action_125 (78) = happyShift action_103
action_125 (20) = happyGoto action_137
action_125 _ = happyFail

action_126 _ = happyReduce_15

action_127 _ = happyReduce_75

action_128 (77) = happyShift action_136
action_128 _ = happyFail

action_129 (51) = happyShift action_135
action_129 _ = happyReduce_74

action_130 (53) = happyShift action_134
action_130 _ = happyFail

action_131 _ = happyReduce_36

action_132 (78) = happyShift action_96
action_132 (19) = happyGoto action_133
action_132 _ = happyFail

action_133 _ = happyReduce_73

action_134 (49) = happyShift action_64
action_134 (57) = happyShift action_65
action_134 (75) = happyShift action_66
action_134 (80) = happyShift action_67
action_134 (16) = happyGoto action_150
action_134 _ = happyFail

action_135 (80) = happyShift action_130
action_135 (21) = happyGoto action_149
action_135 _ = happyFail

action_136 _ = happyReduce_11

action_137 _ = happyReduce_70

action_138 _ = happyReduce_25

action_139 (75) = happyShift action_148
action_139 _ = happyFail

action_140 (63) = happyShift action_147
action_140 _ = happyFail

action_141 _ = happyReduce_18

action_142 (50) = happyShift action_146
action_142 _ = happyFail

action_143 _ = happyReduce_20

action_144 _ = happyReduce_30

action_145 _ = happyReduce_29

action_146 _ = happyReduce_21

action_147 (49) = happyShift action_77
action_147 (58) = happyShift action_78
action_147 (65) = happyShift action_79
action_147 (70) = happyShift action_80
action_147 (80) = happyShift action_81
action_147 (81) = happyShift action_82
action_147 (82) = happyShift action_83
action_147 (83) = happyShift action_84
action_147 (13) = happyGoto action_155
action_147 (15) = happyGoto action_76
action_147 _ = happyFail

action_148 (49) = happyShift action_77
action_148 (58) = happyShift action_78
action_148 (65) = happyShift action_79
action_148 (70) = happyShift action_80
action_148 (80) = happyShift action_81
action_148 (81) = happyShift action_82
action_148 (82) = happyShift action_83
action_148 (83) = happyShift action_84
action_148 (13) = happyGoto action_151
action_148 (15) = happyGoto action_76
action_148 (17) = happyGoto action_152
action_148 (35) = happyGoto action_153
action_148 (36) = happyGoto action_154
action_148 _ = happyReduce_65

action_149 _ = happyReduce_76

action_150 _ = happyReduce_38

action_151 (52) = happyShift action_159
action_151 _ = happyFail

action_152 (54) = happyShift action_158
action_152 _ = happyFail

action_153 (77) = happyShift action_157
action_153 _ = happyFail

action_154 (49) = happyShift action_77
action_154 (58) = happyShift action_78
action_154 (65) = happyShift action_79
action_154 (70) = happyShift action_80
action_154 (80) = happyShift action_81
action_154 (81) = happyShift action_82
action_154 (82) = happyShift action_83
action_154 (83) = happyShift action_84
action_154 (13) = happyGoto action_151
action_154 (15) = happyGoto action_76
action_154 (17) = happyGoto action_156
action_154 _ = happyReduce_64

action_155 _ = happyReduce_17

action_156 (54) = happyShift action_161
action_156 _ = happyFail

action_157 _ = happyReduce_19

action_158 _ = happyReduce_66

action_159 (49) = happyShift action_77
action_159 (58) = happyShift action_78
action_159 (65) = happyShift action_79
action_159 (70) = happyShift action_80
action_159 (80) = happyShift action_81
action_159 (81) = happyShift action_82
action_159 (82) = happyShift action_83
action_159 (83) = happyShift action_84
action_159 (13) = happyGoto action_160
action_159 (15) = happyGoto action_76
action_159 _ = happyFail

action_160 _ = happyReduce_34

action_161 _ = happyReduce_67

happyReduce_1 = happyReduce 10 4 happyReduction_1
happyReduction_1 (_ `HappyStk`
	(HappyAbsSyn27  happy_var_9) `HappyStk`
	(HappyAbsSyn33  happy_var_8) `HappyStk`
	(HappyAbsSyn29  happy_var_7) `HappyStk`
	(HappyAbsSyn31  happy_var_6) `HappyStk`
	(HappyAbsSyn25  happy_var_5) `HappyStk`
	(HappyAbsSyn23  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn4
		 (Module   (unTUident happy_var_2)  happy_var_4 happy_var_5 happy_var_6 happy_var_7 happy_var_8 happy_var_9
	) `HappyStk` happyRest

happyReduce_2 = happySpecReduce_2  5 happyReduction_2
happyReduction_2 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn5
		 (TypeEx   (unTUident happy_var_2)
	)
happyReduction_2 _ _  = notHappyAtAll 

happyReduce_3 = happySpecReduce_2  5 happyReduction_3
happyReduction_3 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn5
		 (VarEx   (unTLident happy_var_2)
	)
happyReduction_3 _ _  = notHappyAtAll 

happyReduce_4 = happySpecReduce_2  6 happyReduction_4
happyReduction_4 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn6
		 (ImportD   (unTUident happy_var_2)
	)
happyReduction_4 _ _  = notHappyAtAll 

happyReduce_5 = happySpecReduce_2  7 happyReduction_5
happyReduction_5 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn7
		 (CountD   (unTNumber happy_var_2)
	)
happyReduction_5 _ _  = notHappyAtAll 

happyReduce_6 = happyReduce 5 8 happyReduction_6
happyReduction_6 ((HappyAbsSyn12  happy_var_5) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn43  happy_var_3) `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn8
		 (TypeD   (unTUident happy_var_2) happy_var_3  happy_var_5
	) `HappyStk` happyRest

happyReduce_7 = happySpecReduce_3  9 happyReduction_7
happyReduction_7 (HappyAbsSyn13  happy_var_3)
	(HappyAbsSyn11  happy_var_2)
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn9
		 (VarD  (unTLident happy_var_1) happy_var_2 happy_var_3
	)
happyReduction_7 _ _ _  = notHappyAtAll 

happyReduce_8 = happySpecReduce_3  10 happyReduction_8
happyReduction_8 (HappyAbsSyn16  happy_var_3)
	(HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn10
		 (InstD   (unTUident happy_var_2) happy_var_3
	)
happyReduction_8 _ _ _  = notHappyAtAll 

happyReduce_9 = happySpecReduce_1  11 happyReduction_9
happyReduction_9 _
	 =  HappyAbsSyn11
		 (Macro
	)

happyReduce_10 = happySpecReduce_1  11 happyReduction_10
happyReduction_10 _
	 =  HappyAbsSyn11
		 (Define
	)

happyReduce_11 = happyReduce 4 12 happyReduction_11
happyReduction_11 (_ `HappyStk`
	(HappyAbsSyn41  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn12
		 (TyRecord    happy_var_3
	) `HappyStk` happyRest

happyReduce_12 = happySpecReduce_2  12 happyReduction_12
happyReduction_12 (HappyAbsSyn39  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyTagged   happy_var_2
	)
happyReduction_12 _ _  = notHappyAtAll 

happyReduce_13 = happySpecReduce_2  12 happyReduction_13
happyReduction_13 (HappyAbsSyn37  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyEnum   happy_var_2
	)
happyReduction_13 _ _  = notHappyAtAll 

happyReduce_14 = happySpecReduce_2  12 happyReduction_14
happyReduction_14 (HappyAbsSyn16  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TySyn   happy_var_2
	)
happyReduction_14 _ _  = notHappyAtAll 

happyReduce_15 = happySpecReduce_3  12 happyReduction_15
happyReduction_15 (HappyAbsSyn16  happy_var_3)
	(HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyNewtype   (unTUident happy_var_2) happy_var_3
	)
happyReduction_15 _ _ _  = notHappyAtAll 

happyReduce_16 = happySpecReduce_2  12 happyReduction_16
happyReduction_16 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyUnit   (unTUident happy_var_2)
	)
happyReduction_16 _ _  = notHappyAtAll 

happyReduce_17 = happyReduce 6 13 happyReduction_17
happyReduction_17 ((HappyAbsSyn13  happy_var_6) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn13  happy_var_4) `HappyStk`
	(HappyAbsSyn11  happy_var_3) `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (LetE   (unTLident happy_var_2) happy_var_3 happy_var_4  happy_var_6
	) `HappyStk` happyRest

happyReduce_18 = happyReduce 4 13 happyReduction_18
happyReduction_18 ((HappyAbsSyn13  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (LamE   (unTLident happy_var_2)  happy_var_4
	) `HappyStk` happyRest

happyReduce_19 = happyReduce 7 13 happyReduction_19
happyReduction_19 (_ `HappyStk`
	(HappyAbsSyn35  happy_var_6) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn14  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn13  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (SwitchE   happy_var_2  happy_var_4  happy_var_6
	) `HappyStk` happyRest

happyReduce_20 = happyReduce 4 13 happyReduction_20
happyReduction_20 (_ `HappyStk`
	(HappyAbsSyn13  happy_var_3) `HappyStk`
	(HappyAbsSyn13  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (AppE   happy_var_2 happy_var_3
	) `HappyStk` happyRest

happyReduce_21 = happyReduce 5 13 happyReduction_21
happyReduction_21 (_ `HappyStk`
	(HappyAbsSyn16  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn13  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (AscribeE   happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_22 = happySpecReduce_1  13 happyReduction_22
happyReduction_22 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn13
		 (VarE  (unTLident happy_var_1)
	)
happyReduction_22 _  = notHappyAtAll 

happyReduce_23 = happySpecReduce_1  13 happyReduction_23
happyReduction_23 (HappyAbsSyn15  happy_var_1)
	 =  HappyAbsSyn13
		 (LitE  happy_var_1
	)
happyReduction_23 _  = notHappyAtAll 

happyReduce_24 = happySpecReduce_0  14 happyReduction_24
happyReduction_24  =  HappyAbsSyn14
		 (DefaultNone
	)

happyReduce_25 = happySpecReduce_1  14 happyReduction_25
happyReduction_25 (HappyAbsSyn13  happy_var_1)
	 =  HappyAbsSyn14
		 (DefaultSome  happy_var_1
	)
happyReduction_25 _  = notHappyAtAll 

happyReduce_26 = happySpecReduce_1  15 happyReduction_26
happyReduction_26 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (CharL  (unTChar happy_var_1)
	)
happyReduction_26 _  = notHappyAtAll 

happyReduce_27 = happySpecReduce_1  15 happyReduction_27
happyReduction_27 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (StringL  (unTString happy_var_1)
	)
happyReduction_27 _  = notHappyAtAll 

happyReduce_28 = happySpecReduce_1  15 happyReduction_28
happyReduction_28 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (NmbrL  (unTNumber happy_var_1)
	)
happyReduction_28 _  = notHappyAtAll 

happyReduce_29 = happyReduce 5 16 happyReduction_29
happyReduction_29 ((HappyAbsSyn16  happy_var_5) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn47  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn16
		 (TyCxt   happy_var_2   happy_var_5
	) `HappyStk` happyRest

happyReduce_30 = happyReduce 5 16 happyReduction_30
happyReduction_30 (_ `HappyStk`
	(HappyAbsSyn16  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn16  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn16
		 (TyFun   happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_31 = happySpecReduce_1  16 happyReduction_31
happyReduction_31 _
	 =  HappyAbsSyn16
		 (TyVoid
	)

happyReduce_32 = happyReduce 4 16 happyReduction_32
happyReduction_32 (_ `HappyStk`
	(HappyAbsSyn45  happy_var_3) `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn16
		 (TyConstr   (unTUident happy_var_2) happy_var_3
	) `HappyStk` happyRest

happyReduce_33 = happySpecReduce_1  16 happyReduction_33
happyReduction_33 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn16
		 (TyVarT  (unTLident happy_var_1)
	)
happyReduction_33 _  = notHappyAtAll 

happyReduce_34 = happySpecReduce_3  17 happyReduction_34
happyReduction_34 (HappyAbsSyn13  happy_var_3)
	_
	(HappyAbsSyn13  happy_var_1)
	 =  HappyAbsSyn17
		 (SwitchAlt  happy_var_1  happy_var_3
	)
happyReduction_34 _ _ _  = notHappyAtAll 

happyReduce_35 = happySpecReduce_2  18 happyReduction_35
happyReduction_35 (HappyAbsSyn43  happy_var_2)
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn18
		 (Cxt  (unTUident happy_var_1) happy_var_2
	)
happyReduction_35 _ _  = notHappyAtAll 

happyReduce_36 = happySpecReduce_2  19 happyReduction_36
happyReduction_36 (HappyAbsSyn16  happy_var_2)
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn19
		 (ConC  (unTUident happy_var_1) happy_var_2
	)
happyReduction_36 _ _  = notHappyAtAll 

happyReduce_37 = happySpecReduce_1  20 happyReduction_37
happyReduction_37 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn20
		 (EnumC  (unTUident happy_var_1)
	)
happyReduction_37 _  = notHappyAtAll 

happyReduce_38 = happySpecReduce_3  21 happyReduction_38
happyReduction_38 (HappyAbsSyn16  happy_var_3)
	_
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn21
		 (FieldT  (unTLident happy_var_1)  happy_var_3
	)
happyReduction_38 _ _ _  = notHappyAtAll 

happyReduce_39 = happySpecReduce_1  22 happyReduction_39
happyReduction_39 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn22
		 (Var  (unTLident happy_var_1)
	)
happyReduction_39 _  = notHappyAtAll 

happyReduce_40 = happySpecReduce_1  23 happyReduction_40
happyReduction_40 (HappyAbsSyn24  happy_var_1)
	 =  HappyAbsSyn23
		 (reverse happy_var_1
	)
happyReduction_40 _  = notHappyAtAll 

happyReduce_41 = happySpecReduce_0  23 happyReduction_41
happyReduction_41  =  HappyAbsSyn23
		 ([]
	)

happyReduce_42 = happySpecReduce_2  24 happyReduction_42
happyReduction_42 _
	(HappyAbsSyn5  happy_var_1)
	 =  HappyAbsSyn24
		 ([happy_var_1]
	)
happyReduction_42 _ _  = notHappyAtAll 

happyReduce_43 = happySpecReduce_3  24 happyReduction_43
happyReduction_43 _
	(HappyAbsSyn5  happy_var_2)
	(HappyAbsSyn24  happy_var_1)
	 =  HappyAbsSyn24
		 (happy_var_2 : happy_var_1
	)
happyReduction_43 _ _ _  = notHappyAtAll 

happyReduce_44 = happySpecReduce_1  25 happyReduction_44
happyReduction_44 (HappyAbsSyn26  happy_var_1)
	 =  HappyAbsSyn25
		 (reverse happy_var_1
	)
happyReduction_44 _  = notHappyAtAll 

happyReduce_45 = happySpecReduce_0  25 happyReduction_45
happyReduction_45  =  HappyAbsSyn25
		 ([]
	)

happyReduce_46 = happySpecReduce_2  26 happyReduction_46
happyReduction_46 _
	(HappyAbsSyn6  happy_var_1)
	 =  HappyAbsSyn26
		 ([happy_var_1]
	)
happyReduction_46 _ _  = notHappyAtAll 

happyReduce_47 = happySpecReduce_3  26 happyReduction_47
happyReduction_47 _
	(HappyAbsSyn6  happy_var_2)
	(HappyAbsSyn26  happy_var_1)
	 =  HappyAbsSyn26
		 (happy_var_2 : happy_var_1
	)
happyReduction_47 _ _ _  = notHappyAtAll 

happyReduce_48 = happySpecReduce_1  27 happyReduction_48
happyReduction_48 (HappyAbsSyn28  happy_var_1)
	 =  HappyAbsSyn27
		 (reverse happy_var_1
	)
happyReduction_48 _  = notHappyAtAll 

happyReduce_49 = happySpecReduce_0  27 happyReduction_49
happyReduction_49  =  HappyAbsSyn27
		 ([]
	)

happyReduce_50 = happySpecReduce_2  28 happyReduction_50
happyReduction_50 _
	(HappyAbsSyn9  happy_var_1)
	 =  HappyAbsSyn28
		 ([happy_var_1]
	)
happyReduction_50 _ _  = notHappyAtAll 

happyReduce_51 = happySpecReduce_3  28 happyReduction_51
happyReduction_51 _
	(HappyAbsSyn9  happy_var_2)
	(HappyAbsSyn28  happy_var_1)
	 =  HappyAbsSyn28
		 (happy_var_2 : happy_var_1
	)
happyReduction_51 _ _ _  = notHappyAtAll 

happyReduce_52 = happySpecReduce_1  29 happyReduction_52
happyReduction_52 (HappyAbsSyn30  happy_var_1)
	 =  HappyAbsSyn29
		 (reverse happy_var_1
	)
happyReduction_52 _  = notHappyAtAll 

happyReduce_53 = happySpecReduce_0  29 happyReduction_53
happyReduction_53  =  HappyAbsSyn29
		 ([]
	)

happyReduce_54 = happySpecReduce_2  30 happyReduction_54
happyReduction_54 _
	(HappyAbsSyn8  happy_var_1)
	 =  HappyAbsSyn30
		 ([happy_var_1]
	)
happyReduction_54 _ _  = notHappyAtAll 

happyReduce_55 = happySpecReduce_3  30 happyReduction_55
happyReduction_55 _
	(HappyAbsSyn8  happy_var_2)
	(HappyAbsSyn30  happy_var_1)
	 =  HappyAbsSyn30
		 (happy_var_2 : happy_var_1
	)
happyReduction_55 _ _ _  = notHappyAtAll 

happyReduce_56 = happySpecReduce_1  31 happyReduction_56
happyReduction_56 (HappyAbsSyn32  happy_var_1)
	 =  HappyAbsSyn31
		 (reverse happy_var_1
	)
happyReduction_56 _  = notHappyAtAll 

happyReduce_57 = happySpecReduce_0  31 happyReduction_57
happyReduction_57  =  HappyAbsSyn31
		 ([]
	)

happyReduce_58 = happySpecReduce_2  32 happyReduction_58
happyReduction_58 _
	(HappyAbsSyn7  happy_var_1)
	 =  HappyAbsSyn32
		 ([happy_var_1]
	)
happyReduction_58 _ _  = notHappyAtAll 

happyReduce_59 = happySpecReduce_3  32 happyReduction_59
happyReduction_59 _
	(HappyAbsSyn7  happy_var_2)
	(HappyAbsSyn32  happy_var_1)
	 =  HappyAbsSyn32
		 (happy_var_2 : happy_var_1
	)
happyReduction_59 _ _ _  = notHappyAtAll 

happyReduce_60 = happySpecReduce_1  33 happyReduction_60
happyReduction_60 (HappyAbsSyn34  happy_var_1)
	 =  HappyAbsSyn33
		 (reverse happy_var_1
	)
happyReduction_60 _  = notHappyAtAll 

happyReduce_61 = happySpecReduce_0  33 happyReduction_61
happyReduction_61  =  HappyAbsSyn33
		 ([]
	)

happyReduce_62 = happySpecReduce_2  34 happyReduction_62
happyReduction_62 _
	(HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn34
		 ([happy_var_1]
	)
happyReduction_62 _ _  = notHappyAtAll 

happyReduce_63 = happySpecReduce_3  34 happyReduction_63
happyReduction_63 _
	(HappyAbsSyn10  happy_var_2)
	(HappyAbsSyn34  happy_var_1)
	 =  HappyAbsSyn34
		 (happy_var_2 : happy_var_1
	)
happyReduction_63 _ _ _  = notHappyAtAll 

happyReduce_64 = happySpecReduce_1  35 happyReduction_64
happyReduction_64 (HappyAbsSyn36  happy_var_1)
	 =  HappyAbsSyn35
		 (reverse happy_var_1
	)
happyReduction_64 _  = notHappyAtAll 

happyReduce_65 = happySpecReduce_0  35 happyReduction_65
happyReduction_65  =  HappyAbsSyn35
		 ([]
	)

happyReduce_66 = happySpecReduce_2  36 happyReduction_66
happyReduction_66 _
	(HappyAbsSyn17  happy_var_1)
	 =  HappyAbsSyn36
		 ([happy_var_1]
	)
happyReduction_66 _ _  = notHappyAtAll 

happyReduce_67 = happySpecReduce_3  36 happyReduction_67
happyReduction_67 _
	(HappyAbsSyn17  happy_var_2)
	(HappyAbsSyn36  happy_var_1)
	 =  HappyAbsSyn36
		 (happy_var_2 : happy_var_1
	)
happyReduction_67 _ _ _  = notHappyAtAll 

happyReduce_68 = happySpecReduce_1  37 happyReduction_68
happyReduction_68 (HappyAbsSyn38  happy_var_1)
	 =  HappyAbsSyn37
		 (reverse happy_var_1
	)
happyReduction_68 _  = notHappyAtAll 

happyReduce_69 = happySpecReduce_1  38 happyReduction_69
happyReduction_69 (HappyAbsSyn20  happy_var_1)
	 =  HappyAbsSyn38
		 ([happy_var_1]
	)
happyReduction_69 _  = notHappyAtAll 

happyReduce_70 = happySpecReduce_3  38 happyReduction_70
happyReduction_70 (HappyAbsSyn20  happy_var_3)
	_
	(HappyAbsSyn38  happy_var_1)
	 =  HappyAbsSyn38
		 (happy_var_3 : happy_var_1
	)
happyReduction_70 _ _ _  = notHappyAtAll 

happyReduce_71 = happySpecReduce_1  39 happyReduction_71
happyReduction_71 (HappyAbsSyn40  happy_var_1)
	 =  HappyAbsSyn39
		 (reverse happy_var_1
	)
happyReduction_71 _  = notHappyAtAll 

happyReduce_72 = happySpecReduce_1  40 happyReduction_72
happyReduction_72 (HappyAbsSyn19  happy_var_1)
	 =  HappyAbsSyn40
		 ([happy_var_1]
	)
happyReduction_72 _  = notHappyAtAll 

happyReduce_73 = happySpecReduce_3  40 happyReduction_73
happyReduction_73 (HappyAbsSyn19  happy_var_3)
	_
	(HappyAbsSyn40  happy_var_1)
	 =  HappyAbsSyn40
		 (happy_var_3 : happy_var_1
	)
happyReduction_73 _ _ _  = notHappyAtAll 

happyReduce_74 = happySpecReduce_1  41 happyReduction_74
happyReduction_74 (HappyAbsSyn42  happy_var_1)
	 =  HappyAbsSyn41
		 (reverse happy_var_1
	)
happyReduction_74 _  = notHappyAtAll 

happyReduce_75 = happySpecReduce_1  42 happyReduction_75
happyReduction_75 (HappyAbsSyn21  happy_var_1)
	 =  HappyAbsSyn42
		 ([happy_var_1]
	)
happyReduction_75 _  = notHappyAtAll 

happyReduce_76 = happySpecReduce_3  42 happyReduction_76
happyReduction_76 (HappyAbsSyn21  happy_var_3)
	_
	(HappyAbsSyn42  happy_var_1)
	 =  HappyAbsSyn42
		 (happy_var_3 : happy_var_1
	)
happyReduction_76 _ _ _  = notHappyAtAll 

happyReduce_77 = happySpecReduce_1  43 happyReduction_77
happyReduction_77 (HappyAbsSyn44  happy_var_1)
	 =  HappyAbsSyn43
		 (reverse happy_var_1
	)
happyReduction_77 _  = notHappyAtAll 

happyReduce_78 = happySpecReduce_0  43 happyReduction_78
happyReduction_78  =  HappyAbsSyn43
		 ([]
	)

happyReduce_79 = happySpecReduce_1  44 happyReduction_79
happyReduction_79 (HappyAbsSyn22  happy_var_1)
	 =  HappyAbsSyn44
		 ([happy_var_1]
	)
happyReduction_79 _  = notHappyAtAll 

happyReduce_80 = happySpecReduce_2  44 happyReduction_80
happyReduction_80 (HappyAbsSyn22  happy_var_2)
	(HappyAbsSyn44  happy_var_1)
	 =  HappyAbsSyn44
		 (happy_var_2 : happy_var_1
	)
happyReduction_80 _ _  = notHappyAtAll 

happyReduce_81 = happySpecReduce_1  45 happyReduction_81
happyReduction_81 (HappyAbsSyn46  happy_var_1)
	 =  HappyAbsSyn45
		 (reverse happy_var_1
	)
happyReduction_81 _  = notHappyAtAll 

happyReduce_82 = happySpecReduce_0  45 happyReduction_82
happyReduction_82  =  HappyAbsSyn45
		 ([]
	)

happyReduce_83 = happySpecReduce_1  46 happyReduction_83
happyReduction_83 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn46
		 ([happy_var_1]
	)
happyReduction_83 _  = notHappyAtAll 

happyReduce_84 = happySpecReduce_2  46 happyReduction_84
happyReduction_84 (HappyAbsSyn16  happy_var_2)
	(HappyAbsSyn46  happy_var_1)
	 =  HappyAbsSyn46
		 (happy_var_2 : happy_var_1
	)
happyReduction_84 _ _  = notHappyAtAll 

happyReduce_85 = happySpecReduce_1  47 happyReduction_85
happyReduction_85 (HappyAbsSyn48  happy_var_1)
	 =  HappyAbsSyn47
		 (reverse happy_var_1
	)
happyReduction_85 _  = notHappyAtAll 

happyReduce_86 = happySpecReduce_0  47 happyReduction_86
happyReduction_86  =  HappyAbsSyn47
		 ([]
	)

happyReduce_87 = happySpecReduce_1  48 happyReduction_87
happyReduction_87 (HappyAbsSyn18  happy_var_1)
	 =  HappyAbsSyn48
		 ([happy_var_1]
	)
happyReduction_87 _  = notHappyAtAll 

happyReduce_88 = happySpecReduce_3  48 happyReduction_88
happyReduction_88 (HappyAbsSyn18  happy_var_3)
	_
	(HappyAbsSyn48  happy_var_1)
	 =  HappyAbsSyn48
		 (happy_var_3 : happy_var_1
	)
happyReduction_88 _ _ _  = notHappyAtAll 

happyNewToken action sts stk [] =
	action 84 84 notHappyAtAll (HappyState action) sts stk []

happyNewToken action sts stk (tk:tks) =
	let cont i = action i i tk (HappyState action) sts stk tks in
	case tk of {
	TSymbol _ "(" -> cont 49;
	TSymbol _ ")" -> cont 50;
	TSymbol _ "," -> cont 51;
	TSymbol _ "->" -> cont 52;
	TSymbol _ "::" -> cont 53;
	TSymbol _ ";" -> cont 54;
	TSymbol _ "=" -> cont 55;
	TSymbol _ "=>" -> cont 56;
	TSymbol _ "VoidT" -> cont 57;
	TSymbol _ "\\" -> cont 58;
	TSymbol _ "count" -> cont 59;
	TSymbol _ "enum" -> cont 60;
	TSymbol _ "export" -> cont 61;
	TSymbol _ "import" -> cont 62;
	TSymbol _ "in" -> cont 63;
	TSymbol _ "instance" -> cont 64;
	TSymbol _ "let" -> cont 65;
	TSymbol _ "module" -> cont 66;
	TSymbol _ "newtype" -> cont 67;
	TSymbol _ "of" -> cont 68;
	TSymbol _ "record" -> cont 69;
	TSymbol _ "switch" -> cont 70;
	TSymbol _ "synonym" -> cont 71;
	TSymbol _ "tagged" -> cont 72;
	TSymbol _ "type" -> cont 73;
	TSymbol _ "unit" -> cont 74;
	TSymbol _ "{" -> cont 75;
	TSymbol _ "|" -> cont 76;
	TSymbol _ "}" -> cont 77;
	TUident _ _ -> cont 78;
	TUsym _ _ -> cont 79;
	TLident _ _ -> cont 80;
	TString _ _ -> cont 81;
	TChar _ _ -> cont 82;
	TNumber _ _ -> cont 83;
	_ -> happyError' (tk:tks)
	}

happyError_ tk tks = happyError' (tk:tks)

newtype HappyIdentity a = HappyIdentity a
happyIdentity = HappyIdentity
happyRunIdentity (HappyIdentity a) = a

instance Monad HappyIdentity where
    return = HappyIdentity
    (HappyIdentity p) >>= q = q p

happyThen :: () => HappyIdentity a -> (a -> HappyIdentity b) -> HappyIdentity b
happyThen = (>>=)
happyReturn :: () => a -> HappyIdentity a
happyReturn = (return)
happyThen1 m k tks = (>>=) m (\a -> k a tks)
happyReturn1 :: () => a -> b -> HappyIdentity a
happyReturn1 = \a tks -> (return) a
happyError' :: () => [((Token Point))] -> HappyIdentity a
happyError' = HappyIdentity . happyError

grmParse tks = happyRunIdentity happySomeParser where
  happySomeParser = happyThen (happyParse action_0 tks) (\x -> case x of {HappyAbsSyn4 z -> happyReturn z; _other -> notHappyAtAll })

happySeq = happyDontSeq



{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "<built-in>" #-}
{-# LINE 1 "<command-line>" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
-- Id: GenericTemplate.hs,v 1.26 2005/01/14 14:47:22 simonmar Exp 

{-# LINE 30 "templates/GenericTemplate.hs" #-}








{-# LINE 51 "templates/GenericTemplate.hs" #-}

{-# LINE 61 "templates/GenericTemplate.hs" #-}

{-# LINE 70 "templates/GenericTemplate.hs" #-}

infixr 9 `HappyStk`
data HappyStk a = HappyStk a (HappyStk a)

-----------------------------------------------------------------------------
-- starting the parse

happyParse start_state = happyNewToken start_state notHappyAtAll notHappyAtAll

-----------------------------------------------------------------------------
-- Accepting the parse

-- If the current token is (1), it means we've just accepted a partial
-- parse (a %partial parser).  We must ignore the saved token on the top of
-- the stack in this case.
happyAccept (1) tk st sts (_ `HappyStk` ans `HappyStk` _) =
	happyReturn1 ans
happyAccept j tk st sts (HappyStk ans _) = 
	 (happyReturn1 ans)

-----------------------------------------------------------------------------
-- Arrays only: do the next action

{-# LINE 148 "templates/GenericTemplate.hs" #-}

-----------------------------------------------------------------------------
-- HappyState data type (not arrays)



newtype HappyState b c = HappyState
        (Int ->                    -- token number
         Int ->                    -- token number (yes, again)
         b ->                           -- token semantic value
         HappyState b c ->              -- current state
         [HappyState b c] ->            -- state stack
         c)



-----------------------------------------------------------------------------
-- Shifting a token

happyShift new_state (1) tk st sts stk@(x `HappyStk` _) =
     let (i) = (case x of { HappyErrorToken (i) -> i }) in
--     trace "shifting the error token" $
     new_state i i tk (HappyState (new_state)) ((st):(sts)) (stk)

happyShift new_state i tk st sts stk =
     happyNewToken new_state ((st):(sts)) ((HappyTerminal (tk))`HappyStk`stk)

-- happyReduce is specialised for the common cases.

happySpecReduce_0 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_0 nt fn j tk st@((HappyState (action))) sts stk
     = action nt j tk st ((st):(sts)) (fn `HappyStk` stk)

happySpecReduce_1 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_1 nt fn j tk _ sts@(((st@(HappyState (action))):(_))) (v1`HappyStk`stk')
     = let r = fn v1 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_2 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_2 nt fn j tk _ ((_):(sts@(((st@(HappyState (action))):(_))))) (v1`HappyStk`v2`HappyStk`stk')
     = let r = fn v1 v2 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_3 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_3 nt fn j tk _ ((_):(((_):(sts@(((st@(HappyState (action))):(_))))))) (v1`HappyStk`v2`HappyStk`v3`HappyStk`stk')
     = let r = fn v1 v2 v3 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happyReduce k i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyReduce k nt fn j tk st sts stk
     = case happyDrop (k - ((1) :: Int)) sts of
	 sts1@(((st1@(HappyState (action))):(_))) ->
        	let r = fn stk in  -- it doesn't hurt to always seq here...
       		happyDoSeq r (action nt j tk st1 sts1 r)

happyMonadReduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonadReduce k nt fn j tk st sts stk =
        happyThen1 (fn stk tk) (\r -> action nt j tk st1 sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk

happyMonad2Reduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonad2Reduce k nt fn j tk st sts stk =
       happyThen1 (fn stk tk) (\r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk





             new_state = action


happyDrop (0) l = l
happyDrop n ((_):(t)) = happyDrop (n - ((1) :: Int)) t

happyDropStk (0) l = l
happyDropStk n (x `HappyStk` xs) = happyDropStk (n - ((1)::Int)) xs

-----------------------------------------------------------------------------
-- Moving to a new state after a reduction

{-# LINE 246 "templates/GenericTemplate.hs" #-}
happyGoto action j tk st = action j j tk (HappyState action)


-----------------------------------------------------------------------------
-- Error recovery ((1) is the error token)

-- parse error if we are in recovery and we fail again
happyFail  (1) tk old_st _ stk =
--	trace "failing" $ 
    	happyError_ tk

{-  We don't need state discarding for our restricted implementation of
    "error".  In fact, it can cause some bogus parses, so I've disabled it
    for now --SDM

-- discard a state
happyFail  (1) tk old_st (((HappyState (action))):(sts)) 
						(saved_tok `HappyStk` _ `HappyStk` stk) =
--	trace ("discarding state, depth " ++ show (length stk))  $
	action (1) (1) tk (HappyState (action)) sts ((saved_tok`HappyStk`stk))
-}

-- Enter error recovery: generate an error token,
--                       save the old token and carry on.
happyFail  i tk (HappyState (action)) sts stk =
--      trace "entering error recovery" $
	action (1) (1) tk (HappyState (action)) sts ( (HappyErrorToken (i)) `HappyStk` stk)

-- Internal happy errors:

notHappyAtAll :: a
notHappyAtAll = error "Internal Happy error\n"

-----------------------------------------------------------------------------
-- Hack to get the typechecker to accept our action functions







-----------------------------------------------------------------------------
-- Seq-ing.  If the --strict flag is given, then Happy emits 
--	happySeq = happyDoSeq
-- otherwise it emits
-- 	happySeq = happyDontSeq

happyDoSeq, happyDontSeq :: a -> b -> b
happyDoSeq   a b = a `seq` b
happyDontSeq a b = b

-----------------------------------------------------------------------------
-- Don't inline any functions from the template.  GHC has a nasty habit
-- of deciding to inline happyGoto everywhere, which increases the size of
-- the generated parser quite a bit.

{-# LINE 311 "templates/GenericTemplate.hs" #-}
{-# NOINLINE happyShift #-}
{-# NOINLINE happySpecReduce_0 #-}
{-# NOINLINE happySpecReduce_1 #-}
{-# NOINLINE happySpecReduce_2 #-}
{-# NOINLINE happySpecReduce_3 #-}
{-# NOINLINE happyReduce #-}
{-# NOINLINE happyMonadReduce #-}
{-# NOINLINE happyGoto #-}
{-# NOINLINE happyFail #-}

-- end of Happy Template.
