{-# OPTIONS_GHC -w #-}
{-# OPTIONS -w #-}
-- Haskell module generated by grm *** DO NOT EDIT ***


module Language.Pir.Par where
import Grm.Prims
import Grm.Lex
import Language.Pir.Abs

-- parser produced by Happy Version 1.18.6

data HappyAbsSyn t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40
	= HappyTerminal ((Token Point))
	| HappyErrorToken Int
	| HappyAbsSyn4 t4
	| HappyAbsSyn5 t5
	| HappyAbsSyn6 t6
	| HappyAbsSyn7 t7
	| HappyAbsSyn8 t8
	| HappyAbsSyn9 t9
	| HappyAbsSyn10 t10
	| HappyAbsSyn11 t11
	| HappyAbsSyn12 t12
	| HappyAbsSyn13 t13
	| HappyAbsSyn14 t14
	| HappyAbsSyn15 t15
	| HappyAbsSyn16 t16
	| HappyAbsSyn17 t17
	| HappyAbsSyn18 t18
	| HappyAbsSyn19 t19
	| HappyAbsSyn20 t20
	| HappyAbsSyn21 t21
	| HappyAbsSyn22 t22
	| HappyAbsSyn23 t23
	| HappyAbsSyn24 t24
	| HappyAbsSyn25 t25
	| HappyAbsSyn26 t26
	| HappyAbsSyn27 t27
	| HappyAbsSyn28 t28
	| HappyAbsSyn29 t29
	| HappyAbsSyn30 t30
	| HappyAbsSyn31 t31
	| HappyAbsSyn32 t32
	| HappyAbsSyn33 t33
	| HappyAbsSyn34 t34
	| HappyAbsSyn35 t35
	| HappyAbsSyn36 t36
	| HappyAbsSyn37 t37
	| HappyAbsSyn38 t38
	| HappyAbsSyn39 t39
	| HappyAbsSyn40 t40

action_0 (57) = happyShift action_2
action_0 (4) = happyGoto action_3
action_0 _ = happyFail

action_1 (57) = happyShift action_2
action_1 _ = happyFail

action_2 (68) = happyShift action_4
action_2 _ = happyFail

action_3 (74) = happyAccept
action_3 _ = happyFail

action_4 (55) = happyShift action_8
action_4 (5) = happyGoto action_5
action_4 (39) = happyGoto action_6
action_4 (40) = happyGoto action_7
action_4 _ = happyReduce_70

action_5 (47) = happyShift action_15
action_5 _ = happyFail

action_6 (52) = happyShift action_14
action_6 (6) = happyGoto action_11
action_6 (37) = happyGoto action_12
action_6 (38) = happyGoto action_13
action_6 _ = happyReduce_66

action_7 (55) = happyShift action_8
action_7 (5) = happyGoto action_10
action_7 _ = happyReduce_69

action_8 (68) = happyShift action_9
action_8 _ = happyFail

action_9 _ = happyReduce_2

action_10 (47) = happyShift action_20
action_10 _ = happyFail

action_11 (47) = happyShift action_19
action_11 _ = happyFail

action_12 _ = happyReduce_1

action_13 (52) = happyShift action_14
action_13 (6) = happyGoto action_18
action_13 _ = happyReduce_65

action_14 (68) = happyShift action_17
action_14 (17) = happyGoto action_16
action_14 _ = happyFail

action_15 _ = happyReduce_71

action_16 (70) = happyShift action_23
action_16 _ = happyFail

action_17 (41) = happyShift action_22
action_17 _ = happyFail

action_18 (47) = happyShift action_21
action_18 _ = happyFail

action_19 _ = happyReduce_67

action_20 _ = happyReduce_72

action_21 _ = happyReduce_68

action_22 (68) = happyShift action_17
action_22 (17) = happyGoto action_25
action_22 (25) = happyGoto action_26
action_22 (26) = happyGoto action_27
action_22 _ = happyReduce_45

action_23 (41) = happyShift action_24
action_23 _ = happyFail

action_24 (70) = happyShift action_33
action_24 (13) = happyGoto action_30
action_24 (31) = happyGoto action_31
action_24 (32) = happyGoto action_32
action_24 _ = happyFail

action_25 _ = happyReduce_46

action_26 (42) = happyShift action_29
action_26 _ = happyFail

action_27 (43) = happyShift action_28
action_27 _ = happyReduce_44

action_28 (68) = happyShift action_17
action_28 (17) = happyGoto action_37
action_28 _ = happyFail

action_29 _ = happyReduce_33

action_30 _ = happyReduce_55

action_31 (42) = happyShift action_36
action_31 _ = happyFail

action_32 (43) = happyShift action_35
action_32 _ = happyReduce_54

action_33 (45) = happyShift action_34
action_33 _ = happyFail

action_34 (68) = happyShift action_17
action_34 (17) = happyGoto action_40
action_34 _ = happyFail

action_35 (70) = happyShift action_33
action_35 (13) = happyGoto action_39
action_35 _ = happyFail

action_36 (48) = happyShift action_38
action_36 _ = happyFail

action_37 _ = happyReduce_47

action_38 (65) = happyShift action_41
action_38 _ = happyFail

action_39 _ = happyReduce_56

action_40 _ = happyReduce_29

action_41 (50) = happyShift action_46
action_41 (54) = happyShift action_47
action_41 (58) = happyShift action_48
action_41 (60) = happyShift action_49
action_41 (61) = happyShift action_50
action_41 (63) = happyShift action_51
action_41 (64) = happyShift action_52
action_41 (70) = happyShift action_33
action_41 (7) = happyGoto action_42
action_41 (13) = happyGoto action_43
action_41 (35) = happyGoto action_44
action_41 (36) = happyGoto action_45
action_41 _ = happyReduce_62

action_42 (47) = happyShift action_70
action_42 _ = happyFail

action_43 (46) = happyShift action_68
action_43 (48) = happyShift action_69
action_43 _ = happyFail

action_44 (67) = happyShift action_67
action_44 _ = happyFail

action_45 (50) = happyShift action_46
action_45 (54) = happyShift action_47
action_45 (58) = happyShift action_48
action_45 (60) = happyShift action_49
action_45 (61) = happyShift action_50
action_45 (63) = happyShift action_51
action_45 (64) = happyShift action_52
action_45 (70) = happyShift action_33
action_45 (7) = happyGoto action_66
action_45 (13) = happyGoto action_43
action_45 _ = happyReduce_61

action_46 (70) = happyShift action_33
action_46 (13) = happyGoto action_65
action_46 _ = happyFail

action_47 (68) = happyShift action_58
action_47 (70) = happyShift action_33
action_47 (71) = happyShift action_59
action_47 (72) = happyShift action_60
action_47 (73) = happyShift action_61
action_47 (9) = happyGoto action_64
action_47 (11) = happyGoto action_55
action_47 (13) = happyGoto action_56
action_47 (14) = happyGoto action_57
action_47 _ = happyReduce_25

action_48 _ = happyReduce_12

action_49 (68) = happyShift action_58
action_49 (70) = happyShift action_33
action_49 (71) = happyShift action_59
action_49 (72) = happyShift action_60
action_49 (73) = happyShift action_61
action_49 (9) = happyGoto action_63
action_49 (11) = happyGoto action_55
action_49 (13) = happyGoto action_56
action_49 (14) = happyGoto action_57
action_49 _ = happyReduce_25

action_50 (68) = happyShift action_58
action_50 (70) = happyShift action_33
action_50 (71) = happyShift action_59
action_50 (72) = happyShift action_60
action_50 (73) = happyShift action_61
action_50 (9) = happyGoto action_62
action_50 (11) = happyGoto action_55
action_50 (13) = happyGoto action_56
action_50 (14) = happyGoto action_57
action_50 _ = happyReduce_25

action_51 (68) = happyShift action_58
action_51 (70) = happyShift action_33
action_51 (71) = happyShift action_59
action_51 (72) = happyShift action_60
action_51 (73) = happyShift action_61
action_51 (9) = happyGoto action_54
action_51 (11) = happyGoto action_55
action_51 (13) = happyGoto action_56
action_51 (14) = happyGoto action_57
action_51 _ = happyReduce_25

action_52 (65) = happyShift action_53
action_52 _ = happyFail

action_53 (50) = happyShift action_46
action_53 (54) = happyShift action_47
action_53 (58) = happyShift action_48
action_53 (60) = happyShift action_49
action_53 (61) = happyShift action_50
action_53 (63) = happyShift action_51
action_53 (64) = happyShift action_52
action_53 (70) = happyShift action_33
action_53 (7) = happyGoto action_42
action_53 (13) = happyGoto action_43
action_53 (35) = happyGoto action_84
action_53 (36) = happyGoto action_45
action_53 _ = happyReduce_62

action_54 (65) = happyShift action_83
action_54 _ = happyFail

action_55 (45) = happyShift action_82
action_55 _ = happyFail

action_56 _ = happyReduce_19

action_57 _ = happyReduce_18

action_58 _ = happyReduce_24

action_59 _ = happyReduce_21

action_60 _ = happyReduce_23

action_61 _ = happyReduce_22

action_62 (65) = happyShift action_81
action_62 _ = happyFail

action_63 _ = happyReduce_11

action_64 (65) = happyShift action_80
action_64 _ = happyFail

action_65 (41) = happyShift action_79
action_65 _ = happyFail

action_66 (47) = happyShift action_78
action_66 _ = happyFail

action_67 _ = happyReduce_3

action_68 (68) = happyShift action_58
action_68 (70) = happyShift action_33
action_68 (71) = happyShift action_59
action_68 (72) = happyShift action_60
action_68 (73) = happyShift action_61
action_68 (9) = happyGoto action_77
action_68 (11) = happyGoto action_55
action_68 (13) = happyGoto action_56
action_68 (14) = happyGoto action_57
action_68 _ = happyReduce_25

action_69 (49) = happyShift action_74
action_69 (51) = happyShift action_75
action_69 (56) = happyShift action_76
action_69 (68) = happyShift action_58
action_69 (70) = happyShift action_33
action_69 (71) = happyShift action_59
action_69 (72) = happyShift action_60
action_69 (73) = happyShift action_61
action_69 (8) = happyGoto action_71
action_69 (9) = happyGoto action_72
action_69 (11) = happyGoto action_55
action_69 (13) = happyGoto action_73
action_69 (14) = happyGoto action_57
action_69 _ = happyReduce_25

action_70 _ = happyReduce_63

action_71 _ = happyReduce_4

action_72 _ = happyReduce_17

action_73 (41) = happyShift action_96
action_73 _ = happyReduce_19

action_74 (68) = happyShift action_17
action_74 (17) = happyGoto action_95
action_74 _ = happyFail

action_75 (70) = happyShift action_33
action_75 (13) = happyGoto action_94
action_75 _ = happyFail

action_76 (41) = happyShift action_93
action_76 _ = happyFail

action_77 _ = happyReduce_5

action_78 _ = happyReduce_64

action_79 (68) = happyShift action_58
action_79 (70) = happyShift action_33
action_79 (71) = happyShift action_59
action_79 (72) = happyShift action_60
action_79 (73) = happyShift action_61
action_79 (9) = happyGoto action_90
action_79 (11) = happyGoto action_55
action_79 (13) = happyGoto action_56
action_79 (14) = happyGoto action_57
action_79 (29) = happyGoto action_91
action_79 (30) = happyGoto action_92
action_79 _ = happyReduce_25

action_80 (50) = happyShift action_46
action_80 (54) = happyShift action_47
action_80 (58) = happyShift action_48
action_80 (60) = happyShift action_49
action_80 (61) = happyShift action_50
action_80 (63) = happyShift action_51
action_80 (64) = happyShift action_52
action_80 (70) = happyShift action_33
action_80 (7) = happyGoto action_42
action_80 (13) = happyGoto action_43
action_80 (35) = happyGoto action_89
action_80 (36) = happyGoto action_45
action_80 _ = happyReduce_62

action_81 (50) = happyShift action_46
action_81 (54) = happyShift action_47
action_81 (58) = happyShift action_48
action_81 (60) = happyShift action_49
action_81 (61) = happyShift action_50
action_81 (63) = happyShift action_51
action_81 (64) = happyShift action_52
action_81 (70) = happyShift action_33
action_81 (7) = happyGoto action_42
action_81 (13) = happyGoto action_43
action_81 (35) = happyGoto action_88
action_81 (36) = happyGoto action_45
action_81 _ = happyReduce_62

action_82 (68) = happyShift action_17
action_82 (17) = happyGoto action_87
action_82 _ = happyFail

action_83 (50) = happyShift action_46
action_83 (54) = happyShift action_47
action_83 (58) = happyShift action_48
action_83 (60) = happyShift action_49
action_83 (61) = happyShift action_50
action_83 (63) = happyShift action_51
action_83 (64) = happyShift action_52
action_83 (70) = happyShift action_33
action_83 (7) = happyGoto action_42
action_83 (13) = happyGoto action_43
action_83 (35) = happyGoto action_86
action_83 (36) = happyGoto action_45
action_83 _ = happyReduce_62

action_84 (67) = happyShift action_85
action_84 _ = happyFail

action_85 (68) = happyShift action_58
action_85 (70) = happyShift action_33
action_85 (71) = happyShift action_59
action_85 (72) = happyShift action_60
action_85 (73) = happyShift action_61
action_85 (9) = happyGoto action_105
action_85 (11) = happyGoto action_55
action_85 (13) = happyGoto action_56
action_85 (14) = happyGoto action_57
action_85 _ = happyReduce_25

action_86 (67) = happyShift action_104
action_86 _ = happyFail

action_87 _ = happyReduce_30

action_88 (67) = happyShift action_103
action_88 _ = happyFail

action_89 (67) = happyShift action_102
action_89 _ = happyFail

action_90 _ = happyReduce_52

action_91 (42) = happyShift action_101
action_91 _ = happyFail

action_92 (43) = happyShift action_100
action_92 _ = happyReduce_51

action_93 (70) = happyShift action_33
action_93 (13) = happyGoto action_99
action_93 _ = happyFail

action_94 (68) = happyShift action_17
action_94 (17) = happyGoto action_98
action_94 _ = happyFail

action_95 _ = happyReduce_15

action_96 (68) = happyShift action_58
action_96 (70) = happyShift action_33
action_96 (71) = happyShift action_59
action_96 (72) = happyShift action_60
action_96 (73) = happyShift action_61
action_96 (9) = happyGoto action_90
action_96 (11) = happyGoto action_55
action_96 (13) = happyGoto action_56
action_96 (14) = happyGoto action_57
action_96 (29) = happyGoto action_97
action_96 (30) = happyGoto action_92
action_96 _ = happyReduce_25

action_97 (42) = happyShift action_111
action_97 _ = happyFail

action_98 _ = happyReduce_14

action_99 (42) = happyShift action_110
action_99 _ = happyFail

action_100 (68) = happyShift action_58
action_100 (70) = happyShift action_33
action_100 (71) = happyShift action_59
action_100 (72) = happyShift action_60
action_100 (73) = happyShift action_61
action_100 (9) = happyGoto action_109
action_100 (11) = happyGoto action_55
action_100 (13) = happyGoto action_56
action_100 (14) = happyGoto action_57
action_100 _ = happyReduce_25

action_101 _ = happyReduce_6

action_102 (65) = happyShift action_108
action_102 _ = happyFail

action_103 (65) = happyShift action_107
action_103 _ = happyFail

action_104 _ = happyReduce_9

action_105 (65) = happyShift action_106
action_105 _ = happyFail

action_106 (50) = happyShift action_46
action_106 (54) = happyShift action_47
action_106 (58) = happyShift action_48
action_106 (60) = happyShift action_49
action_106 (61) = happyShift action_50
action_106 (63) = happyShift action_51
action_106 (64) = happyShift action_52
action_106 (70) = happyShift action_33
action_106 (7) = happyGoto action_42
action_106 (13) = happyGoto action_43
action_106 (35) = happyGoto action_117
action_106 (36) = happyGoto action_45
action_106 _ = happyReduce_62

action_107 (67) = happyReduce_58
action_107 (68) = happyShift action_58
action_107 (71) = happyShift action_59
action_107 (72) = happyShift action_60
action_107 (73) = happyShift action_61
action_107 (10) = happyGoto action_113
action_107 (11) = happyGoto action_55
action_107 (14) = happyGoto action_114
action_107 (33) = happyGoto action_115
action_107 (34) = happyGoto action_116
action_107 _ = happyReduce_25

action_108 (50) = happyShift action_46
action_108 (54) = happyShift action_47
action_108 (58) = happyShift action_48
action_108 (60) = happyShift action_49
action_108 (61) = happyShift action_50
action_108 (63) = happyShift action_51
action_108 (64) = happyShift action_52
action_108 (70) = happyShift action_33
action_108 (7) = happyGoto action_42
action_108 (13) = happyGoto action_43
action_108 (35) = happyGoto action_112
action_108 (36) = happyGoto action_45
action_108 _ = happyReduce_62

action_109 _ = happyReduce_53

action_110 _ = happyReduce_16

action_111 _ = happyReduce_13

action_112 (67) = happyShift action_123
action_112 _ = happyFail

action_113 (47) = happyShift action_122
action_113 _ = happyFail

action_114 (44) = happyShift action_121
action_114 _ = happyFail

action_115 (67) = happyShift action_120
action_115 _ = happyFail

action_116 (67) = happyReduce_57
action_116 (68) = happyShift action_58
action_116 (71) = happyShift action_59
action_116 (72) = happyShift action_60
action_116 (73) = happyShift action_61
action_116 (10) = happyGoto action_119
action_116 (11) = happyGoto action_55
action_116 (14) = happyGoto action_114
action_116 _ = happyReduce_25

action_117 (67) = happyShift action_118
action_117 _ = happyFail

action_118 _ = happyReduce_10

action_119 (47) = happyShift action_125
action_119 _ = happyFail

action_120 _ = happyReduce_7

action_121 (65) = happyShift action_124
action_121 _ = happyFail

action_122 _ = happyReduce_59

action_123 _ = happyReduce_8

action_124 (50) = happyShift action_46
action_124 (54) = happyShift action_47
action_124 (58) = happyShift action_48
action_124 (60) = happyShift action_49
action_124 (61) = happyShift action_50
action_124 (63) = happyShift action_51
action_124 (64) = happyShift action_52
action_124 (70) = happyShift action_33
action_124 (7) = happyGoto action_42
action_124 (13) = happyGoto action_43
action_124 (35) = happyGoto action_126
action_124 (36) = happyGoto action_45
action_124 _ = happyReduce_62

action_125 _ = happyReduce_60

action_126 (67) = happyShift action_127
action_126 _ = happyFail

action_127 _ = happyReduce_20

happyReduce_1 = happyReduce 4 4 happyReduction_1
happyReduction_1 ((HappyAbsSyn37  happy_var_4) `HappyStk`
	(HappyAbsSyn39  happy_var_3) `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn4
		 (Module   (unTUident happy_var_2) happy_var_3 happy_var_4
	) `HappyStk` happyRest

happyReduce_2 = happySpecReduce_2  5 happyReduction_2
happyReduction_2 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn5
		 (Import   (unTUident happy_var_2)
	)
happyReduction_2 _ _  = notHappyAtAll 

happyReduce_3 = happyReduce 10 6 happyReduction_3
happyReduction_3 (_ `HappyStk`
	(HappyAbsSyn35  happy_var_9) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn31  happy_var_5) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_3) `HappyStk`
	(HappyAbsSyn17  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn6
		 (Define   happy_var_2 (unTLident happy_var_3)  happy_var_5    happy_var_9
	) `HappyStk` happyRest

happyReduce_4 = happySpecReduce_3  7 happyReduction_4
happyReduction_4 (HappyAbsSyn8  happy_var_3)
	_
	(HappyAbsSyn13  happy_var_1)
	 =  HappyAbsSyn7
		 (LetS  happy_var_1  happy_var_3
	)
happyReduction_4 _ _ _  = notHappyAtAll 

happyReduce_5 = happySpecReduce_3  7 happyReduction_5
happyReduction_5 (HappyAbsSyn9  happy_var_3)
	_
	(HappyAbsSyn13  happy_var_1)
	 =  HappyAbsSyn7
		 (StoreS  happy_var_1  happy_var_3
	)
happyReduction_5 _ _ _  = notHappyAtAll 

happyReduce_6 = happyReduce 5 7 happyReduction_6
happyReduction_6 (_ `HappyStk`
	(HappyAbsSyn29  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn13  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (CallS   happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_7 = happyReduce 8 7 happyReduction_7
happyReduction_7 (_ `HappyStk`
	(HappyAbsSyn33  happy_var_7) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn35  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn9  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (SwitchS   happy_var_2  happy_var_4   happy_var_7
	) `HappyStk` happyRest

happyReduce_8 = happyReduce 8 7 happyReduction_8
happyReduction_8 (_ `HappyStk`
	(HappyAbsSyn35  happy_var_7) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn35  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn9  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (IfS   happy_var_2  happy_var_4   happy_var_7
	) `HappyStk` happyRest

happyReduce_9 = happyReduce 5 7 happyReduction_9
happyReduction_9 (_ `HappyStk`
	(HappyAbsSyn35  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn9  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (WhenS   happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_10 = happyReduce 8 7 happyReduction_10
happyReduction_10 (_ `HappyStk`
	(HappyAbsSyn35  happy_var_7) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn9  happy_var_5) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn35  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (WhileS    happy_var_3  happy_var_5  happy_var_7
	) `HappyStk` happyRest

happyReduce_11 = happySpecReduce_2  7 happyReduction_11
happyReduction_11 (HappyAbsSyn9  happy_var_2)
	_
	 =  HappyAbsSyn7
		 (ReturnS   happy_var_2
	)
happyReduction_11 _ _  = notHappyAtAll 

happyReduce_12 = happySpecReduce_1  7 happyReduction_12
happyReduction_12 _
	 =  HappyAbsSyn7
		 (NoOpS
	)

happyReduce_13 = happyReduce 4 8 happyReduction_13
happyReduction_13 (_ `HappyStk`
	(HappyAbsSyn29  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn13  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn8
		 (CallE  happy_var_1  happy_var_3
	) `HappyStk` happyRest

happyReduce_14 = happySpecReduce_3  8 happyReduction_14
happyReduction_14 (HappyAbsSyn17  happy_var_3)
	(HappyAbsSyn13  happy_var_2)
	_
	 =  HappyAbsSyn8
		 (CastE   happy_var_2 happy_var_3
	)
happyReduction_14 _ _ _  = notHappyAtAll 

happyReduce_15 = happySpecReduce_2  8 happyReduction_15
happyReduction_15 (HappyAbsSyn17  happy_var_2)
	_
	 =  HappyAbsSyn8
		 (AllocaE   happy_var_2
	)
happyReduction_15 _ _  = notHappyAtAll 

happyReduce_16 = happyReduce 4 8 happyReduction_16
happyReduction_16 (_ `HappyStk`
	(HappyAbsSyn13  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn8
		 (LoadE    happy_var_3
	) `HappyStk` happyRest

happyReduce_17 = happySpecReduce_1  8 happyReduction_17
happyReduction_17 (HappyAbsSyn9  happy_var_1)
	 =  HappyAbsSyn8
		 (AtomE  happy_var_1
	)
happyReduction_17 _  = notHappyAtAll 

happyReduce_18 = happySpecReduce_1  9 happyReduction_18
happyReduction_18 (HappyAbsSyn14  happy_var_1)
	 =  HappyAbsSyn9
		 (LitA  happy_var_1
	)
happyReduction_18 _  = notHappyAtAll 

happyReduce_19 = happySpecReduce_1  9 happyReduction_19
happyReduction_19 (HappyAbsSyn13  happy_var_1)
	 =  HappyAbsSyn9
		 (VarA  happy_var_1
	)
happyReduction_19 _  = notHappyAtAll 

happyReduce_20 = happyReduce 5 10 happyReduction_20
happyReduction_20 (_ `HappyStk`
	(HappyAbsSyn35  happy_var_4) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn14  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn10
		 (SwitchAlt  happy_var_1   happy_var_4
	) `HappyStk` happyRest

happyReduce_21 = happySpecReduce_1  11 happyReduction_21
happyReduction_21 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn11
		 (StringL  (unTString happy_var_1)
	)
happyReduction_21 _  = notHappyAtAll 

happyReduce_22 = happySpecReduce_1  11 happyReduction_22
happyReduction_22 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn11
		 (NmbrL  (unTNumber happy_var_1)
	)
happyReduction_22 _  = notHappyAtAll 

happyReduce_23 = happySpecReduce_1  11 happyReduction_23
happyReduction_23 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn11
		 (CharL  (unTChar happy_var_1)
	)
happyReduction_23 _  = notHappyAtAll 

happyReduce_24 = happySpecReduce_1  11 happyReduction_24
happyReduction_24 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn11
		 (EnumL  (unTUident happy_var_1)
	)
happyReduction_24 _  = notHappyAtAll 

happyReduce_25 = happySpecReduce_0  11 happyReduction_25
happyReduction_25  =  HappyAbsSyn11
		 (VoidL
	)

happyReduce_26 = happySpecReduce_2  12 happyReduction_26
happyReduction_26 (HappyAbsSyn23  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyEnum   happy_var_2
	)
happyReduction_26 _ _  = notHappyAtAll 

happyReduce_27 = happyReduce 4 12 happyReduction_27
happyReduction_27 (_ `HappyStk`
	(HappyAbsSyn21  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn12
		 (TyRecord    happy_var_3
	) `HappyStk` happyRest

happyReduce_28 = happySpecReduce_2  12 happyReduction_28
happyReduction_28 (HappyAbsSyn19  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (TyTagged   happy_var_2
	)
happyReduction_28 _ _  = notHappyAtAll 

happyReduce_29 = happySpecReduce_3  13 happyReduction_29
happyReduction_29 (HappyAbsSyn17  happy_var_3)
	_
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn13
		 (TVar  (unTLident happy_var_1)  happy_var_3
	)
happyReduction_29 _ _ _  = notHappyAtAll 

happyReduce_30 = happySpecReduce_3  14 happyReduction_30
happyReduction_30 (HappyAbsSyn17  happy_var_3)
	_
	(HappyAbsSyn11  happy_var_1)
	 =  HappyAbsSyn14
		 (TLit  happy_var_1  happy_var_3
	)
happyReduction_30 _ _ _  = notHappyAtAll 

happyReduce_31 = happySpecReduce_3  15 happyReduction_31
happyReduction_31 (HappyAbsSyn17  happy_var_3)
	_
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (FieldT  (unTUident happy_var_1)  happy_var_3
	)
happyReduction_31 _ _ _  = notHappyAtAll 

happyReduce_32 = happySpecReduce_2  16 happyReduction_32
happyReduction_32 (HappyAbsSyn17  happy_var_2)
	(HappyTerminal happy_var_1)
	 =  HappyAbsSyn16
		 (ConC  (unTUident happy_var_1) happy_var_2
	)
happyReduction_32 _ _  = notHappyAtAll 

happyReduce_33 = happyReduce 4 17 happyReduction_33
happyReduction_33 (_ `HappyStk`
	(HappyAbsSyn25  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn17
		 (Type  (unTUident happy_var_1)  happy_var_3
	) `HappyStk` happyRest

happyReduce_34 = happySpecReduce_1  18 happyReduction_34
happyReduction_34 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn18
		 (EnumC  (unTUident happy_var_1)
	)
happyReduction_34 _  = notHappyAtAll 

happyReduce_35 = happySpecReduce_1  19 happyReduction_35
happyReduction_35 (HappyAbsSyn20  happy_var_1)
	 =  HappyAbsSyn19
		 (reverse happy_var_1
	)
happyReduction_35 _  = notHappyAtAll 

happyReduce_36 = happySpecReduce_1  20 happyReduction_36
happyReduction_36 (HappyAbsSyn16  happy_var_1)
	 =  HappyAbsSyn20
		 ([happy_var_1]
	)
happyReduction_36 _  = notHappyAtAll 

happyReduce_37 = happySpecReduce_3  20 happyReduction_37
happyReduction_37 (HappyAbsSyn16  happy_var_3)
	_
	(HappyAbsSyn20  happy_var_1)
	 =  HappyAbsSyn20
		 (happy_var_3 : happy_var_1
	)
happyReduction_37 _ _ _  = notHappyAtAll 

happyReduce_38 = happySpecReduce_1  21 happyReduction_38
happyReduction_38 (HappyAbsSyn22  happy_var_1)
	 =  HappyAbsSyn21
		 (reverse happy_var_1
	)
happyReduction_38 _  = notHappyAtAll 

happyReduce_39 = happySpecReduce_1  22 happyReduction_39
happyReduction_39 (HappyAbsSyn15  happy_var_1)
	 =  HappyAbsSyn22
		 ([happy_var_1]
	)
happyReduction_39 _  = notHappyAtAll 

happyReduce_40 = happySpecReduce_3  22 happyReduction_40
happyReduction_40 (HappyAbsSyn15  happy_var_3)
	_
	(HappyAbsSyn22  happy_var_1)
	 =  HappyAbsSyn22
		 (happy_var_3 : happy_var_1
	)
happyReduction_40 _ _ _  = notHappyAtAll 

happyReduce_41 = happySpecReduce_1  23 happyReduction_41
happyReduction_41 (HappyAbsSyn24  happy_var_1)
	 =  HappyAbsSyn23
		 (reverse happy_var_1
	)
happyReduction_41 _  = notHappyAtAll 

happyReduce_42 = happySpecReduce_1  24 happyReduction_42
happyReduction_42 (HappyAbsSyn18  happy_var_1)
	 =  HappyAbsSyn24
		 ([happy_var_1]
	)
happyReduction_42 _  = notHappyAtAll 

happyReduce_43 = happySpecReduce_3  24 happyReduction_43
happyReduction_43 (HappyAbsSyn18  happy_var_3)
	_
	(HappyAbsSyn24  happy_var_1)
	 =  HappyAbsSyn24
		 (happy_var_3 : happy_var_1
	)
happyReduction_43 _ _ _  = notHappyAtAll 

happyReduce_44 = happySpecReduce_1  25 happyReduction_44
happyReduction_44 (HappyAbsSyn26  happy_var_1)
	 =  HappyAbsSyn25
		 (reverse happy_var_1
	)
happyReduction_44 _  = notHappyAtAll 

happyReduce_45 = happySpecReduce_0  25 happyReduction_45
happyReduction_45  =  HappyAbsSyn25
		 ([]
	)

happyReduce_46 = happySpecReduce_1  26 happyReduction_46
happyReduction_46 (HappyAbsSyn17  happy_var_1)
	 =  HappyAbsSyn26
		 ([happy_var_1]
	)
happyReduction_46 _  = notHappyAtAll 

happyReduce_47 = happySpecReduce_3  26 happyReduction_47
happyReduction_47 (HappyAbsSyn17  happy_var_3)
	_
	(HappyAbsSyn26  happy_var_1)
	 =  HappyAbsSyn26
		 (happy_var_3 : happy_var_1
	)
happyReduction_47 _ _ _  = notHappyAtAll 

happyReduce_48 = happySpecReduce_1  27 happyReduction_48
happyReduction_48 (HappyAbsSyn28  happy_var_1)
	 =  HappyAbsSyn27
		 (reverse happy_var_1
	)
happyReduction_48 _  = notHappyAtAll 

happyReduce_49 = happySpecReduce_1  28 happyReduction_49
happyReduction_49 (HappyAbsSyn8  happy_var_1)
	 =  HappyAbsSyn28
		 ([happy_var_1]
	)
happyReduction_49 _  = notHappyAtAll 

happyReduce_50 = happySpecReduce_3  28 happyReduction_50
happyReduction_50 (HappyAbsSyn8  happy_var_3)
	_
	(HappyAbsSyn28  happy_var_1)
	 =  HappyAbsSyn28
		 (happy_var_3 : happy_var_1
	)
happyReduction_50 _ _ _  = notHappyAtAll 

happyReduce_51 = happySpecReduce_1  29 happyReduction_51
happyReduction_51 (HappyAbsSyn30  happy_var_1)
	 =  HappyAbsSyn29
		 (reverse happy_var_1
	)
happyReduction_51 _  = notHappyAtAll 

happyReduce_52 = happySpecReduce_1  30 happyReduction_52
happyReduction_52 (HappyAbsSyn9  happy_var_1)
	 =  HappyAbsSyn30
		 ([happy_var_1]
	)
happyReduction_52 _  = notHappyAtAll 

happyReduce_53 = happySpecReduce_3  30 happyReduction_53
happyReduction_53 (HappyAbsSyn9  happy_var_3)
	_
	(HappyAbsSyn30  happy_var_1)
	 =  HappyAbsSyn30
		 (happy_var_3 : happy_var_1
	)
happyReduction_53 _ _ _  = notHappyAtAll 

happyReduce_54 = happySpecReduce_1  31 happyReduction_54
happyReduction_54 (HappyAbsSyn32  happy_var_1)
	 =  HappyAbsSyn31
		 (reverse happy_var_1
	)
happyReduction_54 _  = notHappyAtAll 

happyReduce_55 = happySpecReduce_1  32 happyReduction_55
happyReduction_55 (HappyAbsSyn13  happy_var_1)
	 =  HappyAbsSyn32
		 ([happy_var_1]
	)
happyReduction_55 _  = notHappyAtAll 

happyReduce_56 = happySpecReduce_3  32 happyReduction_56
happyReduction_56 (HappyAbsSyn13  happy_var_3)
	_
	(HappyAbsSyn32  happy_var_1)
	 =  HappyAbsSyn32
		 (happy_var_3 : happy_var_1
	)
happyReduction_56 _ _ _  = notHappyAtAll 

happyReduce_57 = happySpecReduce_1  33 happyReduction_57
happyReduction_57 (HappyAbsSyn34  happy_var_1)
	 =  HappyAbsSyn33
		 (reverse happy_var_1
	)
happyReduction_57 _  = notHappyAtAll 

happyReduce_58 = happySpecReduce_0  33 happyReduction_58
happyReduction_58  =  HappyAbsSyn33
		 ([]
	)

happyReduce_59 = happySpecReduce_2  34 happyReduction_59
happyReduction_59 _
	(HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn34
		 ([happy_var_1]
	)
happyReduction_59 _ _  = notHappyAtAll 

happyReduce_60 = happySpecReduce_3  34 happyReduction_60
happyReduction_60 _
	(HappyAbsSyn10  happy_var_2)
	(HappyAbsSyn34  happy_var_1)
	 =  HappyAbsSyn34
		 (happy_var_2 : happy_var_1
	)
happyReduction_60 _ _ _  = notHappyAtAll 

happyReduce_61 = happySpecReduce_1  35 happyReduction_61
happyReduction_61 (HappyAbsSyn36  happy_var_1)
	 =  HappyAbsSyn35
		 (reverse happy_var_1
	)
happyReduction_61 _  = notHappyAtAll 

happyReduce_62 = happySpecReduce_0  35 happyReduction_62
happyReduction_62  =  HappyAbsSyn35
		 ([]
	)

happyReduce_63 = happySpecReduce_2  36 happyReduction_63
happyReduction_63 _
	(HappyAbsSyn7  happy_var_1)
	 =  HappyAbsSyn36
		 ([happy_var_1]
	)
happyReduction_63 _ _  = notHappyAtAll 

happyReduce_64 = happySpecReduce_3  36 happyReduction_64
happyReduction_64 _
	(HappyAbsSyn7  happy_var_2)
	(HappyAbsSyn36  happy_var_1)
	 =  HappyAbsSyn36
		 (happy_var_2 : happy_var_1
	)
happyReduction_64 _ _ _  = notHappyAtAll 

happyReduce_65 = happySpecReduce_1  37 happyReduction_65
happyReduction_65 (HappyAbsSyn38  happy_var_1)
	 =  HappyAbsSyn37
		 (reverse happy_var_1
	)
happyReduction_65 _  = notHappyAtAll 

happyReduce_66 = happySpecReduce_0  37 happyReduction_66
happyReduction_66  =  HappyAbsSyn37
		 ([]
	)

happyReduce_67 = happySpecReduce_2  38 happyReduction_67
happyReduction_67 _
	(HappyAbsSyn6  happy_var_1)
	 =  HappyAbsSyn38
		 ([happy_var_1]
	)
happyReduction_67 _ _  = notHappyAtAll 

happyReduce_68 = happySpecReduce_3  38 happyReduction_68
happyReduction_68 _
	(HappyAbsSyn6  happy_var_2)
	(HappyAbsSyn38  happy_var_1)
	 =  HappyAbsSyn38
		 (happy_var_2 : happy_var_1
	)
happyReduction_68 _ _ _  = notHappyAtAll 

happyReduce_69 = happySpecReduce_1  39 happyReduction_69
happyReduction_69 (HappyAbsSyn40  happy_var_1)
	 =  HappyAbsSyn39
		 (reverse happy_var_1
	)
happyReduction_69 _  = notHappyAtAll 

happyReduce_70 = happySpecReduce_0  39 happyReduction_70
happyReduction_70  =  HappyAbsSyn39
		 ([]
	)

happyReduce_71 = happySpecReduce_2  40 happyReduction_71
happyReduction_71 _
	(HappyAbsSyn5  happy_var_1)
	 =  HappyAbsSyn40
		 ([happy_var_1]
	)
happyReduction_71 _ _  = notHappyAtAll 

happyReduce_72 = happySpecReduce_3  40 happyReduction_72
happyReduction_72 _
	(HappyAbsSyn5  happy_var_2)
	(HappyAbsSyn40  happy_var_1)
	 =  HappyAbsSyn40
		 (happy_var_2 : happy_var_1
	)
happyReduction_72 _ _ _  = notHappyAtAll 

happyNewToken action sts stk [] =
	action 74 74 notHappyAtAll (HappyState action) sts stk []

happyNewToken action sts stk (tk:tks) =
	let cont i = action i i tk (HappyState action) sts stk tks in
	case tk of {
	TSymbol _ "(" -> cont 41;
	TSymbol _ ")" -> cont 42;
	TSymbol _ "," -> cont 43;
	TSymbol _ "->" -> cont 44;
	TSymbol _ "::" -> cont 45;
	TSymbol _ ":=" -> cont 46;
	TSymbol _ ";" -> cont 47;
	TSymbol _ "=" -> cont 48;
	TSymbol _ "alloca" -> cont 49;
	TSymbol _ "call" -> cont 50;
	TSymbol _ "cast" -> cont 51;
	TSymbol _ "define" -> cont 52;
	TSymbol _ "enum" -> cont 53;
	TSymbol _ "if" -> cont 54;
	TSymbol _ "import" -> cont 55;
	TSymbol _ "load" -> cont 56;
	TSymbol _ "module" -> cont 57;
	TSymbol _ "noop" -> cont 58;
	TSymbol _ "record" -> cont 59;
	TSymbol _ "return" -> cont 60;
	TSymbol _ "switch" -> cont 61;
	TSymbol _ "tagged" -> cont 62;
	TSymbol _ "when" -> cont 63;
	TSymbol _ "while" -> cont 64;
	TSymbol _ "{" -> cont 65;
	TSymbol _ "|" -> cont 66;
	TSymbol _ "}" -> cont 67;
	TUident _ _ -> cont 68;
	TUsym _ _ -> cont 69;
	TLident _ _ -> cont 70;
	TString _ _ -> cont 71;
	TChar _ _ -> cont 72;
	TNumber _ _ -> cont 73;
	_ -> happyError' (tk:tks)
	}

happyError_ tk tks = happyError' (tk:tks)

newtype HappyIdentity a = HappyIdentity a
happyIdentity = HappyIdentity
happyRunIdentity (HappyIdentity a) = a

instance Monad HappyIdentity where
    return = HappyIdentity
    (HappyIdentity p) >>= q = q p

happyThen :: () => HappyIdentity a -> (a -> HappyIdentity b) -> HappyIdentity b
happyThen = (>>=)
happyReturn :: () => a -> HappyIdentity a
happyReturn = (return)
happyThen1 m k tks = (>>=) m (\a -> k a tks)
happyReturn1 :: () => a -> b -> HappyIdentity a
happyReturn1 = \a tks -> (return) a
happyError' :: () => [((Token Point))] -> HappyIdentity a
happyError' = HappyIdentity . happyError

grmParse tks = happyRunIdentity happySomeParser where
  happySomeParser = happyThen (happyParse action_0 tks) (\x -> case x of {HappyAbsSyn4 z -> happyReturn z; _other -> notHappyAtAll })

happySeq = happyDontSeq



{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "<built-in>" #-}
{-# LINE 1 "<command-line>" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
-- Id: GenericTemplate.hs,v 1.26 2005/01/14 14:47:22 simonmar Exp 

{-# LINE 30 "templates/GenericTemplate.hs" #-}








{-# LINE 51 "templates/GenericTemplate.hs" #-}

{-# LINE 61 "templates/GenericTemplate.hs" #-}

{-# LINE 70 "templates/GenericTemplate.hs" #-}

infixr 9 `HappyStk`
data HappyStk a = HappyStk a (HappyStk a)

-----------------------------------------------------------------------------
-- starting the parse

happyParse start_state = happyNewToken start_state notHappyAtAll notHappyAtAll

-----------------------------------------------------------------------------
-- Accepting the parse

-- If the current token is (1), it means we've just accepted a partial
-- parse (a %partial parser).  We must ignore the saved token on the top of
-- the stack in this case.
happyAccept (1) tk st sts (_ `HappyStk` ans `HappyStk` _) =
	happyReturn1 ans
happyAccept j tk st sts (HappyStk ans _) = 
	 (happyReturn1 ans)

-----------------------------------------------------------------------------
-- Arrays only: do the next action

{-# LINE 148 "templates/GenericTemplate.hs" #-}

-----------------------------------------------------------------------------
-- HappyState data type (not arrays)



newtype HappyState b c = HappyState
        (Int ->                    -- token number
         Int ->                    -- token number (yes, again)
         b ->                           -- token semantic value
         HappyState b c ->              -- current state
         [HappyState b c] ->            -- state stack
         c)



-----------------------------------------------------------------------------
-- Shifting a token

happyShift new_state (1) tk st sts stk@(x `HappyStk` _) =
     let (i) = (case x of { HappyErrorToken (i) -> i }) in
--     trace "shifting the error token" $
     new_state i i tk (HappyState (new_state)) ((st):(sts)) (stk)

happyShift new_state i tk st sts stk =
     happyNewToken new_state ((st):(sts)) ((HappyTerminal (tk))`HappyStk`stk)

-- happyReduce is specialised for the common cases.

happySpecReduce_0 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_0 nt fn j tk st@((HappyState (action))) sts stk
     = action nt j tk st ((st):(sts)) (fn `HappyStk` stk)

happySpecReduce_1 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_1 nt fn j tk _ sts@(((st@(HappyState (action))):(_))) (v1`HappyStk`stk')
     = let r = fn v1 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_2 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_2 nt fn j tk _ ((_):(sts@(((st@(HappyState (action))):(_))))) (v1`HappyStk`v2`HappyStk`stk')
     = let r = fn v1 v2 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_3 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_3 nt fn j tk _ ((_):(((_):(sts@(((st@(HappyState (action))):(_))))))) (v1`HappyStk`v2`HappyStk`v3`HappyStk`stk')
     = let r = fn v1 v2 v3 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happyReduce k i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyReduce k nt fn j tk st sts stk
     = case happyDrop (k - ((1) :: Int)) sts of
	 sts1@(((st1@(HappyState (action))):(_))) ->
        	let r = fn stk in  -- it doesn't hurt to always seq here...
       		happyDoSeq r (action nt j tk st1 sts1 r)

happyMonadReduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonadReduce k nt fn j tk st sts stk =
        happyThen1 (fn stk tk) (\r -> action nt j tk st1 sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk

happyMonad2Reduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonad2Reduce k nt fn j tk st sts stk =
       happyThen1 (fn stk tk) (\r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk





             new_state = action


happyDrop (0) l = l
happyDrop n ((_):(t)) = happyDrop (n - ((1) :: Int)) t

happyDropStk (0) l = l
happyDropStk n (x `HappyStk` xs) = happyDropStk (n - ((1)::Int)) xs

-----------------------------------------------------------------------------
-- Moving to a new state after a reduction

{-# LINE 246 "templates/GenericTemplate.hs" #-}
happyGoto action j tk st = action j j tk (HappyState action)


-----------------------------------------------------------------------------
-- Error recovery ((1) is the error token)

-- parse error if we are in recovery and we fail again
happyFail  (1) tk old_st _ stk =
--	trace "failing" $ 
    	happyError_ tk

{-  We don't need state discarding for our restricted implementation of
    "error".  In fact, it can cause some bogus parses, so I've disabled it
    for now --SDM

-- discard a state
happyFail  (1) tk old_st (((HappyState (action))):(sts)) 
						(saved_tok `HappyStk` _ `HappyStk` stk) =
--	trace ("discarding state, depth " ++ show (length stk))  $
	action (1) (1) tk (HappyState (action)) sts ((saved_tok`HappyStk`stk))
-}

-- Enter error recovery: generate an error token,
--                       save the old token and carry on.
happyFail  i tk (HappyState (action)) sts stk =
--      trace "entering error recovery" $
	action (1) (1) tk (HappyState (action)) sts ( (HappyErrorToken (i)) `HappyStk` stk)

-- Internal happy errors:

notHappyAtAll :: a
notHappyAtAll = error "Internal Happy error\n"

-----------------------------------------------------------------------------
-- Hack to get the typechecker to accept our action functions







-----------------------------------------------------------------------------
-- Seq-ing.  If the --strict flag is given, then Happy emits 
--	happySeq = happyDoSeq
-- otherwise it emits
-- 	happySeq = happyDontSeq

happyDoSeq, happyDontSeq :: a -> b -> b
happyDoSeq   a b = a `seq` b
happyDontSeq a b = b

-----------------------------------------------------------------------------
-- Don't inline any functions from the template.  GHC has a nasty habit
-- of deciding to inline happyGoto everywhere, which increases the size of
-- the generated parser quite a bit.

{-# LINE 311 "templates/GenericTemplate.hs" #-}
{-# NOINLINE happyShift #-}
{-# NOINLINE happySpecReduce_0 #-}
{-# NOINLINE happySpecReduce_1 #-}
{-# NOINLINE happySpecReduce_2 #-}
{-# NOINLINE happySpecReduce_3 #-}
{-# NOINLINE happyReduce #-}
{-# NOINLINE happyMonadReduce #-}
{-# NOINLINE happyGoto #-}
{-# NOINLINE happyFail #-}

-- end of Happy Template.
