{-# OPTIONS_GHC -w #-}
{-# OPTIONS -w #-}
-- Haskell module generated by grm *** DO NOT EDIT ***


module Language.C.Par where
import Grm.Prims
import Grm.Lex
import Language.C.Abs

-- parser produced by Happy Version 1.18.6

data HappyAbsSyn t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35
	= HappyTerminal ((Token Point))
	| HappyErrorToken Int
	| HappyAbsSyn4 t4
	| HappyAbsSyn5 t5
	| HappyAbsSyn6 t6
	| HappyAbsSyn7 t7
	| HappyAbsSyn8 t8
	| HappyAbsSyn9 t9
	| HappyAbsSyn10 t10
	| HappyAbsSyn11 t11
	| HappyAbsSyn12 t12
	| HappyAbsSyn13 t13
	| HappyAbsSyn14 t14
	| HappyAbsSyn15 t15
	| HappyAbsSyn16 t16
	| HappyAbsSyn17 t17
	| HappyAbsSyn18 t18
	| HappyAbsSyn19 t19
	| HappyAbsSyn20 t20
	| HappyAbsSyn21 t21
	| HappyAbsSyn22 t22
	| HappyAbsSyn23 t23
	| HappyAbsSyn24 t24
	| HappyAbsSyn25 t25
	| HappyAbsSyn26 t26
	| HappyAbsSyn27 t27
	| HappyAbsSyn28 t28
	| HappyAbsSyn29 t29
	| HappyAbsSyn30 t30
	| HappyAbsSyn31 t31
	| HappyAbsSyn32 t32
	| HappyAbsSyn33 t33
	| HappyAbsSyn34 t34
	| HappyAbsSyn35 t35

action_0 (40) = happyShift action_2
action_0 (41) = happyShift action_7
action_0 (4) = happyGoto action_3
action_0 (5) = happyGoto action_4
action_0 (34) = happyGoto action_5
action_0 (35) = happyGoto action_6
action_0 _ = happyReduce_88

action_1 (40) = happyShift action_2
action_1 _ = happyFail

action_2 (74) = happyShift action_20
action_2 _ = happyFail

action_3 (80) = happyAccept
action_3 _ = happyFail

action_4 _ = happyReduce_89

action_5 (63) = happyShift action_16
action_5 (67) = happyShift action_17
action_5 (70) = happyShift action_18
action_5 (74) = happyShift action_19
action_5 (7) = happyGoto action_11
action_5 (8) = happyGoto action_12
action_5 (9) = happyGoto action_13
action_5 (32) = happyGoto action_14
action_5 (33) = happyGoto action_15
action_5 _ = happyReduce_84

action_6 (41) = happyShift action_7
action_6 (5) = happyGoto action_10
action_6 _ = happyReduce_87

action_7 (53) = happyShift action_8
action_7 (77) = happyShift action_9
action_7 _ = happyFail

action_8 (76) = happyShift action_32
action_8 _ = happyFail

action_9 _ = happyReduce_3

action_10 _ = happyReduce_90

action_11 (52) = happyShift action_31
action_11 _ = happyFail

action_12 (72) = happyShift action_30
action_12 _ = happyFail

action_13 (43) = happyShift action_26
action_13 (45) = happyShift action_27
action_13 (56) = happyShift action_28
action_13 (76) = happyShift action_29
action_13 _ = happyFail

action_14 _ = happyReduce_2

action_15 (63) = happyShift action_16
action_15 (67) = happyShift action_17
action_15 (70) = happyShift action_18
action_15 (74) = happyShift action_19
action_15 (7) = happyGoto action_25
action_15 (8) = happyGoto action_12
action_15 (9) = happyGoto action_13
action_15 _ = happyReduce_83

action_16 (72) = happyShift action_24
action_16 _ = happyFail

action_17 (72) = happyShift action_23
action_17 _ = happyFail

action_18 (72) = happyShift action_22
action_18 _ = happyFail

action_19 _ = happyReduce_10

action_20 (37) = happyShift action_21
action_20 _ = happyFail

action_21 (74) = happyShift action_68
action_21 _ = happyFail

action_22 (63) = happyShift action_16
action_22 (67) = happyShift action_17
action_22 (70) = happyShift action_18
action_22 (74) = happyShift action_19
action_22 (9) = happyGoto action_34
action_22 (11) = happyGoto action_64
action_22 (22) = happyGoto action_67
action_22 (23) = happyGoto action_66
action_22 _ = happyReduce_64

action_23 (63) = happyShift action_16
action_23 (67) = happyShift action_17
action_23 (70) = happyShift action_18
action_23 (74) = happyShift action_19
action_23 (9) = happyGoto action_34
action_23 (11) = happyGoto action_64
action_23 (22) = happyGoto action_65
action_23 (23) = happyGoto action_66
action_23 _ = happyReduce_64

action_24 (74) = happyShift action_63
action_24 (10) = happyGoto action_60
action_24 (20) = happyGoto action_61
action_24 (21) = happyGoto action_62
action_24 _ = happyFail

action_25 (52) = happyShift action_59
action_25 _ = happyFail

action_26 (45) = happyShift action_58
action_26 _ = happyFail

action_27 _ = happyReduce_11

action_28 (79) = happyShift action_57
action_28 _ = happyFail

action_29 (43) = happyShift action_56
action_29 _ = happyFail

action_30 (39) = happyShift action_41
action_30 (42) = happyShift action_42
action_30 (43) = happyShift action_43
action_30 (45) = happyShift action_44
action_30 (52) = happyReduce_76
action_30 (58) = happyShift action_45
action_30 (59) = happyShift action_46
action_30 (63) = happyShift action_16
action_30 (64) = happyShift action_47
action_30 (65) = happyShift action_48
action_30 (67) = happyShift action_17
action_30 (68) = happyShift action_49
action_30 (70) = happyShift action_18
action_30 (71) = happyShift action_50
action_30 (74) = happyShift action_51
action_30 (76) = happyShift action_52
action_30 (77) = happyShift action_53
action_30 (78) = happyShift action_54
action_30 (79) = happyShift action_55
action_30 (9) = happyGoto action_34
action_30 (11) = happyGoto action_35
action_30 (12) = happyGoto action_36
action_30 (13) = happyGoto action_37
action_30 (15) = happyGoto action_38
action_30 (28) = happyGoto action_39
action_30 (29) = happyGoto action_40
action_30 _ = happyReduce_76

action_31 _ = happyReduce_85

action_32 (55) = happyShift action_33
action_32 _ = happyFail

action_33 _ = happyReduce_4

action_34 (43) = happyShift action_104
action_34 (45) = happyShift action_27
action_34 (56) = happyShift action_28
action_34 (76) = happyShift action_105
action_34 _ = happyFail

action_35 _ = happyReduce_33

action_36 (43) = happyShift action_97
action_36 (46) = happyShift action_98
action_36 (48) = happyShift action_99
action_36 (49) = happyShift action_100
action_36 (50) = happyShift action_101
action_36 (54) = happyShift action_102
action_36 (56) = happyShift action_103
action_36 _ = happyFail

action_37 (52) = happyShift action_96
action_37 _ = happyFail

action_38 _ = happyReduce_22

action_39 (73) = happyShift action_95
action_39 _ = happyReduce_44

action_40 (39) = happyShift action_41
action_40 (42) = happyShift action_42
action_40 (43) = happyShift action_43
action_40 (45) = happyShift action_44
action_40 (52) = happyReduce_76
action_40 (58) = happyShift action_45
action_40 (59) = happyShift action_46
action_40 (63) = happyShift action_16
action_40 (64) = happyShift action_47
action_40 (65) = happyShift action_48
action_40 (67) = happyShift action_17
action_40 (68) = happyShift action_49
action_40 (70) = happyShift action_18
action_40 (71) = happyShift action_50
action_40 (74) = happyShift action_51
action_40 (76) = happyShift action_52
action_40 (77) = happyShift action_53
action_40 (78) = happyShift action_54
action_40 (79) = happyShift action_55
action_40 (9) = happyGoto action_34
action_40 (11) = happyGoto action_35
action_40 (12) = happyGoto action_36
action_40 (13) = happyGoto action_93
action_40 (15) = happyGoto action_38
action_40 (28) = happyGoto action_94
action_40 (29) = happyGoto action_40
action_40 _ = happyReduce_75

action_41 (39) = happyShift action_41
action_41 (42) = happyShift action_42
action_41 (43) = happyShift action_43
action_41 (45) = happyShift action_44
action_41 (58) = happyShift action_45
action_41 (74) = happyShift action_88
action_41 (76) = happyShift action_52
action_41 (77) = happyShift action_53
action_41 (78) = happyShift action_54
action_41 (79) = happyShift action_55
action_41 (12) = happyGoto action_92
action_41 (15) = happyGoto action_38
action_41 _ = happyFail

action_42 (39) = happyShift action_41
action_42 (42) = happyShift action_42
action_42 (43) = happyShift action_43
action_42 (45) = happyShift action_44
action_42 (58) = happyShift action_45
action_42 (74) = happyShift action_88
action_42 (76) = happyShift action_52
action_42 (77) = happyShift action_53
action_42 (78) = happyShift action_54
action_42 (79) = happyShift action_55
action_42 (12) = happyGoto action_91
action_42 (15) = happyGoto action_38
action_42 _ = happyFail

action_43 (39) = happyShift action_41
action_43 (42) = happyShift action_42
action_43 (43) = happyShift action_43
action_43 (45) = happyShift action_44
action_43 (58) = happyShift action_45
action_43 (63) = happyShift action_16
action_43 (67) = happyShift action_17
action_43 (70) = happyShift action_18
action_43 (74) = happyShift action_51
action_43 (76) = happyShift action_52
action_43 (77) = happyShift action_53
action_43 (78) = happyShift action_54
action_43 (79) = happyShift action_55
action_43 (9) = happyGoto action_89
action_43 (12) = happyGoto action_90
action_43 (15) = happyGoto action_38
action_43 _ = happyFail

action_44 (39) = happyShift action_41
action_44 (42) = happyShift action_42
action_44 (43) = happyShift action_43
action_44 (45) = happyShift action_44
action_44 (58) = happyShift action_45
action_44 (74) = happyShift action_88
action_44 (76) = happyShift action_52
action_44 (77) = happyShift action_53
action_44 (78) = happyShift action_54
action_44 (79) = happyShift action_55
action_44 (12) = happyGoto action_87
action_44 (15) = happyGoto action_38
action_44 _ = happyFail

action_45 (43) = happyShift action_86
action_45 _ = happyFail

action_46 _ = happyReduce_37

action_47 (43) = happyShift action_85
action_47 _ = happyFail

action_48 (43) = happyShift action_84
action_48 _ = happyReduce_42

action_49 (43) = happyShift action_83
action_49 _ = happyFail

action_50 (43) = happyShift action_82
action_50 _ = happyFail

action_51 (43) = happyReduce_52
action_51 (44) = happyReduce_52
action_51 (46) = happyReduce_52
action_51 (48) = happyReduce_52
action_51 (49) = happyReduce_52
action_51 (50) = happyReduce_52
action_51 (54) = happyReduce_52
action_51 (56) = happyReduce_52
action_51 (75) = happyReduce_52
action_51 _ = happyReduce_10

action_52 _ = happyReduce_21

action_53 _ = happyReduce_49

action_54 _ = happyReduce_50

action_55 _ = happyReduce_51

action_56 (63) = happyShift action_16
action_56 (67) = happyShift action_17
action_56 (70) = happyShift action_18
action_56 (74) = happyShift action_19
action_56 (9) = happyGoto action_34
action_56 (11) = happyGoto action_79
action_56 (24) = happyGoto action_80
action_56 (25) = happyGoto action_81
action_56 _ = happyReduce_68

action_57 (57) = happyShift action_78
action_57 _ = happyFail

action_58 (44) = happyShift action_76
action_58 (76) = happyShift action_77
action_58 _ = happyFail

action_59 _ = happyReduce_86

action_60 _ = happyReduce_61

action_61 (73) = happyShift action_75
action_61 _ = happyFail

action_62 (47) = happyShift action_74
action_62 _ = happyReduce_60

action_63 _ = happyReduce_17

action_64 (52) = happyShift action_73
action_64 _ = happyFail

action_65 (73) = happyShift action_72
action_65 _ = happyFail

action_66 (63) = happyShift action_16
action_66 (67) = happyShift action_17
action_66 (70) = happyShift action_18
action_66 (74) = happyShift action_19
action_66 (9) = happyGoto action_34
action_66 (11) = happyGoto action_71
action_66 _ = happyReduce_63

action_67 (73) = happyShift action_70
action_67 _ = happyFail

action_68 (36) = happyShift action_69
action_68 _ = happyFail

action_69 (41) = happyShift action_7
action_69 (5) = happyGoto action_4
action_69 (34) = happyGoto action_131
action_69 (35) = happyGoto action_6
action_69 _ = happyReduce_88

action_70 _ = happyReduce_16

action_71 (52) = happyShift action_130
action_71 _ = happyFail

action_72 _ = happyReduce_15

action_73 _ = happyReduce_65

action_74 (74) = happyShift action_63
action_74 (10) = happyGoto action_129
action_74 _ = happyFail

action_75 _ = happyReduce_14

action_76 (43) = happyShift action_128
action_76 _ = happyFail

action_77 (43) = happyShift action_127
action_77 _ = happyFail

action_78 _ = happyReduce_13

action_79 _ = happyReduce_69

action_80 (44) = happyShift action_126
action_80 _ = happyFail

action_81 (47) = happyShift action_125
action_81 _ = happyReduce_67

action_82 (39) = happyShift action_41
action_82 (42) = happyShift action_42
action_82 (43) = happyShift action_43
action_82 (45) = happyShift action_44
action_82 (58) = happyShift action_45
action_82 (74) = happyShift action_88
action_82 (76) = happyShift action_52
action_82 (77) = happyShift action_53
action_82 (78) = happyShift action_54
action_82 (79) = happyShift action_55
action_82 (12) = happyGoto action_124
action_82 (15) = happyGoto action_38
action_82 _ = happyFail

action_83 (39) = happyShift action_41
action_83 (42) = happyShift action_42
action_83 (43) = happyShift action_43
action_83 (45) = happyShift action_44
action_83 (58) = happyShift action_45
action_83 (74) = happyShift action_88
action_83 (76) = happyShift action_52
action_83 (77) = happyShift action_53
action_83 (78) = happyShift action_54
action_83 (79) = happyShift action_55
action_83 (12) = happyGoto action_123
action_83 (15) = happyGoto action_38
action_83 _ = happyFail

action_84 (39) = happyShift action_41
action_84 (42) = happyShift action_42
action_84 (43) = happyShift action_43
action_84 (45) = happyShift action_44
action_84 (58) = happyShift action_45
action_84 (74) = happyShift action_88
action_84 (76) = happyShift action_52
action_84 (77) = happyShift action_53
action_84 (78) = happyShift action_54
action_84 (79) = happyShift action_55
action_84 (12) = happyGoto action_122
action_84 (15) = happyGoto action_38
action_84 _ = happyFail

action_85 (39) = happyShift action_41
action_85 (42) = happyShift action_42
action_85 (43) = happyShift action_43
action_85 (45) = happyShift action_44
action_85 (58) = happyShift action_45
action_85 (74) = happyShift action_88
action_85 (76) = happyShift action_52
action_85 (77) = happyShift action_53
action_85 (78) = happyShift action_54
action_85 (79) = happyShift action_55
action_85 (12) = happyGoto action_121
action_85 (15) = happyGoto action_38
action_85 _ = happyFail

action_86 (66) = happyShift action_120
action_86 _ = happyFail

action_87 (43) = happyShift action_116
action_87 (49) = happyShift action_100
action_87 (50) = happyShift action_101
action_87 (56) = happyShift action_103
action_87 _ = happyReduce_24

action_88 _ = happyReduce_52

action_89 (43) = happyShift action_104
action_89 (44) = happyShift action_119
action_89 (45) = happyShift action_27
action_89 (56) = happyShift action_28
action_89 _ = happyFail

action_90 (43) = happyShift action_116
action_90 (44) = happyShift action_117
action_90 (49) = happyShift action_100
action_90 (50) = happyShift action_101
action_90 (56) = happyShift action_103
action_90 (75) = happyShift action_118
action_90 _ = happyFail

action_91 (43) = happyShift action_116
action_91 (49) = happyShift action_100
action_91 (50) = happyShift action_101
action_91 (56) = happyShift action_103
action_91 _ = happyReduce_27

action_92 (43) = happyShift action_116
action_92 (49) = happyShift action_100
action_92 (50) = happyShift action_101
action_92 (56) = happyShift action_103
action_92 _ = happyReduce_32

action_93 (52) = happyShift action_115
action_93 _ = happyFail

action_94 _ = happyReduce_44

action_95 _ = happyReduce_7

action_96 _ = happyReduce_77

action_97 (39) = happyShift action_41
action_97 (42) = happyShift action_42
action_97 (43) = happyShift action_43
action_97 (45) = happyShift action_44
action_97 (58) = happyShift action_45
action_97 (74) = happyShift action_88
action_97 (76) = happyShift action_52
action_97 (77) = happyShift action_53
action_97 (78) = happyShift action_54
action_97 (79) = happyShift action_55
action_97 (12) = happyGoto action_112
action_97 (15) = happyGoto action_38
action_97 (18) = happyGoto action_113
action_97 (19) = happyGoto action_114
action_97 _ = happyFail

action_98 _ = happyReduce_45

action_99 _ = happyReduce_46

action_100 (39) = happyShift action_41
action_100 (42) = happyShift action_42
action_100 (43) = happyShift action_43
action_100 (45) = happyShift action_44
action_100 (58) = happyShift action_45
action_100 (74) = happyShift action_88
action_100 (76) = happyShift action_52
action_100 (77) = happyShift action_53
action_100 (78) = happyShift action_54
action_100 (79) = happyShift action_55
action_100 (12) = happyGoto action_111
action_100 (15) = happyGoto action_38
action_100 _ = happyFail

action_101 (39) = happyShift action_41
action_101 (42) = happyShift action_42
action_101 (43) = happyShift action_43
action_101 (45) = happyShift action_44
action_101 (58) = happyShift action_45
action_101 (74) = happyShift action_88
action_101 (76) = happyShift action_52
action_101 (77) = happyShift action_53
action_101 (78) = happyShift action_54
action_101 (79) = happyShift action_55
action_101 (12) = happyGoto action_110
action_101 (15) = happyGoto action_38
action_101 _ = happyFail

action_102 (39) = happyShift action_41
action_102 (42) = happyShift action_42
action_102 (43) = happyShift action_43
action_102 (45) = happyShift action_44
action_102 (58) = happyShift action_45
action_102 (74) = happyShift action_88
action_102 (76) = happyShift action_52
action_102 (77) = happyShift action_53
action_102 (78) = happyShift action_54
action_102 (79) = happyShift action_55
action_102 (12) = happyGoto action_109
action_102 (15) = happyGoto action_38
action_102 _ = happyFail

action_103 (39) = happyShift action_41
action_103 (42) = happyShift action_42
action_103 (43) = happyShift action_43
action_103 (45) = happyShift action_44
action_103 (58) = happyShift action_45
action_103 (74) = happyShift action_88
action_103 (76) = happyShift action_52
action_103 (77) = happyShift action_53
action_103 (78) = happyShift action_54
action_103 (79) = happyShift action_55
action_103 (12) = happyGoto action_108
action_103 (15) = happyGoto action_38
action_103 _ = happyFail

action_104 (45) = happyShift action_107
action_104 _ = happyFail

action_105 (43) = happyShift action_106
action_105 _ = happyReduce_18

action_106 (63) = happyShift action_16
action_106 (67) = happyShift action_17
action_106 (70) = happyShift action_18
action_106 (74) = happyShift action_19
action_106 (9) = happyGoto action_137
action_106 (16) = happyGoto action_153
action_106 (17) = happyGoto action_139
action_106 _ = happyReduce_54

action_107 (44) = happyShift action_76
action_107 _ = happyFail

action_108 (43) = happyShift action_116
action_108 (49) = happyShift action_100
action_108 (50) = happyShift action_101
action_108 (56) = happyShift action_103
action_108 (57) = happyShift action_152
action_108 _ = happyFail

action_109 (43) = happyShift action_116
action_109 (49) = happyShift action_100
action_109 (50) = happyShift action_101
action_109 (56) = happyShift action_103
action_109 _ = happyReduce_34

action_110 (43) = happyShift action_116
action_110 (49) = happyShift action_100
action_110 (50) = happyShift action_101
action_110 (56) = happyShift action_103
action_110 _ = happyReduce_26

action_111 (43) = happyShift action_116
action_111 (49) = happyShift action_100
action_111 (50) = happyShift action_101
action_111 (56) = happyShift action_103
action_111 _ = happyReduce_25

action_112 (43) = happyShift action_116
action_112 (49) = happyShift action_100
action_112 (50) = happyShift action_101
action_112 (56) = happyShift action_103
action_112 _ = happyReduce_58

action_113 (44) = happyShift action_151
action_113 _ = happyFail

action_114 (47) = happyShift action_150
action_114 _ = happyReduce_57

action_115 (39) = happyReduce_78
action_115 (42) = happyReduce_78
action_115 (43) = happyReduce_78
action_115 (45) = happyReduce_78
action_115 (52) = happyReduce_78
action_115 (58) = happyReduce_78
action_115 (59) = happyReduce_78
action_115 (63) = happyReduce_78
action_115 (64) = happyReduce_78
action_115 (65) = happyReduce_78
action_115 (67) = happyReduce_78
action_115 (68) = happyReduce_78
action_115 (70) = happyReduce_78
action_115 (71) = happyReduce_78
action_115 (74) = happyReduce_78
action_115 (76) = happyReduce_78
action_115 (77) = happyReduce_78
action_115 (78) = happyReduce_78
action_115 (79) = happyReduce_78
action_115 _ = happyReduce_78

action_116 (39) = happyShift action_41
action_116 (42) = happyShift action_42
action_116 (43) = happyShift action_43
action_116 (45) = happyShift action_44
action_116 (58) = happyShift action_45
action_116 (74) = happyShift action_88
action_116 (76) = happyShift action_52
action_116 (77) = happyShift action_53
action_116 (78) = happyShift action_54
action_116 (79) = happyShift action_55
action_116 (12) = happyGoto action_112
action_116 (15) = happyGoto action_38
action_116 (18) = happyGoto action_149
action_116 (19) = happyGoto action_114
action_116 _ = happyFail

action_117 _ = happyReduce_31

action_118 (39) = happyShift action_41
action_118 (42) = happyShift action_42
action_118 (43) = happyShift action_43
action_118 (45) = happyShift action_44
action_118 (58) = happyShift action_45
action_118 (74) = happyShift action_88
action_118 (76) = happyShift action_52
action_118 (77) = happyShift action_53
action_118 (78) = happyShift action_54
action_118 (79) = happyShift action_55
action_118 (12) = happyGoto action_148
action_118 (15) = happyGoto action_38
action_118 _ = happyFail

action_119 (39) = happyShift action_41
action_119 (42) = happyShift action_42
action_119 (43) = happyShift action_43
action_119 (45) = happyShift action_44
action_119 (58) = happyShift action_45
action_119 (74) = happyShift action_88
action_119 (76) = happyShift action_52
action_119 (77) = happyShift action_53
action_119 (78) = happyShift action_54
action_119 (79) = happyShift action_55
action_119 (12) = happyGoto action_147
action_119 (15) = happyGoto action_38
action_119 _ = happyFail

action_120 (43) = happyShift action_146
action_120 _ = happyFail

action_121 (43) = happyShift action_116
action_121 (44) = happyShift action_145
action_121 (49) = happyShift action_100
action_121 (50) = happyShift action_101
action_121 (56) = happyShift action_103
action_121 _ = happyFail

action_122 (43) = happyShift action_116
action_122 (44) = happyShift action_144
action_122 (49) = happyShift action_100
action_122 (50) = happyShift action_101
action_122 (56) = happyShift action_103
action_122 _ = happyFail

action_123 (43) = happyShift action_116
action_123 (44) = happyShift action_143
action_123 (49) = happyShift action_100
action_123 (50) = happyShift action_101
action_123 (56) = happyShift action_103
action_123 _ = happyFail

action_124 (43) = happyShift action_116
action_124 (44) = happyShift action_142
action_124 (49) = happyShift action_100
action_124 (50) = happyShift action_101
action_124 (56) = happyShift action_103
action_124 _ = happyFail

action_125 (63) = happyShift action_16
action_125 (67) = happyShift action_17
action_125 (70) = happyShift action_18
action_125 (74) = happyShift action_19
action_125 (9) = happyGoto action_34
action_125 (11) = happyGoto action_141
action_125 _ = happyFail

action_126 _ = happyReduce_8

action_127 (63) = happyShift action_16
action_127 (67) = happyShift action_17
action_127 (70) = happyShift action_18
action_127 (74) = happyShift action_19
action_127 (9) = happyGoto action_34
action_127 (11) = happyGoto action_79
action_127 (24) = happyGoto action_140
action_127 (25) = happyGoto action_81
action_127 _ = happyReduce_68

action_128 (63) = happyShift action_16
action_128 (67) = happyShift action_17
action_128 (70) = happyShift action_18
action_128 (74) = happyShift action_19
action_128 (9) = happyGoto action_137
action_128 (16) = happyGoto action_138
action_128 (17) = happyGoto action_139
action_128 _ = happyReduce_54

action_129 _ = happyReduce_62

action_130 _ = happyReduce_66

action_131 (63) = happyShift action_16
action_131 (67) = happyShift action_17
action_131 (69) = happyShift action_136
action_131 (70) = happyShift action_18
action_131 (74) = happyShift action_19
action_131 (6) = happyGoto action_132
action_131 (8) = happyGoto action_133
action_131 (9) = happyGoto action_13
action_131 (30) = happyGoto action_134
action_131 (31) = happyGoto action_135
action_131 _ = happyReduce_80

action_132 (52) = happyShift action_168
action_132 _ = happyFail

action_133 _ = happyReduce_5

action_134 (38) = happyShift action_167
action_134 _ = happyFail

action_135 (63) = happyShift action_16
action_135 (67) = happyShift action_17
action_135 (69) = happyShift action_136
action_135 (70) = happyShift action_18
action_135 (74) = happyShift action_19
action_135 (6) = happyGoto action_166
action_135 (8) = happyGoto action_133
action_135 (9) = happyGoto action_13
action_135 _ = happyReduce_79

action_136 (63) = happyShift action_16
action_136 (67) = happyShift action_17
action_136 (70) = happyShift action_18
action_136 (74) = happyShift action_19
action_136 (9) = happyGoto action_34
action_136 (11) = happyGoto action_165
action_136 _ = happyFail

action_137 (43) = happyShift action_104
action_137 (45) = happyShift action_27
action_137 (56) = happyShift action_28
action_137 _ = happyReduce_55

action_138 (44) = happyShift action_164
action_138 _ = happyFail

action_139 (47) = happyShift action_163
action_139 _ = happyReduce_53

action_140 (44) = happyShift action_162
action_140 _ = happyFail

action_141 _ = happyReduce_70

action_142 (72) = happyShift action_161
action_142 _ = happyFail

action_143 (72) = happyShift action_160
action_143 _ = happyFail

action_144 _ = happyReduce_41

action_145 (72) = happyShift action_159
action_145 _ = happyFail

action_146 (63) = happyShift action_16
action_146 (67) = happyShift action_17
action_146 (70) = happyShift action_18
action_146 (74) = happyShift action_19
action_146 (9) = happyGoto action_158
action_146 _ = happyFail

action_147 (43) = happyShift action_116
action_147 (49) = happyShift action_100
action_147 (50) = happyShift action_101
action_147 (56) = happyShift action_103
action_147 _ = happyReduce_23

action_148 (43) = happyShift action_116
action_148 (44) = happyShift action_157
action_148 (49) = happyShift action_100
action_148 (50) = happyShift action_101
action_148 (56) = happyShift action_103
action_148 _ = happyFail

action_149 (44) = happyShift action_156
action_149 _ = happyFail

action_150 (39) = happyShift action_41
action_150 (42) = happyShift action_42
action_150 (43) = happyShift action_43
action_150 (45) = happyShift action_44
action_150 (58) = happyShift action_45
action_150 (74) = happyShift action_88
action_150 (76) = happyShift action_52
action_150 (77) = happyShift action_53
action_150 (78) = happyShift action_54
action_150 (79) = happyShift action_55
action_150 (12) = happyGoto action_155
action_150 (15) = happyGoto action_38
action_150 _ = happyFail

action_151 (52) = happyReduce_35
action_151 _ = happyReduce_29

action_152 _ = happyReduce_28

action_153 (44) = happyShift action_154
action_153 _ = happyFail

action_154 _ = happyReduce_19

action_155 (43) = happyShift action_116
action_155 (49) = happyShift action_100
action_155 (50) = happyShift action_101
action_155 (56) = happyShift action_103
action_155 _ = happyReduce_59

action_156 _ = happyReduce_29

action_157 _ = happyReduce_30

action_158 (43) = happyShift action_104
action_158 (44) = happyShift action_179
action_158 (45) = happyShift action_27
action_158 (56) = happyShift action_28
action_158 _ = happyFail

action_159 (39) = happyShift action_41
action_159 (42) = happyShift action_42
action_159 (43) = happyShift action_43
action_159 (45) = happyShift action_44
action_159 (52) = happyReduce_76
action_159 (58) = happyShift action_45
action_159 (59) = happyShift action_46
action_159 (63) = happyShift action_16
action_159 (64) = happyShift action_47
action_159 (65) = happyShift action_48
action_159 (67) = happyShift action_17
action_159 (68) = happyShift action_49
action_159 (70) = happyShift action_18
action_159 (71) = happyShift action_50
action_159 (74) = happyShift action_51
action_159 (76) = happyShift action_52
action_159 (77) = happyShift action_53
action_159 (78) = happyShift action_54
action_159 (79) = happyShift action_55
action_159 (9) = happyGoto action_34
action_159 (11) = happyGoto action_35
action_159 (12) = happyGoto action_36
action_159 (13) = happyGoto action_37
action_159 (15) = happyGoto action_38
action_159 (28) = happyGoto action_178
action_159 (29) = happyGoto action_40
action_159 _ = happyReduce_76

action_160 (60) = happyShift action_176
action_160 (61) = happyShift action_177
action_160 (14) = happyGoto action_173
action_160 (26) = happyGoto action_174
action_160 (27) = happyGoto action_175
action_160 _ = happyReduce_72

action_161 (39) = happyShift action_41
action_161 (42) = happyShift action_42
action_161 (43) = happyShift action_43
action_161 (45) = happyShift action_44
action_161 (52) = happyReduce_76
action_161 (58) = happyShift action_45
action_161 (59) = happyShift action_46
action_161 (63) = happyShift action_16
action_161 (64) = happyShift action_47
action_161 (65) = happyShift action_48
action_161 (67) = happyShift action_17
action_161 (68) = happyShift action_49
action_161 (70) = happyShift action_18
action_161 (71) = happyShift action_50
action_161 (74) = happyShift action_51
action_161 (76) = happyShift action_52
action_161 (77) = happyShift action_53
action_161 (78) = happyShift action_54
action_161 (79) = happyShift action_55
action_161 (9) = happyGoto action_34
action_161 (11) = happyGoto action_35
action_161 (12) = happyGoto action_36
action_161 (13) = happyGoto action_37
action_161 (15) = happyGoto action_38
action_161 (28) = happyGoto action_172
action_161 (29) = happyGoto action_40
action_161 _ = happyReduce_76

action_162 (44) = happyShift action_171
action_162 _ = happyFail

action_163 (63) = happyShift action_16
action_163 (67) = happyShift action_17
action_163 (70) = happyShift action_18
action_163 (74) = happyShift action_19
action_163 (9) = happyGoto action_170
action_163 _ = happyFail

action_164 _ = happyReduce_12

action_165 _ = happyReduce_6

action_166 (52) = happyShift action_169
action_166 _ = happyFail

action_167 _ = happyReduce_1

action_168 _ = happyReduce_81

action_169 _ = happyReduce_82

action_170 (43) = happyShift action_104
action_170 (45) = happyShift action_27
action_170 (56) = happyShift action_28
action_170 _ = happyReduce_56

action_171 (43) = happyShift action_187
action_171 _ = happyFail

action_172 (73) = happyShift action_186
action_172 _ = happyReduce_44

action_173 _ = happyReduce_73

action_174 (73) = happyShift action_185
action_174 _ = happyFail

action_175 (60) = happyShift action_176
action_175 (61) = happyShift action_177
action_175 (14) = happyGoto action_184
action_175 _ = happyReduce_71

action_176 (74) = happyShift action_88
action_176 (77) = happyShift action_53
action_176 (78) = happyShift action_54
action_176 (79) = happyShift action_55
action_176 (15) = happyGoto action_183
action_176 _ = happyFail

action_177 (39) = happyShift action_41
action_177 (42) = happyShift action_42
action_177 (43) = happyShift action_43
action_177 (45) = happyShift action_44
action_177 (52) = happyReduce_76
action_177 (58) = happyShift action_45
action_177 (59) = happyShift action_46
action_177 (63) = happyShift action_16
action_177 (64) = happyShift action_47
action_177 (65) = happyShift action_48
action_177 (67) = happyShift action_17
action_177 (68) = happyShift action_49
action_177 (70) = happyShift action_18
action_177 (71) = happyShift action_50
action_177 (74) = happyShift action_51
action_177 (76) = happyShift action_52
action_177 (77) = happyShift action_53
action_177 (78) = happyShift action_54
action_177 (79) = happyShift action_55
action_177 (9) = happyGoto action_34
action_177 (11) = happyGoto action_35
action_177 (12) = happyGoto action_36
action_177 (13) = happyGoto action_37
action_177 (15) = happyGoto action_38
action_177 (28) = happyGoto action_182
action_177 (29) = happyGoto action_40
action_177 _ = happyReduce_76

action_178 (73) = happyShift action_181
action_178 _ = happyReduce_44

action_179 (44) = happyShift action_180
action_179 _ = happyFail

action_180 _ = happyReduce_20

action_181 (62) = happyShift action_190
action_181 _ = happyReduce_39

action_182 (60) = happyReduce_48
action_182 (61) = happyReduce_48
action_182 (73) = happyReduce_48
action_182 _ = happyReduce_44

action_183 (51) = happyShift action_189
action_183 _ = happyFail

action_184 _ = happyReduce_74

action_185 _ = happyReduce_36

action_186 _ = happyReduce_40

action_187 (63) = happyShift action_16
action_187 (67) = happyShift action_17
action_187 (70) = happyShift action_18
action_187 (74) = happyShift action_19
action_187 (9) = happyGoto action_137
action_187 (16) = happyGoto action_188
action_187 (17) = happyGoto action_139
action_187 _ = happyReduce_54

action_188 (44) = happyShift action_193
action_188 _ = happyFail

action_189 (39) = happyShift action_41
action_189 (42) = happyShift action_42
action_189 (43) = happyShift action_43
action_189 (45) = happyShift action_44
action_189 (52) = happyReduce_76
action_189 (58) = happyShift action_45
action_189 (59) = happyShift action_46
action_189 (63) = happyShift action_16
action_189 (64) = happyShift action_47
action_189 (65) = happyShift action_48
action_189 (67) = happyShift action_17
action_189 (68) = happyShift action_49
action_189 (70) = happyShift action_18
action_189 (71) = happyShift action_50
action_189 (74) = happyShift action_51
action_189 (76) = happyShift action_52
action_189 (77) = happyShift action_53
action_189 (78) = happyShift action_54
action_189 (79) = happyShift action_55
action_189 (9) = happyGoto action_34
action_189 (11) = happyGoto action_35
action_189 (12) = happyGoto action_36
action_189 (13) = happyGoto action_37
action_189 (15) = happyGoto action_38
action_189 (28) = happyGoto action_192
action_189 (29) = happyGoto action_40
action_189 _ = happyReduce_76

action_190 (72) = happyShift action_191
action_190 _ = happyFail

action_191 (39) = happyShift action_41
action_191 (42) = happyShift action_42
action_191 (43) = happyShift action_43
action_191 (45) = happyShift action_44
action_191 (52) = happyReduce_76
action_191 (58) = happyShift action_45
action_191 (59) = happyShift action_46
action_191 (63) = happyShift action_16
action_191 (64) = happyShift action_47
action_191 (65) = happyShift action_48
action_191 (67) = happyShift action_17
action_191 (68) = happyShift action_49
action_191 (70) = happyShift action_18
action_191 (71) = happyShift action_50
action_191 (74) = happyShift action_51
action_191 (76) = happyShift action_52
action_191 (77) = happyShift action_53
action_191 (78) = happyShift action_54
action_191 (79) = happyShift action_55
action_191 (9) = happyGoto action_34
action_191 (11) = happyGoto action_35
action_191 (12) = happyGoto action_36
action_191 (13) = happyGoto action_37
action_191 (15) = happyGoto action_38
action_191 (28) = happyGoto action_194
action_191 (29) = happyGoto action_40
action_191 _ = happyReduce_76

action_192 (60) = happyReduce_47
action_192 (61) = happyReduce_47
action_192 (73) = happyReduce_47
action_192 _ = happyReduce_44

action_193 _ = happyReduce_9

action_194 (73) = happyShift action_195
action_194 _ = happyReduce_44

action_195 _ = happyReduce_38

happyReduce_1 = happyReduce 8 4 happyReduction_1
happyReduction_1 (_ `HappyStk`
	(HappyAbsSyn30  happy_var_7) `HappyStk`
	(HappyAbsSyn34  happy_var_6) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn4
		 (HModule   (unTUident happy_var_2)  (unTUident happy_var_4)  happy_var_6 happy_var_7
	) `HappyStk` happyRest

happyReduce_2 = happySpecReduce_2  4 happyReduction_2
happyReduction_2 (HappyAbsSyn32  happy_var_2)
	(HappyAbsSyn34  happy_var_1)
	 =  HappyAbsSyn4
		 (CModule  happy_var_1 happy_var_2
	)
happyReduction_2 _ _  = notHappyAtAll 

happyReduce_3 = happySpecReduce_2  5 happyReduction_3
happyReduction_3 (HappyTerminal happy_var_2)
	_
	 =  HappyAbsSyn5
		 (Import   (unTString happy_var_2)
	)
happyReduction_3 _ _  = notHappyAtAll 

happyReduce_4 = happyReduce 4 5 happyReduction_4
happyReduction_4 (_ `HappyStk`
	(HappyTerminal happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn5
		 (GImport     (unTLident happy_var_3)
	) `HappyStk` happyRest

happyReduce_5 = happySpecReduce_1  6 happyReduction_5
happyReduction_5 (HappyAbsSyn8  happy_var_1)
	 =  HappyAbsSyn6
		 (Declare  happy_var_1
	)
happyReduction_5 _  = notHappyAtAll 

happyReduce_6 = happySpecReduce_2  6 happyReduction_6
happyReduction_6 (HappyAbsSyn11  happy_var_2)
	_
	 =  HappyAbsSyn6
		 (Typedef   happy_var_2
	)
happyReduction_6 _ _  = notHappyAtAll 

happyReduce_7 = happyReduce 4 7 happyReduction_7
happyReduction_7 (_ `HappyStk`
	(HappyAbsSyn28  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn8  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn7
		 (Define  happy_var_1  happy_var_3
	) `HappyStk` happyRest

happyReduce_8 = happyReduce 5 8 happyReduction_8
happyReduction_8 (_ `HappyStk`
	(HappyAbsSyn24  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	(HappyAbsSyn9  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn8
		 (FunFD  happy_var_1 (unTLident happy_var_2)    happy_var_4
	) `HappyStk` happyRest

happyReduce_9 = happyReduce 11 8 happyReduction_9
happyReduction_9 (_ `HappyStk`
	(HappyAbsSyn16  happy_var_10) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn24  happy_var_6) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_4) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn9  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn8
		 (RetFunFD  happy_var_1   (unTLident happy_var_4)   happy_var_6      happy_var_10
	) `HappyStk` happyRest

happyReduce_10 = happySpecReduce_1  9 happyReduction_10
happyReduction_10 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn9
		 (TyName  (unTUident happy_var_1)
	)
happyReduction_10 _  = notHappyAtAll 

happyReduce_11 = happySpecReduce_2  9 happyReduction_11
happyReduction_11 _
	(HappyAbsSyn9  happy_var_1)
	 =  HappyAbsSyn9
		 (TyPtr  happy_var_1
	)
happyReduction_11 _ _  = notHappyAtAll 

happyReduce_12 = happyReduce 7 9 happyReduction_12
happyReduction_12 (_ `HappyStk`
	(HappyAbsSyn16  happy_var_6) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn9  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn9
		 (TyFun  happy_var_1        happy_var_6
	) `HappyStk` happyRest

happyReduce_13 = happyReduce 4 9 happyReduction_13
happyReduction_13 (_ `HappyStk`
	(HappyTerminal happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn9  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn9
		 (TyArray  happy_var_1  (unTNumber happy_var_3)
	) `HappyStk` happyRest

happyReduce_14 = happyReduce 4 9 happyReduction_14
happyReduction_14 (_ `HappyStk`
	(HappyAbsSyn20  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn9
		 (TyEnum    happy_var_3
	) `HappyStk` happyRest

happyReduce_15 = happyReduce 4 9 happyReduction_15
happyReduction_15 (_ `HappyStk`
	(HappyAbsSyn22  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn9
		 (TyStruct    happy_var_3
	) `HappyStk` happyRest

happyReduce_16 = happyReduce 4 9 happyReduction_16
happyReduction_16 (_ `HappyStk`
	(HappyAbsSyn22  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn9
		 (TyUnion    happy_var_3
	) `HappyStk` happyRest

happyReduce_17 = happySpecReduce_1  10 happyReduction_17
happyReduction_17 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn10
		 (EnumC  (unTUident happy_var_1)
	)
happyReduction_17 _  = notHappyAtAll 

happyReduce_18 = happySpecReduce_2  11 happyReduction_18
happyReduction_18 (HappyTerminal happy_var_2)
	(HappyAbsSyn9  happy_var_1)
	 =  HappyAbsSyn11
		 (Decl  happy_var_1 (unTLident happy_var_2)
	)
happyReduction_18 _ _  = notHappyAtAll 

happyReduce_19 = happyReduce 5 11 happyReduction_19
happyReduction_19 (_ `HappyStk`
	(HappyAbsSyn16  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyTerminal happy_var_2) `HappyStk`
	(HappyAbsSyn9  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn11
		 (FunD  happy_var_1 (unTLident happy_var_2)    happy_var_4
	) `HappyStk` happyRest

happyReduce_20 = happyReduce 7 12 happyReduction_20
happyReduction_20 (_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn9  happy_var_5) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn12
		 (AllocaE      happy_var_5
	) `HappyStk` happyRest

happyReduce_21 = happySpecReduce_1  12 happyReduction_21
happyReduction_21 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn12
		 (VarE  (unTLident happy_var_1)
	)
happyReduction_21 _  = notHappyAtAll 

happyReduce_22 = happySpecReduce_1  12 happyReduction_22
happyReduction_22 (HappyAbsSyn15  happy_var_1)
	 =  HappyAbsSyn12
		 (LitE  happy_var_1
	)
happyReduction_22 _  = notHappyAtAll 

happyReduce_23 = happyReduce 4 12 happyReduction_23
happyReduction_23 ((HappyAbsSyn12  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn9  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn12
		 (CastE   happy_var_2  happy_var_4
	) `HappyStk` happyRest

happyReduce_24 = happySpecReduce_2  12 happyReduction_24
happyReduction_24 (HappyAbsSyn12  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (LoadE    happy_var_2
	)
happyReduction_24 _ _  = notHappyAtAll 

happyReduce_25 = happySpecReduce_3  12 happyReduction_25
happyReduction_25 (HappyAbsSyn12  happy_var_3)
	_
	(HappyAbsSyn12  happy_var_1)
	 =  HappyAbsSyn12
		 (ArrowE  happy_var_1    happy_var_3
	)
happyReduction_25 _ _ _  = notHappyAtAll 

happyReduce_26 = happySpecReduce_3  12 happyReduction_26
happyReduction_26 (HappyAbsSyn12  happy_var_3)
	_
	(HappyAbsSyn12  happy_var_1)
	 =  HappyAbsSyn12
		 (DotE  happy_var_1    happy_var_3
	)
happyReduction_26 _ _ _  = notHappyAtAll 

happyReduce_27 = happySpecReduce_2  12 happyReduction_27
happyReduction_27 (HappyAbsSyn12  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (AddrE    happy_var_2
	)
happyReduction_27 _ _  = notHappyAtAll 

happyReduce_28 = happyReduce 4 12 happyReduction_28
happyReduction_28 (_ `HappyStk`
	(HappyAbsSyn12  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn12  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn12
		 (IdxE  happy_var_1    happy_var_3
	) `HappyStk` happyRest

happyReduce_29 = happyReduce 4 12 happyReduction_29
happyReduction_29 (_ `HappyStk`
	(HappyAbsSyn18  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn12  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn12
		 (CallE  happy_var_1    happy_var_3
	) `HappyStk` happyRest

happyReduce_30 = happyReduce 5 12 happyReduction_30
happyReduction_30 (_ `HappyStk`
	(HappyAbsSyn12  happy_var_4) `HappyStk`
	(HappyTerminal happy_var_3) `HappyStk`
	(HappyAbsSyn12  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn12
		 (BinOpE    happy_var_2 (unTUsym happy_var_3) happy_var_4
	) `HappyStk` happyRest

happyReduce_31 = happySpecReduce_3  12 happyReduction_31
happyReduction_31 _
	(HappyAbsSyn12  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (ParenE   happy_var_2
	)
happyReduction_31 _ _ _  = notHappyAtAll 

happyReduce_32 = happySpecReduce_2  12 happyReduction_32
happyReduction_32 (HappyAbsSyn12  happy_var_2)
	_
	 =  HappyAbsSyn12
		 (NotE    happy_var_2
	)
happyReduction_32 _ _  = notHappyAtAll 

happyReduce_33 = happySpecReduce_1  13 happyReduction_33
happyReduction_33 (HappyAbsSyn11  happy_var_1)
	 =  HappyAbsSyn13
		 (DeclS  happy_var_1
	)
happyReduction_33 _  = notHappyAtAll 

happyReduce_34 = happySpecReduce_3  13 happyReduction_34
happyReduction_34 (HappyAbsSyn12  happy_var_3)
	_
	(HappyAbsSyn12  happy_var_1)
	 =  HappyAbsSyn13
		 (AssignS  happy_var_1  happy_var_3
	)
happyReduction_34 _ _ _  = notHappyAtAll 

happyReduce_35 = happyReduce 4 13 happyReduction_35
happyReduction_35 (_ `HappyStk`
	(HappyAbsSyn18  happy_var_3) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn12  happy_var_1) `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (CallS  happy_var_1    happy_var_3
	) `HappyStk` happyRest

happyReduce_36 = happyReduce 7 13 happyReduction_36
happyReduction_36 (_ `HappyStk`
	(HappyAbsSyn26  happy_var_6) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn12  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (SwitchS    happy_var_3   happy_var_6
	) `HappyStk` happyRest

happyReduce_37 = happySpecReduce_1  13 happyReduction_37
happyReduction_37 _
	 =  HappyAbsSyn13
		 (BreakS
	)

happyReduce_38 = happyReduce 11 13 happyReduction_38
happyReduction_38 (_ `HappyStk`
	(HappyAbsSyn28  happy_var_10) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn28  happy_var_6) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn12  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (IfS    happy_var_3   happy_var_6    happy_var_10
	) `HappyStk` happyRest

happyReduce_39 = happyReduce 7 13 happyReduction_39
happyReduction_39 (_ `HappyStk`
	(HappyAbsSyn28  happy_var_6) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn12  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (WhenS    happy_var_3   happy_var_6
	) `HappyStk` happyRest

happyReduce_40 = happyReduce 7 13 happyReduction_40
happyReduction_40 (_ `HappyStk`
	(HappyAbsSyn28  happy_var_6) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn12  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (WhileS    happy_var_3   happy_var_6
	) `HappyStk` happyRest

happyReduce_41 = happyReduce 4 13 happyReduction_41
happyReduction_41 (_ `HappyStk`
	(HappyAbsSyn12  happy_var_3) `HappyStk`
	_ `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn13
		 (ReturnS      happy_var_3
	) `HappyStk` happyRest

happyReduce_42 = happySpecReduce_1  13 happyReduction_42
happyReduction_42 _
	 =  HappyAbsSyn13
		 (RetVoidS
	)

happyReduce_43 = happySpecReduce_0  13 happyReduction_43
happyReduction_43  =  HappyAbsSyn13
		 (NoOpS
	)

happyReduce_44 = happySpecReduce_1  13 happyReduction_44
happyReduction_44 (HappyAbsSyn28  happy_var_1)
	 =  HappyAbsSyn13
		 (BlockS  happy_var_1
	)
happyReduction_44 _  = notHappyAtAll 

happyReduce_45 = happySpecReduce_2  13 happyReduction_45
happyReduction_45 _
	(HappyAbsSyn12  happy_var_1)
	 =  HappyAbsSyn13
		 (IncS  happy_var_1
	)
happyReduction_45 _ _  = notHappyAtAll 

happyReduce_46 = happySpecReduce_2  13 happyReduction_46
happyReduction_46 _
	(HappyAbsSyn12  happy_var_1)
	 =  HappyAbsSyn13
		 (DecS  happy_var_1
	)
happyReduction_46 _ _  = notHappyAtAll 

happyReduce_47 = happyReduce 4 14 happyReduction_47
happyReduction_47 ((HappyAbsSyn28  happy_var_4) `HappyStk`
	_ `HappyStk`
	(HappyAbsSyn15  happy_var_2) `HappyStk`
	_ `HappyStk`
	happyRest)
	 = HappyAbsSyn14
		 (SwitchAlt   happy_var_2   happy_var_4
	) `HappyStk` happyRest

happyReduce_48 = happySpecReduce_2  14 happyReduction_48
happyReduction_48 (HappyAbsSyn28  happy_var_2)
	_
	 =  HappyAbsSyn14
		 (DefaultAlt   happy_var_2
	)
happyReduction_48 _ _  = notHappyAtAll 

happyReduce_49 = happySpecReduce_1  15 happyReduction_49
happyReduction_49 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (StringL  (unTString happy_var_1)
	)
happyReduction_49 _  = notHappyAtAll 

happyReduce_50 = happySpecReduce_1  15 happyReduction_50
happyReduction_50 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (CharL  (unTChar happy_var_1)
	)
happyReduction_50 _  = notHappyAtAll 

happyReduce_51 = happySpecReduce_1  15 happyReduction_51
happyReduction_51 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (NmbrL  (unTNumber happy_var_1)
	)
happyReduction_51 _  = notHappyAtAll 

happyReduce_52 = happySpecReduce_1  15 happyReduction_52
happyReduction_52 (HappyTerminal happy_var_1)
	 =  HappyAbsSyn15
		 (EnumL  (unTUident happy_var_1)
	)
happyReduction_52 _  = notHappyAtAll 

happyReduce_53 = happySpecReduce_1  16 happyReduction_53
happyReduction_53 (HappyAbsSyn17  happy_var_1)
	 =  HappyAbsSyn16
		 (reverse happy_var_1
	)
happyReduction_53 _  = notHappyAtAll 

happyReduce_54 = happySpecReduce_0  16 happyReduction_54
happyReduction_54  =  HappyAbsSyn16
		 ([]
	)

happyReduce_55 = happySpecReduce_1  17 happyReduction_55
happyReduction_55 (HappyAbsSyn9  happy_var_1)
	 =  HappyAbsSyn17
		 ([happy_var_1]
	)
happyReduction_55 _  = notHappyAtAll 

happyReduce_56 = happySpecReduce_3  17 happyReduction_56
happyReduction_56 (HappyAbsSyn9  happy_var_3)
	_
	(HappyAbsSyn17  happy_var_1)
	 =  HappyAbsSyn17
		 (happy_var_3 : happy_var_1
	)
happyReduction_56 _ _ _  = notHappyAtAll 

happyReduce_57 = happySpecReduce_1  18 happyReduction_57
happyReduction_57 (HappyAbsSyn19  happy_var_1)
	 =  HappyAbsSyn18
		 (reverse happy_var_1
	)
happyReduction_57 _  = notHappyAtAll 

happyReduce_58 = happySpecReduce_1  19 happyReduction_58
happyReduction_58 (HappyAbsSyn12  happy_var_1)
	 =  HappyAbsSyn19
		 ([happy_var_1]
	)
happyReduction_58 _  = notHappyAtAll 

happyReduce_59 = happySpecReduce_3  19 happyReduction_59
happyReduction_59 (HappyAbsSyn12  happy_var_3)
	_
	(HappyAbsSyn19  happy_var_1)
	 =  HappyAbsSyn19
		 (happy_var_3 : happy_var_1
	)
happyReduction_59 _ _ _  = notHappyAtAll 

happyReduce_60 = happySpecReduce_1  20 happyReduction_60
happyReduction_60 (HappyAbsSyn21  happy_var_1)
	 =  HappyAbsSyn20
		 (reverse happy_var_1
	)
happyReduction_60 _  = notHappyAtAll 

happyReduce_61 = happySpecReduce_1  21 happyReduction_61
happyReduction_61 (HappyAbsSyn10  happy_var_1)
	 =  HappyAbsSyn21
		 ([happy_var_1]
	)
happyReduction_61 _  = notHappyAtAll 

happyReduce_62 = happySpecReduce_3  21 happyReduction_62
happyReduction_62 (HappyAbsSyn10  happy_var_3)
	_
	(HappyAbsSyn21  happy_var_1)
	 =  HappyAbsSyn21
		 (happy_var_3 : happy_var_1
	)
happyReduction_62 _ _ _  = notHappyAtAll 

happyReduce_63 = happySpecReduce_1  22 happyReduction_63
happyReduction_63 (HappyAbsSyn23  happy_var_1)
	 =  HappyAbsSyn22
		 (reverse happy_var_1
	)
happyReduction_63 _  = notHappyAtAll 

happyReduce_64 = happySpecReduce_0  22 happyReduction_64
happyReduction_64  =  HappyAbsSyn22
		 ([]
	)

happyReduce_65 = happySpecReduce_2  23 happyReduction_65
happyReduction_65 _
	(HappyAbsSyn11  happy_var_1)
	 =  HappyAbsSyn23
		 ([happy_var_1]
	)
happyReduction_65 _ _  = notHappyAtAll 

happyReduce_66 = happySpecReduce_3  23 happyReduction_66
happyReduction_66 _
	(HappyAbsSyn11  happy_var_2)
	(HappyAbsSyn23  happy_var_1)
	 =  HappyAbsSyn23
		 (happy_var_2 : happy_var_1
	)
happyReduction_66 _ _ _  = notHappyAtAll 

happyReduce_67 = happySpecReduce_1  24 happyReduction_67
happyReduction_67 (HappyAbsSyn25  happy_var_1)
	 =  HappyAbsSyn24
		 (reverse happy_var_1
	)
happyReduction_67 _  = notHappyAtAll 

happyReduce_68 = happySpecReduce_0  24 happyReduction_68
happyReduction_68  =  HappyAbsSyn24
		 ([]
	)

happyReduce_69 = happySpecReduce_1  25 happyReduction_69
happyReduction_69 (HappyAbsSyn11  happy_var_1)
	 =  HappyAbsSyn25
		 ([happy_var_1]
	)
happyReduction_69 _  = notHappyAtAll 

happyReduce_70 = happySpecReduce_3  25 happyReduction_70
happyReduction_70 (HappyAbsSyn11  happy_var_3)
	_
	(HappyAbsSyn25  happy_var_1)
	 =  HappyAbsSyn25
		 (happy_var_3 : happy_var_1
	)
happyReduction_70 _ _ _  = notHappyAtAll 

happyReduce_71 = happySpecReduce_1  26 happyReduction_71
happyReduction_71 (HappyAbsSyn27  happy_var_1)
	 =  HappyAbsSyn26
		 (reverse happy_var_1
	)
happyReduction_71 _  = notHappyAtAll 

happyReduce_72 = happySpecReduce_0  26 happyReduction_72
happyReduction_72  =  HappyAbsSyn26
		 ([]
	)

happyReduce_73 = happySpecReduce_1  27 happyReduction_73
happyReduction_73 (HappyAbsSyn14  happy_var_1)
	 =  HappyAbsSyn27
		 ([happy_var_1]
	)
happyReduction_73 _  = notHappyAtAll 

happyReduce_74 = happySpecReduce_2  27 happyReduction_74
happyReduction_74 (HappyAbsSyn14  happy_var_2)
	(HappyAbsSyn27  happy_var_1)
	 =  HappyAbsSyn27
		 (happy_var_2 : happy_var_1
	)
happyReduction_74 _ _  = notHappyAtAll 

happyReduce_75 = happySpecReduce_1  28 happyReduction_75
happyReduction_75 (HappyAbsSyn29  happy_var_1)
	 =  HappyAbsSyn28
		 (reverse happy_var_1
	)
happyReduction_75 _  = notHappyAtAll 

happyReduce_76 = happySpecReduce_0  28 happyReduction_76
happyReduction_76  =  HappyAbsSyn28
		 ([]
	)

happyReduce_77 = happySpecReduce_2  29 happyReduction_77
happyReduction_77 _
	(HappyAbsSyn13  happy_var_1)
	 =  HappyAbsSyn29
		 ([happy_var_1]
	)
happyReduction_77 _ _  = notHappyAtAll 

happyReduce_78 = happySpecReduce_3  29 happyReduction_78
happyReduction_78 _
	(HappyAbsSyn13  happy_var_2)
	(HappyAbsSyn29  happy_var_1)
	 =  HappyAbsSyn29
		 (happy_var_2 : happy_var_1
	)
happyReduction_78 _ _ _  = notHappyAtAll 

happyReduce_79 = happySpecReduce_1  30 happyReduction_79
happyReduction_79 (HappyAbsSyn31  happy_var_1)
	 =  HappyAbsSyn30
		 (reverse happy_var_1
	)
happyReduction_79 _  = notHappyAtAll 

happyReduce_80 = happySpecReduce_0  30 happyReduction_80
happyReduction_80  =  HappyAbsSyn30
		 ([]
	)

happyReduce_81 = happySpecReduce_2  31 happyReduction_81
happyReduction_81 _
	(HappyAbsSyn6  happy_var_1)
	 =  HappyAbsSyn31
		 ([happy_var_1]
	)
happyReduction_81 _ _  = notHappyAtAll 

happyReduce_82 = happySpecReduce_3  31 happyReduction_82
happyReduction_82 _
	(HappyAbsSyn6  happy_var_2)
	(HappyAbsSyn31  happy_var_1)
	 =  HappyAbsSyn31
		 (happy_var_2 : happy_var_1
	)
happyReduction_82 _ _ _  = notHappyAtAll 

happyReduce_83 = happySpecReduce_1  32 happyReduction_83
happyReduction_83 (HappyAbsSyn33  happy_var_1)
	 =  HappyAbsSyn32
		 (reverse happy_var_1
	)
happyReduction_83 _  = notHappyAtAll 

happyReduce_84 = happySpecReduce_0  32 happyReduction_84
happyReduction_84  =  HappyAbsSyn32
		 ([]
	)

happyReduce_85 = happySpecReduce_2  33 happyReduction_85
happyReduction_85 _
	(HappyAbsSyn7  happy_var_1)
	 =  HappyAbsSyn33
		 ([happy_var_1]
	)
happyReduction_85 _ _  = notHappyAtAll 

happyReduce_86 = happySpecReduce_3  33 happyReduction_86
happyReduction_86 _
	(HappyAbsSyn7  happy_var_2)
	(HappyAbsSyn33  happy_var_1)
	 =  HappyAbsSyn33
		 (happy_var_2 : happy_var_1
	)
happyReduction_86 _ _ _  = notHappyAtAll 

happyReduce_87 = happySpecReduce_1  34 happyReduction_87
happyReduction_87 (HappyAbsSyn35  happy_var_1)
	 =  HappyAbsSyn34
		 (reverse happy_var_1
	)
happyReduction_87 _  = notHappyAtAll 

happyReduce_88 = happySpecReduce_0  34 happyReduction_88
happyReduction_88  =  HappyAbsSyn34
		 ([]
	)

happyReduce_89 = happySpecReduce_1  35 happyReduction_89
happyReduction_89 (HappyAbsSyn5  happy_var_1)
	 =  HappyAbsSyn35
		 ([happy_var_1]
	)
happyReduction_89 _  = notHappyAtAll 

happyReduce_90 = happySpecReduce_2  35 happyReduction_90
happyReduction_90 (HappyAbsSyn5  happy_var_2)
	(HappyAbsSyn35  happy_var_1)
	 =  HappyAbsSyn35
		 (happy_var_2 : happy_var_1
	)
happyReduction_90 _ _  = notHappyAtAll 

happyNewToken action sts stk [] =
	action 80 80 notHappyAtAll (HappyState action) sts stk []

happyNewToken action sts stk (tk:tks) =
	let cont i = action i i tk (HappyState action) sts stk tks in
	case tk of {
	TSymbol _ "\n" -> cont 36;
	TSymbol _ "\n#define" -> cont 37;
	TSymbol _ "\n#endif" -> cont 38;
	TSymbol _ "!" -> cont 39;
	TSymbol _ "#ifndef" -> cont 40;
	TSymbol _ "#include" -> cont 41;
	TSymbol _ "&" -> cont 42;
	TSymbol _ "(" -> cont 43;
	TSymbol _ ")" -> cont 44;
	TSymbol _ "*" -> cont 45;
	TSymbol _ "++" -> cont 46;
	TSymbol _ "," -> cont 47;
	TSymbol _ "--" -> cont 48;
	TSymbol _ "->" -> cont 49;
	TSymbol _ "." -> cont 50;
	TSymbol _ ":" -> cont 51;
	TSymbol _ ";" -> cont 52;
	TSymbol _ "<" -> cont 53;
	TSymbol _ "=" -> cont 54;
	TSymbol _ ">" -> cont 55;
	TSymbol _ "[" -> cont 56;
	TSymbol _ "]" -> cont 57;
	TSymbol _ "alloca" -> cont 58;
	TSymbol _ "break" -> cont 59;
	TSymbol _ "case" -> cont 60;
	TSymbol _ "default:" -> cont 61;
	TSymbol _ "else" -> cont 62;
	TSymbol _ "enum" -> cont 63;
	TSymbol _ "if" -> cont 64;
	TSymbol _ "return" -> cont 65;
	TSymbol _ "sizeof" -> cont 66;
	TSymbol _ "struct" -> cont 67;
	TSymbol _ "switch" -> cont 68;
	TSymbol _ "typedef" -> cont 69;
	TSymbol _ "union" -> cont 70;
	TSymbol _ "while" -> cont 71;
	TSymbol _ "{" -> cont 72;
	TSymbol _ "}" -> cont 73;
	TUident _ _ -> cont 74;
	TUsym _ _ -> cont 75;
	TLident _ _ -> cont 76;
	TString _ _ -> cont 77;
	TChar _ _ -> cont 78;
	TNumber _ _ -> cont 79;
	_ -> happyError' (tk:tks)
	}

happyError_ tk tks = happyError' (tk:tks)

newtype HappyIdentity a = HappyIdentity a
happyIdentity = HappyIdentity
happyRunIdentity (HappyIdentity a) = a

instance Monad HappyIdentity where
    return = HappyIdentity
    (HappyIdentity p) >>= q = q p

happyThen :: () => HappyIdentity a -> (a -> HappyIdentity b) -> HappyIdentity b
happyThen = (>>=)
happyReturn :: () => a -> HappyIdentity a
happyReturn = (return)
happyThen1 m k tks = (>>=) m (\a -> k a tks)
happyReturn1 :: () => a -> b -> HappyIdentity a
happyReturn1 = \a tks -> (return) a
happyError' :: () => [((Token Point))] -> HappyIdentity a
happyError' = HappyIdentity . happyError

grmParse tks = happyRunIdentity happySomeParser where
  happySomeParser = happyThen (happyParse action_0 tks) (\x -> case x of {HappyAbsSyn4 z -> happyReturn z; _other -> notHappyAtAll })

happySeq = happyDontSeq



{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
{-# LINE 1 "<built-in>" #-}
{-# LINE 1 "<command-line>" #-}
{-# LINE 1 "templates/GenericTemplate.hs" #-}
-- Id: GenericTemplate.hs,v 1.26 2005/01/14 14:47:22 simonmar Exp 

{-# LINE 30 "templates/GenericTemplate.hs" #-}








{-# LINE 51 "templates/GenericTemplate.hs" #-}

{-# LINE 61 "templates/GenericTemplate.hs" #-}

{-# LINE 70 "templates/GenericTemplate.hs" #-}

infixr 9 `HappyStk`
data HappyStk a = HappyStk a (HappyStk a)

-----------------------------------------------------------------------------
-- starting the parse

happyParse start_state = happyNewToken start_state notHappyAtAll notHappyAtAll

-----------------------------------------------------------------------------
-- Accepting the parse

-- If the current token is (1), it means we've just accepted a partial
-- parse (a %partial parser).  We must ignore the saved token on the top of
-- the stack in this case.
happyAccept (1) tk st sts (_ `HappyStk` ans `HappyStk` _) =
	happyReturn1 ans
happyAccept j tk st sts (HappyStk ans _) = 
	 (happyReturn1 ans)

-----------------------------------------------------------------------------
-- Arrays only: do the next action

{-# LINE 148 "templates/GenericTemplate.hs" #-}

-----------------------------------------------------------------------------
-- HappyState data type (not arrays)



newtype HappyState b c = HappyState
        (Int ->                    -- token number
         Int ->                    -- token number (yes, again)
         b ->                           -- token semantic value
         HappyState b c ->              -- current state
         [HappyState b c] ->            -- state stack
         c)



-----------------------------------------------------------------------------
-- Shifting a token

happyShift new_state (1) tk st sts stk@(x `HappyStk` _) =
     let (i) = (case x of { HappyErrorToken (i) -> i }) in
--     trace "shifting the error token" $
     new_state i i tk (HappyState (new_state)) ((st):(sts)) (stk)

happyShift new_state i tk st sts stk =
     happyNewToken new_state ((st):(sts)) ((HappyTerminal (tk))`HappyStk`stk)

-- happyReduce is specialised for the common cases.

happySpecReduce_0 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_0 nt fn j tk st@((HappyState (action))) sts stk
     = action nt j tk st ((st):(sts)) (fn `HappyStk` stk)

happySpecReduce_1 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_1 nt fn j tk _ sts@(((st@(HappyState (action))):(_))) (v1`HappyStk`stk')
     = let r = fn v1 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_2 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_2 nt fn j tk _ ((_):(sts@(((st@(HappyState (action))):(_))))) (v1`HappyStk`v2`HappyStk`stk')
     = let r = fn v1 v2 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happySpecReduce_3 i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happySpecReduce_3 nt fn j tk _ ((_):(((_):(sts@(((st@(HappyState (action))):(_))))))) (v1`HappyStk`v2`HappyStk`v3`HappyStk`stk')
     = let r = fn v1 v2 v3 in
       happySeq r (action nt j tk st sts (r `HappyStk` stk'))

happyReduce k i fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyReduce k nt fn j tk st sts stk
     = case happyDrop (k - ((1) :: Int)) sts of
	 sts1@(((st1@(HappyState (action))):(_))) ->
        	let r = fn stk in  -- it doesn't hurt to always seq here...
       		happyDoSeq r (action nt j tk st1 sts1 r)

happyMonadReduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonadReduce k nt fn j tk st sts stk =
        happyThen1 (fn stk tk) (\r -> action nt j tk st1 sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk

happyMonad2Reduce k nt fn (1) tk st sts stk
     = happyFail (1) tk st sts stk
happyMonad2Reduce k nt fn j tk st sts stk =
       happyThen1 (fn stk tk) (\r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
       where (sts1@(((st1@(HappyState (action))):(_)))) = happyDrop k ((st):(sts))
             drop_stk = happyDropStk k stk





             new_state = action


happyDrop (0) l = l
happyDrop n ((_):(t)) = happyDrop (n - ((1) :: Int)) t

happyDropStk (0) l = l
happyDropStk n (x `HappyStk` xs) = happyDropStk (n - ((1)::Int)) xs

-----------------------------------------------------------------------------
-- Moving to a new state after a reduction

{-# LINE 246 "templates/GenericTemplate.hs" #-}
happyGoto action j tk st = action j j tk (HappyState action)


-----------------------------------------------------------------------------
-- Error recovery ((1) is the error token)

-- parse error if we are in recovery and we fail again
happyFail  (1) tk old_st _ stk =
--	trace "failing" $ 
    	happyError_ tk

{-  We don't need state discarding for our restricted implementation of
    "error".  In fact, it can cause some bogus parses, so I've disabled it
    for now --SDM

-- discard a state
happyFail  (1) tk old_st (((HappyState (action))):(sts)) 
						(saved_tok `HappyStk` _ `HappyStk` stk) =
--	trace ("discarding state, depth " ++ show (length stk))  $
	action (1) (1) tk (HappyState (action)) sts ((saved_tok`HappyStk`stk))
-}

-- Enter error recovery: generate an error token,
--                       save the old token and carry on.
happyFail  i tk (HappyState (action)) sts stk =
--      trace "entering error recovery" $
	action (1) (1) tk (HappyState (action)) sts ( (HappyErrorToken (i)) `HappyStk` stk)

-- Internal happy errors:

notHappyAtAll :: a
notHappyAtAll = error "Internal Happy error\n"

-----------------------------------------------------------------------------
-- Hack to get the typechecker to accept our action functions







-----------------------------------------------------------------------------
-- Seq-ing.  If the --strict flag is given, then Happy emits 
--	happySeq = happyDoSeq
-- otherwise it emits
-- 	happySeq = happyDontSeq

happyDoSeq, happyDontSeq :: a -> b -> b
happyDoSeq   a b = a `seq` b
happyDontSeq a b = b

-----------------------------------------------------------------------------
-- Don't inline any functions from the template.  GHC has a nasty habit
-- of deciding to inline happyGoto everywhere, which increases the size of
-- the generated parser quite a bit.

{-# LINE 311 "templates/GenericTemplate.hs" #-}
{-# NOINLINE happyShift #-}
{-# NOINLINE happySpecReduce_0 #-}
{-# NOINLINE happySpecReduce_1 #-}
{-# NOINLINE happySpecReduce_2 #-}
{-# NOINLINE happySpecReduce_3 #-}
{-# NOINLINE happyReduce #-}
{-# NOINLINE happyMonadReduce #-}
{-# NOINLINE happyGoto #-}
{-# NOINLINE happyFail #-}

-- end of Happy Template.
